/**
 * GENERATED by scripts/measure-genre-references.mjs — do not edit by hand.
 * Re-run `npm run references:genres` after changing generation content.
 *
 * Per-genre AUDIO TARGETS for the candidate sound rerank
 * (src/intent/audio-feedback.ts scoreAudioFit): RMS / crest / ZCR /
 * low-band ratio measured on FULL RENDERED SONGS per genre (the canonical
 * buildSong pipeline, curated bank, fixed seeds — medians of
 * 2 seeds), widened into corridors so mood/energy variation
 * inside a genre still lands inside its own target:
 *   rms/zcr/lowBandRatio: measured median ×[1/2.5, ×2.5]
 *   crestFactor: [max(1.2, m−4), m+8]
 * Consumed by audioTargetFor() — the hand-written table stays as the
 * fallback for genres missing from this file.
 */

/** Ranges for scoring candidate audio fit per genre (see audio-feedback.ts). */
export const GENERATED_AUDIO_TARGETS: Record<
  string,
  { rmsRange: [number, number]; crestRange: [number, number]; zcrRange: [number, number]; bassRange: [number, number] }
> = {
  house: {
    rmsRange: [0.1368, 0.8553],
    crestRange: [1.2, 10.7],
    zcrRange: [0.0118, 0.0735],
    bassRange: [0.5904, 0.8904],
  },
  techno: {
    rmsRange: [0.148, 0.9248],
    crestRange: [1.2, 10.5],
    zcrRange: [0.0098, 0.0613],
    bassRange: [0.6349, 0.9349],
  },
  trap: {
    rmsRange: [0.1351, 0.8443],
    crestRange: [1.2, 10.7],
    zcrRange: [0.0077, 0.0483],
    bassRange: [0.5587, 0.8587],
  },
  ambient: {
    rmsRange: [0.1557, 0.973],
    crestRange: [1.2, 10.3],
    zcrRange: [0.0079, 0.0495],
    bassRange: [0.6276, 0.9276],
  },
  drill: {
    rmsRange: [0.1002, 0.626],
    crestRange: [1.2, 11.6],
    zcrRange: [0.0224, 0.14],
    bassRange: [0.7158, 0.95],
  },
  phonk: {
    rmsRange: [0.0667, 0.4167],
    crestRange: [1.4, 13.4],
    zcrRange: [0.0121, 0.0758],
    bassRange: [0.6527, 0.95],
  },
  jersey: {
    rmsRange: [0.0504, 0.3152],
    crestRange: [3.2, 15.2],
    zcrRange: [0.0211, 0.132],
    bassRange: [0.4808, 0.7808],
  },
  dnb: {
    rmsRange: [0.1204, 0.7525],
    crestRange: [1.2, 11],
    zcrRange: [0.0168, 0.1053],
    bassRange: [0.5636, 0.8636],
  },
  hyperpop: {
    rmsRange: [0.0782, 0.4888],
    crestRange: [1.4, 13.4],
    zcrRange: [0.0302, 0.1885],
    bassRange: [0.5026, 0.8026],
  },
  ukg: {
    rmsRange: [0.0957, 0.598],
    crestRange: [1.2, 11.8],
    zcrRange: [0.0127, 0.0795],
    bassRange: [0.6658, 0.95],
  },
  boombap: {
    rmsRange: [0.0964, 0.6022],
    crestRange: [1.2, 12.6],
    zcrRange: [0.0216, 0.1348],
    bassRange: [0.663, 0.95],
  },
  amapiano: {
    rmsRange: [0.1101, 0.688],
    crestRange: [1.2, 11.3],
    zcrRange: [0.0058, 0.0365],
    bassRange: [0.6931, 0.95],
  },
  trance: {
    rmsRange: [0.098, 0.6128],
    crestRange: [1.2, 11.9],
    zcrRange: [0.0257, 0.1608],
    bassRange: [0.6484, 0.9484],
  },
  detroit: {
    rmsRange: [0.0864, 0.5398],
    crestRange: [1.2, 12.2],
    zcrRange: [0.0052, 0.0323],
    bassRange: [0.6225, 0.9225],
  },
  postrock: {
    rmsRange: [0.0602, 0.3762],
    crestRange: [2.1, 14.1],
    zcrRange: [0.0072, 0.0448],
    bassRange: [0.6545, 0.95],
  },
  chiptune: {
    rmsRange: [0.0658, 0.4115],
    crestRange: [1.7, 13.7],
    zcrRange: [0.0227, 0.142],
    bassRange: [0.5552, 0.8552],
  },
  eurodance: {
    rmsRange: [0.0772, 0.4825],
    crestRange: [1.2, 12.7],
    zcrRange: [0.0388, 0.2425],
    bassRange: [0.5241, 0.8241],
  },
  latin: {
    rmsRange: [0.1054, 0.6588],
    crestRange: [1.2, 11.5],
    zcrRange: [0.0086, 0.0537],
    bassRange: [0.6693, 0.95],
  },
  drone: {
    rmsRange: [0.0533, 0.3333],
    crestRange: [2.8, 14.8],
    zcrRange: [0.0026, 0.0165],
    bassRange: [0.7177, 0.95],
  },
};
