/**
 * GENERATED by scripts/measure-genre-references.mjs — do not edit by hand.
 * Re-run `npm run references:genres` after changing generation content
 * (grooves, kits, song forms, curated layer, master chain).
 *
 * Reference: full RENDERED SONGS per genre (buildSong → applySongCommand →
 * renderProject, curated bank, studio quality, fixed seeds, medians of
 * 2 seeds each). These are UNTRIMMED levels — the song builder
 * trims toward the target using these numbers.
 */

/** Every generated song exports at roughly this integrated loudness. */
export const SONG_LOUDNESS_TARGET_LUFS = -14;

/** Builder clamp — keep in sync with scripts/measure-genre-references.mjs. */
export const SONG_LOUDNESS_TRIM_LIMIT_DB = 6;

export interface GenreSongReference {
  /** Integrated loudness (LUFS) of the untrimmed reference render. */
  integrated: number;
  /** Peak-to-loudness ratio (dB) — transient headroom of the full mix. */
  punchPlrDb: number;
  /** Tonal tilt (dB): 10·log10(low≤220Hz / high≥4kHz), positive = low-heavy. */
  tiltDb: number;
  /** Reference song length in bars. */
  bars: number;
}

export const GENRE_REFERENCE: Record<string, GenreSongReference> = {
  house: { integrated: -7.4, punchPlrDb: 6.4, tiltDb: 22.6, bars: 44 },
  techno: { integrated: -7, punchPlrDb: 6, tiltDb: 24.5, bars: 44 },
  trap: { integrated: -7.7, punchPlrDb: 6.7, tiltDb: 21.7, bars: 52 },
  ambient: { integrated: -6.6, punchPlrDb: 5.6, tiltDb: 27.3, bars: 40 },
  drill: { integrated: -11.6, punchPlrDb: 10.6, tiltDb: 20.8, bars: 52 },
  phonk: { integrated: -12.1, punchPlrDb: 11.1, tiltDb: 20.3, bars: 52 },
  jersey: { integrated: -13.1, punchPlrDb: 12.1, tiltDb: 13.5, bars: 52 },
  dnb: { integrated: -7.8, punchPlrDb: 6.8, tiltDb: 21, bars: 64 },
  hyperpop: { integrated: -10.7, punchPlrDb: 9.7, tiltDb: 15.3, bars: 36 },
  ukg: { integrated: -10.7, punchPlrDb: 9.7, tiltDb: 22.1, bars: 72 },
  boombap: { integrated: -11, punchPlrDb: 10, tiltDb: 21.7, bars: 72 },
  amapiano: { integrated: -10.5, punchPlrDb: 9.5, tiltDb: 28.4, bars: 88 },
  trance: { integrated: -11.1, punchPlrDb: 10.1, tiltDb: 17.4, bars: 120 },
  detroit: { integrated: -11.3, punchPlrDb: 10.3, tiltDb: 20.1, bars: 96 },
  postrock: { integrated: -11.3, punchPlrDb: 10.3, tiltDb: 22.1, bars: 112 },
  chiptune: { integrated: -11.4, punchPlrDb: 10.4, tiltDb: 15.1, bars: 56 },
  eurodance: { integrated: -11.9, punchPlrDb: 10.9, tiltDb: 14.6, bars: 104 },
  latin: { integrated: -10.8, punchPlrDb: 9.8, tiltDb: 25.4, bars: 96 },
  drone: { integrated: -10.4, punchPlrDb: 9.4, tiltDb: 26.9, bars: 176 },
};
