/**
 * GENERATED by scripts/measure-genre-references.mjs — do not edit by hand.
 * Re-run `npm run references:genres` after changing generation content
 * (grooves, kits, song forms, curated layer, master chain).
 *
 * Reference: full RENDERED SONGS per genre (buildSong → applySongCommand →
 * renderProject, curated bank, studio quality, fixed seeds, medians of
 * 2 seeds each). These are UNTRIMMED levels — the song builder
 * trims toward the target using these numbers.
 */

/** Every generated song exports at roughly this integrated loudness. */
export const SONG_LOUDNESS_TARGET_LUFS = -14;

/** Builder clamp — keep in sync with scripts/measure-genre-references.mjs. */
export const SONG_LOUDNESS_TRIM_LIMIT_DB = 6;

export interface GenreSongReference {
  /** Integrated loudness (LUFS) of the untrimmed reference render. */
  integrated: number;
  /** Peak-to-loudness ratio (dB) — transient headroom of the full mix. */
  punchPlrDb: number;
  /** Tonal tilt (dB): 10·log10(low≤220Hz / high≥4kHz), positive = low-heavy. */
  tiltDb: number;
  /** Reference song length in bars. */
  bars: number;
}

export const GENRE_REFERENCE: Record<string, GenreSongReference> = {
  house: { integrated: -8.3, punchPlrDb: 7.3, tiltDb: 21.8, bars: 44 },
  techno: { integrated: -7.5, punchPlrDb: 6.5, tiltDb: 24.4, bars: 44 },
  trap: { integrated: -7.7, punchPlrDb: 6.7, tiltDb: 22.7, bars: 52 },
  ambient: { integrated: -7.3, punchPlrDb: 6.3, tiltDb: 27.8, bars: 40 },
  drill: { integrated: -9.1, punchPlrDb: 8.1, tiltDb: 21.4, bars: 52 },
  phonk: { integrated: -10.3, punchPlrDb: 9.3, tiltDb: 20.6, bars: 52 },
  jersey: { integrated: -11.8, punchPlrDb: 10.8, tiltDb: 14.9, bars: 52 },
  dnb: { integrated: -12.8, punchPlrDb: 11.8, tiltDb: 13.8, bars: 64 },
  hyperpop: { integrated: -11.7, punchPlrDb: 10.7, tiltDb: 17.7, bars: 36 },
  ukg: { integrated: -10, punchPlrDb: 9, tiltDb: 24, bars: 72 },
  boombap: { integrated: -9.9, punchPlrDb: 8.9, tiltDb: 24.1, bars: 72 },
  amapiano: { integrated: -10, punchPlrDb: 9, tiltDb: 28.3, bars: 88 },
  trance: { integrated: -10.2, punchPlrDb: 9.2, tiltDb: 22.3, bars: 120 },
  detroit: { integrated: -7, punchPlrDb: 6, tiltDb: 26.7, bars: 96 },
  postrock: { integrated: -10.6, punchPlrDb: 9.6, tiltDb: 23.1, bars: 112 },
  chiptune: { integrated: -11.4, punchPlrDb: 10.4, tiltDb: 16.9, bars: 56 },
  eurodance: { integrated: -11.4, punchPlrDb: 10.4, tiltDb: 16.5, bars: 104 },
  latin: { integrated: -10.1, punchPlrDb: 9.1, tiltDb: 27.5, bars: 96 },
  drone: { integrated: -10.4, punchPlrDb: 9.4, tiltDb: 26.4, bars: 176 },
};
