import { toGbnfGrammar } from "./model-schema";

/**
 * LOCAL INTENT MODEL — LOADER CONTRACT (pipeline step [C] runtime, see
 * docs/LOCAL-INTENT-MODEL.md).
 *
 * The manifest pins the trained artifact to THIS build of the engine:
 * `grammarSha256` is the SHA-256 of `toGbnfGrammar()` at training time and
 * is re-computed at load time — a vocabulary/action-schema change after the
 * model was trained makes the pair LOAD-REFUSED instead of silently
 * prompting a model with a grammar it never saw. That is the drift guard
 * between `model-schema.ts` (single source of the action vocabulary) and
 * any binary artifact.
 *
 * The manifest itself is generated by the future training script next to
 * the artifact (`public/models/intent-model-v1.manifest.json` + the GGUF it
 * describes). An origin without the artifact serves 404 — the loader
 * reports unavailable and the deterministic parsers remain the engine.
 */

export type IntentModelMode = "off" | "on";
export type IntentModelState = "off" | "unavailable" | "loading" | "ready" | "error";

export interface IntentModelManifest {
  /** Model identity + version, e.g. "intent-model.v1". */
  intentModelVersion: string;
  /** Action-schema generation the model was trained against (MODEL_ACTIONS shape). */
  schemaVersion: number;
  /** SHA-256 (hex) of toGbnfGrammar() at training time — re-verified at load. */
  grammarSha256: string;
  runtime: {
    /** Loader-internal backend id, e.g. "wllama-gguf". */
    kind: string;
    /** Module URL (own origin) exporting `export`. */
    module: string;
    /** Named export returning an IntentLlmRuntime. */
    export: string;
  };
  model: {
    /** Model weights URL (own origin or pack cache). */
    url: string;
    /** Expected size in bytes — cheap sanity before hashing. */
    bytes: number;
    /** SHA-256 (hex) of the weights — verified before init. */
    sha256: string;
  };
  prompt: {
    system: string;
    /** Template with an `{instruction}` placeholder. */
    instructionTemplate: string;
  };
  generation: {
    maxTokens: number;
    temperature: number;
  };
  /** ONNX v1 student pin: the vocab artifact the decoder reads class lists
   * from (written by the trainer, hash-verified here). */
  features?: {
    version: string;
    vocabSha256: string;
    vocabSize: number;
    inputName: string;
    outputNames: string[];
    heads: IntentModelHead[];
  };
  /** Training/eval summary (display + gates), engine-ignored. */
  report?: Record<string, unknown>;
}

/** One closed classification head of the v1 student. Lives here (not in
 * model-decoder.ts) so the manifest validator can check it without pulling
 * the decoder graph into the worker bundle. */
export interface IntentModelHead {
  name: string;
  kind: "softmax" | "sigmoid";
  classes: string[];
}

export interface IntentModelVocab {
  version: 1;
  tokens: string[];
  trunk: number[];
  heads: IntentModelHead[];
}

/**
 * Release-gate verdict pin: the validate script patches `report.gatePassed`
 * to true ONLY when the assembled exact/kindOK/abstain gates pass on val +
 * golden. The loader refuses to register a model without it — an artifact
 * that exists is not an artifact that may act (the ranker shipped the same
 * way: shadow until its golden verdict said ready-for-active).
 */
export function manifestGatePassed(manifest: IntentModelManifest): boolean {
  return manifest.report?.["gatePassed"] === true;
}

export type IntentModelRequest =
  | { type: "load"; requestId: number; manifest: IntentModelManifest }
  | { type: "generate"; requestId: number; instruction: string }
  | { type: "reset"; requestId: number };

export type IntentModelResponse =
  | { type: "load"; requestId: number; ok: true }
  | { type: "load"; requestId: number; ok: false; error: string }
  | { type: "generate"; requestId: number; ok: true; text: string }
  | { type: "generate"; requestId: number; ok: false; error: string }
  | { type: "reset"; requestId: number; ok: true }
  | { type: "progress"; requestId: number; loaded: number; total: number };

/** What request() resolves with - progress ticks are filtered, never settle. */
export type IntentModelReply = Exclude<IntentModelResponse, { type: "progress" }>;

/**
 * The runtime adapter every vendored LLM backend must export. Weights are
 * passed in as bytes (the worker fetched + hash-verified them); the runtime
 * owns tokenization, the constrained-decoding grammar and generation.
 */
export interface IntentLlmRuntime {
  load(init: {
    weights: ArrayBuffer;
    grammar: string;
    system: string;
    instructionTemplate: string;
    maxTokens: number;
    temperature: number;
  }): Promise<void>;
  generate(prompt: string): Promise<string>;
  dispose?(): void;
}

const HEX = /^[0-9a-f]{64}$/;

export function isIntentModelManifest(value: unknown): value is IntentModelManifest {
  if (value == null || typeof value !== "object") return false;
  const m = value as Partial<IntentModelManifest>;
  if (typeof m.intentModelVersion !== "string" || m.intentModelVersion.length === 0) return false;
  if (typeof m.schemaVersion !== "number" || !Number.isInteger(m.schemaVersion) || m.schemaVersion < 1) return false;
  if (typeof m.grammarSha256 !== "string" || !HEX.test(m.grammarSha256)) return false;
  if (m.runtime == null || typeof m.runtime !== "object") return false;
  if (typeof m.runtime.kind !== "string" || m.runtime.kind.length === 0) return false;
  if (typeof m.runtime.module !== "string" || !m.runtime.module.startsWith("/")) return false;
  if (typeof m.runtime.export !== "string" || m.runtime.export.length === 0) return false;
  if (m.model == null || typeof m.model !== "object") return false;
  if (typeof m.model.url !== "string" || !m.model.url.startsWith("/")) return false;
  if (typeof m.model.bytes !== "number" || !Number.isInteger(m.model.bytes) || m.model.bytes <= 0) return false;
  if (typeof m.model.sha256 !== "string" || !HEX.test(m.model.sha256)) return false;
  if (m.prompt == null || typeof m.prompt !== "object") return false;
  if (typeof m.prompt.system !== "string" || m.prompt.system.length === 0) return false;
  if (typeof m.prompt.instructionTemplate !== "string" || !m.prompt.instructionTemplate.includes("{instruction}")) {
    return false;
  }
  if (m.generation == null || typeof m.generation !== "object") return false;
  if (typeof m.generation.maxTokens !== "number" || !Number.isInteger(m.generation.maxTokens)) return false;
  if (m.generation.maxTokens < 1 || m.generation.maxTokens > 512) return false;
  if (typeof m.generation.temperature !== "number" || !Number.isFinite(m.generation.temperature)) return false;
  if (m.generation.temperature < 0 || m.generation.temperature > 2) return false;
  if (m.features !== undefined) {
    const f = m.features;
    if (typeof f.version !== "string" || f.version.length === 0) return false;
    if (typeof f.vocabSha256 !== "string" || !HEX.test(f.vocabSha256)) return false;
    if (typeof f.vocabSize !== "number" || !Number.isInteger(f.vocabSize) || f.vocabSize <= 0) return false;
    if (typeof f.inputName !== "string" || f.inputName.length === 0) return false;
    if (!Array.isArray(f.outputNames) || f.outputNames.some((name) => typeof name !== "string")) return false;
    if (!Array.isArray(f.heads) || f.heads.length === 0) return false;
    for (const head of f.heads) {
      if (head == null || typeof head !== "object") return false;
      if (typeof head.name !== "string" || head.name.length === 0) return false;
      if (head.kind !== "softmax" && head.kind !== "sigmoid") return false;
      if (!Array.isArray(head.classes) || head.classes.length === 0) return false;
      if (head.classes.some((cls) => typeof cls !== "string")) return false;
    }
  }
  return true;
}

async function sha256Hex(data: ArrayBuffer | string): Promise<string> {
  const bytes = typeof data === "string" ? new TextEncoder().encode(data) : new Uint8Array(data);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * The load-time drift guard: the manifest must pin EXACTLY the grammar this
 * build generates from `model-schema.ts`. Returns an error string when the
 * pair is incompatible (the worker refuses the load), null when it matches.
 */
export async function manifestGrammarDrift(manifest: IntentModelManifest): Promise<string | null> {
  const digest = await sha256Hex(toGbnfGrammar());
  if (digest !== manifest.grammarSha256.toLowerCase()) {
    return `grammar drift: manifest pins ${manifest.grammarSha256.slice(0, 12)}… but this build generates ${digest.slice(0, 12)}… — retrain or repin the model`;
  }
  return null;
}

export async function sha256Mismatch(weights: ArrayBuffer, expectedHex: string): Promise<string | null> {
  const digest = await sha256Hex(weights);
  if (digest !== expectedHex.toLowerCase()) {
    return `model hash mismatch: expected ${expectedHex.slice(0, 12)}… got ${digest.slice(0, 12)}…`;
  }
  return null;
}

/** Build the prompt the constrained model sees (system + filled template). */
export function buildIntentModelPrompt(manifest: IntentModelManifest, instruction: string): string {
  return `${manifest.prompt.system}\n${manifest.prompt.instructionTemplate.replace("{instruction}", instruction)}`;
}
