import type { InstrumentPreset } from "./types";

/**
 * Factory presets are pure data, curated by genre and mood. Parameter values
 * stay inside each instrument's defined ranges so they clamp cleanly.
 */
export const FACTORY_PRESETS: InstrumentPreset[] = [
  /* ================= Bass Synth ================= */
  {
    id: "factory.bass.house.pluck",
    name: "House Pluck",
    instrument: "bass",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["plucky", "punchy", "clean"],
    params: { sub: 0.4, body: 0.55, punch: 0.75, grit: 0.15, movement: 0.1, width: 0.2, cutoff: 900, resonance: 1.4, level: -6 },
  },
  {
    id: "factory.bass.house.deep",
    name: "Deep House Bass",
    instrument: "bass",
    genre: "house",
    mood: ["deep", "warm"],
    tags: ["deep", "warm", "round"],
    params: { sub: 0.7, body: 0.7, punch: 0.4, grit: 0.1, movement: 0.08, width: 0.25, cutoff: 600, resonance: 1.0, level: -5 },
  },
  {
    id: "factory.bass.house.warmsub",
    name: "Warm Sub",
    instrument: "bass",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["sub", "warm", "round"],
    params: { sub: 0.75, body: 0.6, punch: 0.35, grit: 0.08, movement: 0.05, width: 0.15, cutoff: 520, resonance: 0.8, level: -5 },
  },
  {
    id: "factory.bass.house.pluckbass",
    name: "Pluck Bass",
    instrument: "bass",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["pluck", "bright", "punchy"],
    params: { sub: 0.3, body: 0.4, punch: 0.85, grit: 0.12, movement: 0.08, width: 0.2, cutoff: 1100, resonance: 1.6, level: -7 },
  },
  {
    id: "factory.bass.house.techhouse",
    name: "Tech House Bass",
    instrument: "bass",
    genre: "house",
    mood: ["aggressive", "dark"],
    tags: ["tech", "punchy", "gritty"],
    params: { sub: 0.6, body: 0.5, punch: 0.65, grit: 0.32, movement: 0.15, width: 0.18, cutoff: 700, resonance: 1.8, level: -6 },
  },
  {
    id: "factory.bass.techno.rumble",
    name: "Techno Rumble",
    instrument: "bass",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["dark", "driving", "gritty"],
    params: { sub: 0.8, body: 0.45, punch: 0.3, grit: 0.55, movement: 0.25, width: 0.1, cutoff: 420, resonance: 2.5, level: -6 },
  },
  {
    id: "factory.bass.techno.acid",
    name: "Acid Line",
    instrument: "bass",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["acid", "resonant", "moving"],
    params: { sub: 0.3, body: 0.5, punch: 0.6, grit: 0.4, movement: 0.6, width: 0.15, cutoff: 800, resonance: 6.5, level: -7 },
  },
  {
    id: "factory.bass.techno.reese",
    name: "Reese",
    instrument: "bass",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["reese", "wide", "moving"],
    params: { sub: 0.65, body: 0.72, punch: 0.4, grit: 0.5, movement: 0.4, width: 0.7, cutoff: 650, resonance: 1.6, level: -7 },
  },
  {
    id: "factory.bass.techno.darkpulse",
    name: "Dark Pulse",
    instrument: "bass",
    genre: "techno",
    mood: ["dark", "deep"],
    tags: ["dark", "pulse", "static"],
    params: { sub: 0.85, body: 0.5, punch: 0.5, grit: 0.38, movement: 0.2, width: 0.12, cutoff: 380, resonance: 2.6, level: -6 },
  },
  {
    id: "factory.bass.trap.808slide",
    name: "Trap 808 Bass",
    instrument: "bass",
    genre: "trap",
    mood: ["deep", "aggressive"],
    tags: ["sub", "heavy", "deep"],
    params: { sub: 0.9, body: 0.6, punch: 0.55, grit: 0.3, movement: 0.05, width: 0.1, cutoff: 500, resonance: 1.2, level: -4 },
  },
  {
    id: "factory.bass.trap.fmgrowl",
    name: "FM Growl",
    instrument: "bass",
    genre: "trap",
    mood: ["dark", "aggressive"],
    tags: ["fm", "growl", "aggressive"],
    params: { sub: 0.55, body: 0.6, punch: 0.45, grit: 0.7, movement: 0.55, width: 0.3, cutoff: 620, resonance: 3.4, level: -6 },
  },
  {
    id: "factory.bass.trap.walnut",
    name: "808 Walnut",
    instrument: "bass",
    genre: "trap",
    mood: ["clean", "warm"],
    tags: ["808", "clean", "round"],
    params: { sub: 0.85, body: 0.55, punch: 0.5, grit: 0.18, movement: 0.05, width: 0.12, cutoff: 460, resonance: 1.0, level: -4 },
  },
  {
    id: "factory.bass.ambient.drone",
    name: "Ambient Drone Bass",
    instrument: "bass",
    genre: "ambient",
    mood: ["atmosphere", "deep"],
    tags: ["drone", "soft", "wide"],
    params: { sub: 0.75, body: 0.8, punch: 0.1, grit: 0.05, movement: 0.4, width: 0.6, cutoff: 350, resonance: 0.8, level: -8 },
  },
  {
    id: "factory.bass.ambient.subdrone",
    name: "Sub Drone",
    instrument: "bass",
    genre: "ambient",
    mood: ["deep", "atmosphere"],
    tags: ["sub", "drone", "deep"],
    params: { sub: 0.9, body: 0.75, punch: 0.08, grit: 0.04, movement: 0.3, width: 0.5, cutoff: 300, resonance: 0.7, level: -8 },
  },
  {
    id: "factory.bass.score.low",
    name: "Score Low Bed",
    instrument: "bass",
    genre: "score",
    mood: ["deep", "atmosphere"],
    tags: ["cinematic", "deep", "static"],
    params: { sub: 0.85, body: 0.75, punch: 0.15, grit: 0.12, movement: 0.2, width: 0.45, cutoff: 400, resonance: 1.0, level: -7 },
  },
  {
    id: "factory.bass.score.cinemalow",
    name: "Cinema Low",
    instrument: "bass",
    genre: "score",
    mood: ["atmosphere", "dark"],
    tags: ["cinematic", "dark", "low"],
    params: { sub: 0.8, body: 0.7, punch: 0.2, grit: 0.2, movement: 0.25, width: 0.5, cutoff: 360, resonance: 1.2, level: -7 },
  },

  /* ================= Analog Synth ================= */
  {
    id: "factory.analog.house.stab",
    name: "House Stab",
    instrument: "analog",
    genre: "house",
    mood: ["bright", "aggressive"],
    tags: ["stab", "bright", "chord"],
    params: { oscA: 2, oscB: 2, oscBDetune: 10, subLevel: 0.2, noiseLevel: 0.03, cutoff: 7000, resonance: 1.2, filterEnv: 0.45, attack: 0.004, decay: 0.22, sustain: 0.35, release: 0.18, level: -7 },
  },
  {
    id: "factory.analog.house.plucklead",
    name: "House Pluck Lead",
    instrument: "analog",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["pluck", "lead", "clean"],
    params: { oscA: 2, oscB: 0, oscBDetune: 6, subLevel: 0.15, noiseLevel: 0.02, cutoff: 8500, resonance: 1.6, filterEnv: 0.55, attack: 0.002, decay: 0.18, sustain: 0.2, release: 0.15, level: -8 },
  },
  {
    id: "factory.analog.house.chords",
    name: "House Chords",
    instrument: "analog",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["chord", "warm", "keys"],
    params: { oscA: 1, oscB: 1, oscBDetune: 8, subLevel: 0.2, noiseLevel: 0.03, cutoff: 5200, resonance: 0.9, filterEnv: 0.28, attack: 0.008, decay: 0.4, sustain: 0.6, release: 0.25, level: -9 },
  },
  {
    id: "factory.analog.house.arp",
    name: "Sparkle Arp",
    instrument: "analog",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["arp", "bright", "short"],
    params: { oscA: 2, oscB: 0, oscBDetune: 4, subLevel: 0.1, noiseLevel: 0.02, cutoff: 9000, resonance: 1.4, filterEnv: 0.6, attack: 0.001, decay: 0.1, sustain: 0.1, release: 0.08, level: -9 },
  },
  {
    id: "factory.analog.techno.stab",
    name: "Techno Stab",
    instrument: "analog",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["dark", "stab", "punchy"],
    params: { oscA: 2, oscB: 3, oscBDetune: 14, subLevel: 0.3, noiseLevel: 0.05, cutoff: 4200, resonance: 2.2, filterEnv: 0.5, attack: 0.003, decay: 0.2, sustain: 0.3, release: 0.12, level: -7 },
  },
  {
    id: "factory.analog.techno.lead",
    name: "Techno Acid Lead",
    instrument: "analog",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["acid", "resonant", "aggressive"],
    params: { oscA: 2, oscB: 2, oscBDetune: 8, subLevel: 0.1, noiseLevel: 0.02, cutoff: 3200, resonance: 7.5, filterEnv: 0.65, attack: 0.002, decay: 0.16, sustain: 0.4, release: 0.1, level: -8 },
  },
  {
    id: "factory.analog.techno.darkpluck",
    name: "Dark Pluck",
    instrument: "analog",
    genre: "techno",
    mood: ["dark", "clean"],
    tags: ["dark", "pluck", "short"],
    params: { oscA: 2, oscB: 2, oscBDetune: 10, subLevel: 0.2, noiseLevel: 0.03, cutoff: 3400, resonance: 2.5, filterEnv: 0.5, attack: 0.002, decay: 0.15, sustain: 0.15, release: 0.1, level: -8 },
  },
  {
    id: "factory.analog.techno.digikeys",
    name: "Digi Keys",
    instrument: "analog",
    genre: "techno",
    mood: ["clean", "bright"],
    tags: ["keys", "clean", "digital"],
    params: { oscA: 0, oscB: 1, oscBDetune: 3, subLevel: 0.1, noiseLevel: 0.02, cutoff: 7500, resonance: 1.0, filterEnv: 0.25, attack: 0.005, decay: 0.35, sustain: 0.5, release: 0.3, level: -9 },
  },
  {
    id: "factory.analog.trap.lead",
    name: "Trap Lead",
    instrument: "analog",
    genre: "trap",
    mood: ["bright", "clean"],
    tags: ["bright", "lead", "clean"],
    params: { oscA: 2, oscB: 3, oscBDetune: 10, subLevel: 0.1, noiseLevel: 0.02, cutoff: 5200, resonance: 2.0, filterEnv: 0.4, attack: 0.005, decay: 0.3, sustain: 0.4, release: 0.3, level: -12 },
  },
  {
    id: "factory.analog.trap.darkkeys",
    name: "Trap Dark Keys",
    instrument: "analog",
    genre: "trap",
    mood: ["dark", "warm"],
    tags: ["dark", "keys", "soft"],
    params: { oscA: 1, oscB: 0, oscBDetune: 5, subLevel: 0.2, noiseLevel: 0.03, cutoff: 2800, resonance: 1.0, filterEnv: 0.3, attack: 0.01, decay: 0.5, sustain: 0.5, release: 0.5, level: -10 },
  },
  {
    id: "factory.analog.trap.supersaw",
    name: "Supersaw Lead",
    instrument: "analog",
    genre: "trap",
    mood: ["bright", "aggressive"],
    tags: ["supersaw", "lead", "wide"],
    params: { oscA: 2, oscB: 2, oscBDetune: 22, subLevel: 0.15, noiseLevel: 0.03, cutoff: 6000, resonance: 1.5, filterEnv: 0.35, attack: 0.004, decay: 0.4, sustain: 0.5, release: 0.35, level: -11 },
  },
  {
    id: "factory.analog.ambient.pad",
    name: "Ambient Pad",
    instrument: "analog",
    genre: "ambient",
    mood: ["warm", "atmosphere"],
    tags: ["pad", "warm", "wide"],
    params: { oscA: 1, oscB: 1, oscBDetune: 12, subLevel: 0.15, noiseLevel: 0.06, cutoff: 2400, resonance: 0.8, filterEnv: 0.15, attack: 0.8, decay: 1.2, sustain: 0.8, release: 1.6, level: -10 },
  },
  {
    id: "factory.analog.ambient.vapor",
    name: "Vapor Keys",
    instrument: "analog",
    genre: "ambient",
    mood: ["atmosphere", "bright"],
    tags: ["keys", "vapor", "airy"],
    params: { oscA: 1, oscB: 0, oscBDetune: 9, subLevel: 0.1, noiseLevel: 0.05, cutoff: 3000, resonance: 0.7, filterEnv: 0.2, attack: 0.15, decay: 0.8, sustain: 0.6, release: 1.4, level: -11 },
  },
  {
    id: "factory.analog.ambient.softlead",
    name: "Soft Lead",
    instrument: "analog",
    genre: "ambient",
    mood: ["warm", "clean"],
    tags: ["lead", "soft", "warm"],
    params: { oscA: 1, oscB: 1, oscBDetune: 7, subLevel: 0.12, noiseLevel: 0.02, cutoff: 3800, resonance: 0.9, filterEnv: 0.25, attack: 0.06, decay: 0.5, sustain: 0.6, release: 0.6, level: -9 },
  },
  {
    id: "factory.analog.score.strings",
    name: "Score Strings",
    instrument: "analog",
    genre: "score",
    mood: ["warm", "atmosphere"],
    tags: ["cinematic", "warm", "moving"],
    params: { oscA: 2, oscB: 2, oscBDetune: 16, subLevel: 0.1, noiseLevel: 0.04, cutoff: 3600, resonance: 0.9, filterEnv: 0.2, attack: 0.5, decay: 0.8, sustain: 0.75, release: 1.2, level: -10 },
  },
  {
    id: "factory.analog.score.brass",
    name: "Brass Hit",
    instrument: "analog",
    genre: "score",
    mood: ["aggressive", "bright"],
    tags: ["brass", "cinematic", "hit"],
    params: { oscA: 2, oscB: 2, oscBDetune: 12, subLevel: 0.25, noiseLevel: 0.04, cutoff: 5200, resonance: 1.6, filterEnv: 0.55, attack: 0.01, decay: 0.3, sustain: 0.55, release: 0.3, level: -9 },
  },
  {
    id: "factory.analog.score.swell",
    name: "Atmos Swell",
    instrument: "analog",
    genre: "score",
    mood: ["atmosphere", "dark"],
    tags: ["swell", "cinematic", "atmosphere"],
    params: { oscA: 1, oscB: 2, oscBDetune: 18, subLevel: 0.2, noiseLevel: 0.08, cutoff: 2000, resonance: 1.4, filterEnv: 0.2, attack: 1.2, decay: 1.0, sustain: 0.8, release: 2.0, level: -10 },
  },

  /* ================= 808 Synth ================= */
  {
    id: "factory.808.trap.deep",
    name: "Deep Trap 808",
    instrument: "808",
    genre: "trap",
    mood: ["deep", "dark"],
    tags: ["sub", "long", "heavy"],
    params: { decay: 1.6, pitchDrop: 0.5, click: 0.3, drive: 0.35, tone: 0.3, gain: 0.9 },
  },
  {
    id: "factory.808.trap.punch",
    name: "Punch 808",
    instrument: "808",
    genre: "trap",
    mood: ["aggressive", "clean"],
    tags: ["punchy", "tight"],
    params: { decay: 0.6, pitchDrop: 0.55, click: 0.5, drive: 0.3, tone: 0.4, gain: 0.9 },
  },
  {
    id: "factory.808.trap.boomer",
    name: "Long Boomer",
    instrument: "808",
    genre: "trap",
    mood: ["deep", "warm"],
    tags: ["long", "boomy", "sub"],
    params: { decay: 3.0, pitchDrop: 0.45, click: 0.2, drive: 0.25, tone: 0.25, gain: 0.88 },
  },
  {
    id: "factory.808.trap.distorted",
    name: "Distorted 808",
    instrument: "808",
    genre: "trap",
    mood: ["aggressive", "dark"],
    tags: ["distorted", "aggressive"],
    params: { decay: 1.2, pitchDrop: 0.55, click: 0.45, drive: 0.8, tone: 0.5, gain: 0.82 },
  },
  {
    id: "factory.808.house.sub",
    name: "House Sub 808",
    instrument: "808",
    genre: "house",
    mood: ["clean", "warm"],
    tags: ["sub", "clean", "round"],
    params: { decay: 0.9, pitchDrop: 0.4, click: 0.35, drive: 0.2, tone: 0.35, gain: 0.85 },
  },
  {
    id: "factory.808.house.short",
    name: "Short 808",
    instrument: "808",
    genre: "house",
    mood: ["bright", "aggressive"],
    tags: ["short", "tight"],
    params: { decay: 0.35, pitchDrop: 0.5, click: 0.55, drive: 0.25, tone: 0.45, gain: 0.9 },
  },
  {
    id: "factory.808.house.punchy",
    name: "Punchy 808",
    instrument: "808",
    genre: "house",
    mood: ["aggressive", "bright"],
    tags: ["punchy", "tight"],
    params: { decay: 0.5, pitchDrop: 0.5, click: 0.6, drive: 0.35, tone: 0.45, gain: 0.9 },
  },
  {
    id: "factory.808.techno.boom",
    name: "Techno Boom",
    instrument: "808",
    genre: "techno",
    mood: ["dark", "deep"],
    tags: ["dark", "boomy"],
    params: { decay: 1.2, pitchDrop: 0.6, click: 0.25, drive: 0.45, tone: 0.25, gain: 0.85 },
  },
  {
    id: "factory.808.ambient.warm",
    name: "Warm 808",
    instrument: "808",
    genre: "ambient",
    mood: ["warm", "deep"],
    tags: ["warm", "soft", "round"],
    params: { decay: 2.0, pitchDrop: 0.3, click: 0.15, drive: 0.15, tone: 0.3, gain: 0.8 },
  },
  {
    id: "factory.808.score.impact",
    name: "Score Impact",
    instrument: "808",
    genre: "score",
    mood: ["deep", "atmosphere"],
    tags: ["cinematic", "impact", "deep"],
    params: { decay: 2.4, pitchDrop: 0.75, click: 0.4, drive: 0.3, tone: 0.2, gain: 0.9 },
  },

  /* ================= Sampler ================= */
  {
    id: "factory.sampler.house.pluck",
    name: "House Pluck",
    instrument: "sampler",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["pluck", "bright"],
    sampleId: "factory.tonal.pluck",
    params: { root: 60, attack: 0.003, release: 0.14, cutoff: 14000, resonance: 0.8, gain: 0.9 },
  },
  {
    id: "factory.sampler.house.stab",
    name: "House Stab",
    instrument: "sampler",
    genre: "house",
    mood: ["aggressive", "bright"],
    tags: ["stab", "chord"],
    sampleId: "factory.tonal.stab",
    params: { root: 60, attack: 0.002, release: 0.12, cutoff: 13000, resonance: 0.7, gain: 0.85 },
  },
  {
    id: "factory.sampler.house.mellow",
    name: "Mellow Pluck",
    instrument: "sampler",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["pluck", "warm"],
    sampleId: "factory.tonal.pluck",
    params: { root: 60, attack: 0.03, release: 0.35, cutoff: 7000, resonance: 0.6, gain: 0.8 },
  },
  {
    id: "factory.sampler.techno.stab",
    name: "Analog Stab",
    instrument: "sampler",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["stab", "dark"],
    sampleId: "factory.tonal.stab",
    params: { root: 60, attack: 0.001, release: 0.1, cutoff: 8000, resonance: 1.4, gain: 0.9 },
  },
  {
    id: "factory.sampler.ambient.keys",
    name: "Ambient Keys",
    instrument: "sampler",
    genre: "ambient",
    mood: ["warm", "atmosphere"],
    tags: ["keys", "soft", "clean"],
    sampleId: "factory.tonal.keys",
    params: { root: 60, attack: 0.02, release: 0.5, cutoff: 9000, resonance: 0.6, gain: 0.85 },
  },
  {
    id: "factory.sampler.ambient.piano",
    name: "Piano Keys",
    instrument: "sampler",
    genre: "ambient",
    mood: ["warm", "clean"],
    tags: ["piano", "keys", "clean"],
    sampleId: "factory.tonal.keys",
    params: { root: 60, attack: 0.004, release: 0.9, cutoff: 12000, resonance: 0.5, gain: 0.85 },
  },
  {
    id: "factory.sampler.score.bell",
    name: "Score Bell",
    instrument: "sampler",
    genre: "score",
    mood: ["bright", "atmosphere"],
    tags: ["bell", "clear", "lead"],
    sampleId: "factory.tonal.bell",
    params: { root: 72, attack: 0.002, release: 0.6, cutoff: 15000, resonance: 0.7, gain: 0.8 },
  },
  {
    id: "factory.sampler.score.bellpad",
    name: "Bell Pad",
    instrument: "sampler",
    genre: "score",
    mood: ["atmosphere", "warm"],
    tags: ["bell", "pad", "long"],
    sampleId: "factory.tonal.bell",
    params: { root: 60, attack: 0.1, release: 1.4, cutoff: 6000, resonance: 0.5, gain: 0.7 },
  },

  /* ================= Texture Synth ================= */
  {
    id: "factory.texture.ambient.drift",
    name: "Ambient Drift",
    instrument: "texture",
    genre: "ambient",
    mood: ["atmosphere", "warm"],
    tags: ["atmosphere", "evolving", "wide"],
    params: { color: 0.45, motion: 0.5, space: 0.6, density: 0.6, texture: 0.35, chaos: 0.15, level: -8 },
  },
  {
    id: "factory.texture.ambient.darkdrone",
    name: "Dark Drone",
    instrument: "texture",
    genre: "ambient",
    mood: ["dark", "deep"],
    tags: ["drone", "dark", "static"],
    params: { color: 0.2, motion: 0.25, space: 0.5, density: 0.8, texture: 0.5, chaos: 0.1, level: -9 },
  },
  {
    id: "factory.texture.ambient.shimmer",
    name: "Shimmer",
    instrument: "texture",
    genre: "ambient",
    mood: ["bright", "atmosphere"],
    tags: ["shimmer", "bright", "airy"],
    params: { color: 0.7, motion: 0.45, space: 0.65, density: 0.4, texture: 0.25, chaos: 0.2, level: -10 },
  },
  {
    id: "factory.texture.ambient.lushpad",
    name: "Lush Pad",
    instrument: "texture",
    genre: "ambient",
    mood: ["warm", "clean"],
    tags: ["pad", "lush", "warm"],
    params: { color: 0.55, motion: 0.35, space: 0.55, density: 0.7, texture: 0.3, chaos: 0.1, level: -9 },
  },
  {
    id: "factory.texture.ambient.deepsapce",
    name: "Deep Space",
    instrument: "texture",
    genre: "ambient",
    mood: ["deep", "dark"],
    tags: ["space", "deep", "dark"],
    params: { color: 0.15, motion: 0.3, space: 0.75, density: 0.85, texture: 0.45, chaos: 0.15, level: -9 },
  },
  {
    id: "factory.texture.ambient.wind",
    name: "Wind",
    instrument: "texture",
    genre: "ambient",
    mood: ["atmosphere", "clean"],
    tags: ["wind", "airy", "moving"],
    params: { color: 0.5, motion: 0.7, space: 0.4, density: 0.2, texture: 0.55, chaos: 0.6, level: -11 },
  },
  {
    id: "factory.texture.ambient.rain",
    name: "Rain",
    instrument: "texture",
    genre: "ambient",
    mood: ["dark", "atmosphere"],
    tags: ["rain", "warm", "textural"],
    params: { color: 0.35, motion: 0.55, space: 0.45, density: 0.3, texture: 0.7, chaos: 0.5, level: -11 },
  },
  {
    id: "factory.texture.score.bed",
    name: "Score Bed",
    instrument: "texture",
    genre: "score",
    mood: ["atmosphere", "warm"],
    tags: ["cinematic", "bed", "moving"],
    params: { color: 0.5, motion: 0.35, space: 0.5, density: 0.65, texture: 0.4, chaos: 0.12, level: -10 },
  },
  {
    id: "factory.texture.score.dronebed",
    name: "Drone Bed",
    instrument: "texture",
    genre: "score",
    mood: ["deep", "atmosphere"],
    tags: ["drone", "cinematic", "deep"],
    params: { color: 0.25, motion: 0.25, space: 0.6, density: 0.85, texture: 0.5, chaos: 0.08, level: -10 },
  },
  {
    id: "factory.texture.techno.industrial",
    name: "Industrial Texture",
    instrument: "texture",
    genre: "techno",
    mood: ["aggressive", "dark"],
    tags: ["dark", "gritty", "moving"],
    params: { color: 0.35, motion: 0.6, space: 0.35, density: 0.5, texture: 0.65, chaos: 0.4, level: -11 },
  },
  {
    id: "factory.texture.techno.glitch",
    name: "Glitch",
    instrument: "texture",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["glitch", "bright", "chaotic"],
    params: { color: 0.6, motion: 0.75, space: 0.3, density: 0.35, texture: 0.75, chaos: 0.8, level: -12 },
  },
  {
    id: "factory.texture.techno.warmpad",
    name: "Warm Pad",
    instrument: "texture",
    genre: "techno",
    mood: ["warm", "clean"],
    tags: ["pad", "warm", "clean"],
    params: { color: 0.55, motion: 0.3, space: 0.5, density: 0.7, texture: 0.3, chaos: 0.1, level: -9 },
  },
];