import type { InstrumentPreset } from "./types";

/**
 * Factory presets are pure data, grouped by the same genre tags the templates
 * use. Parameter values stay inside each instrument's defined ranges so they
 * clamp cleanly when applied.
 */
export const FACTORY_PRESETS: InstrumentPreset[] = [
  /* ---------------- Bass Synth ---------------- */
  {
    id: "factory.bass.house.pluck",
    name: "House Pluck",
    instrument: "bass",
    genre: "house",
    tags: ["plucky", "punchy", "clean"],
    params: { sub: 0.4, body: 0.55, punch: 0.75, grit: 0.15, movement: 0.1, width: 0.2, cutoff: 900, resonance: 1.4, level: -6 },
  },
  {
    id: "factory.bass.house.deep",
    name: "Deep House Bass",
    instrument: "bass",
    genre: "house",
    tags: ["deep", "warm", "round"],
    params: { sub: 0.7, body: 0.7, punch: 0.4, grit: 0.1, movement: 0.08, width: 0.25, cutoff: 600, resonance: 1.0, level: -5 },
  },
  {
    id: "factory.bass.techno.rumble",
    name: "Techno Rumble",
    instrument: "bass",
    genre: "techno",
    tags: ["dark", "driving", "gritty"],
    params: { sub: 0.8, body: 0.45, punch: 0.3, grit: 0.55, movement: 0.25, width: 0.1, cutoff: 420, resonance: 2.5, level: -6 },
  },
  {
    id: "factory.bass.techno.acid",
    name: "Acid Line",
    instrument: "bass",
    genre: "techno",
    tags: ["acid", "resonant", "moving"],
    params: { sub: 0.3, body: 0.5, punch: 0.6, grit: 0.4, movement: 0.6, width: 0.15, cutoff: 800, resonance: 6.5, level: -7 },
  },
  {
    id: "factory.bass.trap.808slide",
    name: "Trap 808 Bass",
    instrument: "bass",
    genre: "trap",
    tags: ["sub", "heavy", "deep"],
    params: { sub: 0.9, body: 0.6, punch: 0.55, grit: 0.3, movement: 0.05, width: 0.1, cutoff: 500, resonance: 1.2, level: -4 },
  },
  {
    id: "factory.bass.ambient.drone",
    name: "Ambient Drone Bass",
    instrument: "bass",
    genre: "ambient",
    tags: ["drone", "soft", "wide"],
    params: { sub: 0.75, body: 0.8, punch: 0.1, grit: 0.05, movement: 0.4, width: 0.6, cutoff: 350, resonance: 0.8, level: -8 },
  },
  {
    id: "factory.bass.score.low",
    name: "Score Low Bed",
    instrument: "bass",
    genre: "score",
    tags: ["cinematic", "deep", "static"],
    params: { sub: 0.85, body: 0.75, punch: 0.15, grit: 0.12, movement: 0.2, width: 0.45, cutoff: 400, resonance: 1.0, level: -7 },
  },

  /* ---------------- Analog Synth ---------------- */
  {
    id: "factory.analog.house.stab",
    name: "House Stab",
    instrument: "analog",
    genre: "house",
    tags: ["stab", "bright", "chord"],
    params: { oscA: 2, oscB: 2, oscBDetune: 10, subLevel: 0.2, noiseLevel: 0.03, cutoff: 7000, resonance: 1.2, filterEnv: 0.45, attack: 0.004, decay: 0.22, sustain: 0.35, release: 0.18, level: -7 },
  },
  {
    id: "factory.analog.house.plucklead",
    name: "House Pluck Lead",
    instrument: "analog",
    genre: "house",
    tags: ["pluck", "lead", "clean"],
    params: { oscA: 2, oscB: 0, oscBDetune: 6, subLevel: 0.15, noiseLevel: 0.02, cutoff: 8500, resonance: 1.6, filterEnv: 0.55, attack: 0.002, decay: 0.18, sustain: 0.2, release: 0.15, level: -8 },
  },
  {
    id: "factory.analog.techno.stab",
    name: "Techno Stab",
    instrument: "analog",
    genre: "techno",
    tags: ["dark", "stab", "punchy"],
    params: { oscA: 2, oscB: 3, oscBDetune: 14, subLevel: 0.3, noiseLevel: 0.05, cutoff: 4200, resonance: 2.2, filterEnv: 0.5, attack: 0.003, decay: 0.2, sustain: 0.3, release: 0.12, level: -7 },
  },
  {
    id: "factory.analog.techno.lead",
    name: "Techno Acid Lead",
    instrument: "analog",
    genre: "techno",
    tags: ["acid", "resonant", "aggressive"],
    params: { oscA: 2, oscB: 2, oscBDetune: 8, subLevel: 0.1, noiseLevel: 0.02, cutoff: 3200, resonance: 7.5, filterEnv: 0.65, attack: 0.002, decay: 0.16, sustain: 0.4, release: 0.1, level: -8 },
  },
  {
    id: "factory.analog.trap.lead",
    name: "Trap Lead",
    instrument: "analog",
    genre: "trap",
    tags: ["bright", "lead", "clean"],
    params: { oscA: 2, oscB: 3, oscBDetune: 10, subLevel: 0.1, noiseLevel: 0.02, cutoff: 5200, resonance: 2.0, filterEnv: 0.4, attack: 0.005, decay: 0.3, sustain: 0.4, release: 0.3, level: -12 },
  },
  {
    id: "factory.analog.trap.darkkeys",
    name: "Trap Dark Keys",
    instrument: "analog",
    genre: "trap",
    tags: ["dark", "keys", "soft"],
    params: { oscA: 1, oscB: 0, oscBDetune: 5, subLevel: 0.2, noiseLevel: 0.03, cutoff: 2800, resonance: 1.0, filterEnv: 0.3, attack: 0.01, decay: 0.5, sustain: 0.5, release: 0.5, level: -10 },
  },
  {
    id: "factory.analog.ambient.pad",
    name: "Ambient Pad",
    instrument: "analog",
    genre: "ambient",
    tags: ["pad", "warm", "wide"],
    params: { oscA: 1, oscB: 1, oscBDetune: 12, subLevel: 0.15, noiseLevel: 0.06, cutoff: 2400, resonance: 0.8, filterEnv: 0.15, attack: 0.8, decay: 1.2, sustain: 0.8, release: 1.6, level: -10 },
  },
  {
    id: "factory.analog.score.strings",
    name: "Score Strings",
    instrument: "analog",
    genre: "score",
    tags: ["cinematic", "warm", "moving"],
    params: { oscA: 2, oscB: 2, oscBDetune: 16, subLevel: 0.1, noiseLevel: 0.04, cutoff: 3600, resonance: 0.9, filterEnv: 0.2, attack: 0.5, decay: 0.8, sustain: 0.75, release: 1.2, level: -10 },
  },

  /* ---------------- 808 Synth ---------------- */
  {
    id: "factory.808.trap.deep",
    name: "Deep Trap 808",
    instrument: "808",
    genre: "trap",
    tags: ["sub", "long", "heavy"],
    params: { decay: 1.6, pitchDrop: 0.5, click: 0.3, drive: 0.35, tone: 0.3, gain: 0.9 },
  },
  {
    id: "factory.808.trap.punch",
    name: "Punch 808",
    instrument: "808",
    genre: "trap",
    tags: ["punchy", "tight"],
    params: { decay: 0.6, pitchDrop: 0.55, click: 0.5, drive: 0.3, tone: 0.4, gain: 0.9 },
  },
  {
    id: "factory.808.house.sub",
    name: "House Sub 808",
    instrument: "808",
    genre: "house",
    tags: ["sub", "clean", "round"],
    params: { decay: 0.9, pitchDrop: 0.4, click: 0.35, drive: 0.2, tone: 0.35, gain: 0.85 },
  },
  {
    id: "factory.808.techno.boom",
    name: "Techno Boom",
    instrument: "808",
    genre: "techno",
    tags: ["dark", "boomy"],
    params: { decay: 1.2, pitchDrop: 0.6, click: 0.25, drive: 0.45, tone: 0.25, gain: 0.85 },
  },
  {
    id: "factory.808.score.impact",
    name: "Score Impact",
    instrument: "808",
    genre: "score",
    tags: ["cinematic", "impact", "deep"],
    params: { decay: 2.4, pitchDrop: 0.75, click: 0.4, drive: 0.3, tone: 0.2, gain: 0.9 },
  },

  /* ---------------- Sampler ---------------- */
  {
    id: "factory.sampler.house.pluck",
    name: "House Pluck",
    instrument: "sampler",
    genre: "house",
    tags: ["pluck", "bright"],
    sampleId: "factory.tonal.pluck",
    params: { root: 60, attack: 0.003, release: 0.14, cutoff: 14000, resonance: 0.8, gain: 0.9 },
  },
  {
    id: "factory.sampler.house.stab",
    name: "House Stab",
    instrument: "sampler",
    genre: "house",
    tags: ["stab", "chord"],
    sampleId: "factory.tonal.stab",
    params: { root: 60, attack: 0.002, release: 0.12, cutoff: 13000, resonance: 0.7, gain: 0.85 },
  },
  {
    id: "factory.sampler.ambient.keys",
    name: "Ambient Keys",
    instrument: "sampler",
    genre: "ambient",
    tags: ["keys", "soft", "clean"],
    sampleId: "factory.tonal.keys",
    params: { root: 60, attack: 0.02, release: 0.5, cutoff: 9000, resonance: 0.6, gain: 0.85 },
  },
  {
    id: "factory.sampler.score.bell",
    name: "Score Bell",
    instrument: "sampler",
    genre: "score",
    tags: ["bell", "clear", "lead"],
    sampleId: "factory.tonal.bell",
    params: { root: 72, attack: 0.002, release: 0.6, cutoff: 15000, resonance: 0.7, gain: 0.8 },
  },

  /* ---------------- Texture Synth ---------------- */
  {
    id: "factory.texture.ambient.drift",
    name: "Ambient Drift",
    instrument: "texture",
    genre: "ambient",
    tags: ["atmosphere", "evolving", "wide"],
    params: { color: 0.45, motion: 0.5, space: 0.6, density: 0.6, texture: 0.35, chaos: 0.15, level: -8 },
  },
  {
    id: "factory.texture.ambient.darkdrone",
    name: "Dark Drone",
    instrument: "texture",
    genre: "ambient",
    tags: ["drone", "dark", "static"],
    params: { color: 0.2, motion: 0.25, space: 0.5, density: 0.8, texture: 0.5, chaos: 0.1, level: -9 },
  },
  {
    id: "factory.texture.score.bed",
    name: "Score Bed",
    instrument: "texture",
    genre: "score",
    tags: ["cinematic", "bed", "moving"],
    params: { color: 0.5, motion: 0.35, space: 0.5, density: 0.65, texture: 0.4, chaos: 0.12, level: -10 },
  },
  {
    id: "factory.texture.techno.industrial",
    name: "Industrial Texture",
    instrument: "texture",
    genre: "techno",
    tags: ["dark", "gritty", "moving"],
    params: { color: 0.35, motion: 0.6, space: 0.35, density: 0.5, texture: 0.65, chaos: 0.4, level: -11 },
  },
];
