import type { DrumSynthPreset, InstrumentPreset } from "./types";

/**
 * Factory presets are pure data, curated by genre and mood. Parameter values
 * stay inside each instrument's defined ranges so they clamp cleanly.
 */
export const FACTORY_PRESETS: InstrumentPreset[] = [
  /* ================= Bass Synth ================= */
  {
    id: "factory.bass.house.pluck",
    name: "House Pluck",
    instrument: "bass",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["plucky", "punchy", "clean"],
    params: {
      sub: 0.4,
      body: 0.55,
      punch: 0.75,
      grit: 0.15,
      movement: 0.1,
      width: 0.2,
      cutoff: 900,
      resonance: 1.4,
      level: -6,
    },
  },
  {
    id: "factory.bass.house.deep",
    name: "Deep House Bass",
    instrument: "bass",
    genre: "house",
    mood: ["deep", "warm"],
    tags: ["deep", "warm", "round"],
    params: {
      sub: 0.7,
      body: 0.7,
      punch: 0.4,
      grit: 0.1,
      movement: 0.08,
      width: 0.25,
      cutoff: 600,
      resonance: 1.0,
      level: -5,
    },
  },
  {
    id: "factory.bass.house.warmsub",
    name: "Warm Sub",
    instrument: "bass",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["sub", "warm", "round"],
    params: {
      sub: 0.75,
      body: 0.6,
      punch: 0.35,
      grit: 0.08,
      movement: 0.05,
      width: 0.15,
      cutoff: 520,
      resonance: 0.8,
      level: -5,
    },
  },
  {
    id: "factory.bass.house.pluckbass",
    name: "Pluck Bass",
    instrument: "bass",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["pluck", "bright", "punchy"],
    params: {
      sub: 0.3,
      body: 0.4,
      punch: 0.85,
      grit: 0.12,
      movement: 0.08,
      width: 0.2,
      cutoff: 1100,
      resonance: 1.6,
      level: -7,
    },
  },
  {
    id: "factory.bass.house.techhouse",
    name: "Tech House Bass",
    instrument: "bass",
    genre: "house",
    mood: ["aggressive", "dark"],
    tags: ["tech", "punchy", "gritty"],
    params: {
      sub: 0.6,
      body: 0.5,
      punch: 0.65,
      grit: 0.32,
      movement: 0.15,
      width: 0.18,
      cutoff: 700,
      resonance: 1.8,
      level: -6,
    },
  },
  {
    id: "factory.bass.techno.rumble",
    name: "Techno Rumble",
    instrument: "bass",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["dark", "driving", "gritty"],
    params: {
      sub: 0.8,
      body: 0.45,
      punch: 0.3,
      grit: 0.55,
      movement: 0.25,
      width: 0.1,
      cutoff: 420,
      resonance: 2.5,
      level: -6,
    },
  },
  {
    id: "factory.bass.techno.acid",
    name: "Acid Line",
    instrument: "bass",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["acid", "resonant", "moving"],
    params: {
      sub: 0.3,
      body: 0.5,
      punch: 0.6,
      grit: 0.4,
      movement: 0.6,
      width: 0.15,
      cutoff: 800,
      resonance: 6.5,
      level: -7,
    },
  },
  {
    id: "factory.bass.techno.reese",
    name: "Reese",
    instrument: "bass",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["reese", "wide", "moving"],
    params: {
      sub: 0.65,
      body: 0.72,
      punch: 0.4,
      grit: 0.5,
      movement: 0.4,
      width: 0.7,
      cutoff: 650,
      resonance: 1.6,
      level: -7,
    },
  },
  {
    id: "factory.bass.techno.darkpulse",
    name: "Dark Pulse",
    instrument: "bass",
    genre: "techno",
    mood: ["dark", "deep"],
    tags: ["dark", "pulse", "static"],
    params: {
      sub: 0.85,
      body: 0.5,
      punch: 0.5,
      grit: 0.38,
      movement: 0.2,
      width: 0.12,
      cutoff: 380,
      resonance: 2.6,
      level: -6,
    },
  },
  {
    id: "factory.bass.trap.808slide",
    name: "Trap 808 Bass",
    instrument: "bass",
    genre: "trap",
    mood: ["deep", "aggressive"],
    tags: ["sub", "heavy", "deep"],
    params: {
      sub: 0.9,
      body: 0.6,
      punch: 0.55,
      grit: 0.3,
      movement: 0.05,
      width: 0.1,
      cutoff: 500,
      resonance: 1.2,
      level: -4,
    },
  },
  {
    id: "factory.bass.trap.fmgrowl",
    name: "FM Growl",
    instrument: "bass",
    genre: "trap",
    mood: ["dark", "aggressive"],
    tags: ["fm", "growl", "aggressive"],
    params: {
      sub: 0.55,
      body: 0.6,
      punch: 0.45,
      grit: 0.7,
      movement: 0.55,
      width: 0.3,
      cutoff: 620,
      resonance: 3.4,
      level: -6,
    },
  },
  {
    id: "factory.bass.trap.walnut",
    name: "808 Walnut",
    instrument: "bass",
    genre: "trap",
    mood: ["clean", "warm"],
    tags: ["808", "clean", "round"],
    params: {
      sub: 0.85,
      body: 0.55,
      punch: 0.5,
      grit: 0.18,
      movement: 0.05,
      width: 0.12,
      cutoff: 460,
      resonance: 1.0,
      level: -4,
    },
  },
  {
    id: "factory.bass.ambient.drone",
    name: "Ambient Drone Bass",
    instrument: "bass",
    genre: "ambient",
    mood: ["atmosphere", "deep"],
    tags: ["drone", "soft", "wide"],
    params: {
      sub: 0.75,
      body: 0.8,
      punch: 0.1,
      grit: 0.05,
      movement: 0.4,
      width: 0.6,
      cutoff: 350,
      resonance: 0.8,
      level: -8,
    },
  },
  {
    id: "factory.bass.ambient.subdrone",
    name: "Sub Drone",
    instrument: "bass",
    genre: "ambient",
    mood: ["deep", "atmosphere"],
    tags: ["sub", "drone", "deep"],
    params: {
      sub: 0.9,
      body: 0.75,
      punch: 0.08,
      grit: 0.04,
      movement: 0.3,
      width: 0.5,
      cutoff: 300,
      resonance: 0.7,
      level: -8,
    },
  },
  {
    id: "factory.bass.score.low",
    name: "Score Low Bed",
    instrument: "bass",
    genre: "score",
    mood: ["deep", "atmosphere"],
    tags: ["cinematic", "deep", "static"],
    params: {
      sub: 0.85,
      body: 0.75,
      punch: 0.15,
      grit: 0.12,
      movement: 0.2,
      width: 0.45,
      cutoff: 400,
      resonance: 1.0,
      level: -7,
    },
  },
  {
    id: "factory.bass.score.cinemalow",
    name: "Cinema Low",
    instrument: "bass",
    genre: "score",
    mood: ["atmosphere", "dark"],
    tags: ["cinematic", "dark", "low"],
    params: {
      sub: 0.8,
      body: 0.7,
      punch: 0.2,
      grit: 0.2,
      movement: 0.25,
      width: 0.5,
      cutoff: 360,
      resonance: 1.2,
      level: -7,
    },
  },

  /* ================= Analog Synth ================= */
  {
    id: "factory.analog.house.stab",
    name: "House Stab",
    instrument: "analog",
    genre: "house",
    mood: ["bright", "aggressive"],
    tags: ["stab", "bright", "chord"],
    params: {
      oscA: 2,
      oscB: 2,
      oscBDetune: 10,
      subLevel: 0.2,
      noiseLevel: 0.03,
      cutoff: 7000,
      resonance: 1.2,
      filterEnv: 0.45,
      attack: 0.004,
      decay: 0.22,
      sustain: 0.35,
      release: 0.18,
      level: -7,
    },
  },
  {
    id: "factory.analog.house.plucklead",
    name: "House Pluck Lead",
    instrument: "analog",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["pluck", "lead", "clean"],
    params: {
      oscA: 2,
      oscB: 0,
      oscBDetune: 6,
      subLevel: 0.15,
      noiseLevel: 0.02,
      cutoff: 8500,
      resonance: 1.6,
      filterEnv: 0.55,
      attack: 0.002,
      decay: 0.18,
      sustain: 0.2,
      release: 0.15,
      level: -8,
    },
  },
  {
    id: "factory.analog.house.chords",
    name: "House Chords",
    instrument: "analog",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["chord", "warm", "keys"],
    params: {
      oscA: 1,
      oscB: 1,
      oscBDetune: 8,
      subLevel: 0.2,
      noiseLevel: 0.03,
      cutoff: 5200,
      resonance: 0.9,
      filterEnv: 0.28,
      attack: 0.008,
      decay: 0.4,
      sustain: 0.6,
      release: 0.25,
      level: -9,
    },
  },
  {
    id: "factory.analog.house.arp",
    name: "Sparkle Arp",
    instrument: "analog",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["arp", "bright", "short"],
    params: {
      oscA: 2,
      oscB: 0,
      oscBDetune: 4,
      subLevel: 0.1,
      noiseLevel: 0.02,
      cutoff: 9000,
      resonance: 1.4,
      filterEnv: 0.6,
      attack: 0.001,
      decay: 0.1,
      sustain: 0.1,
      release: 0.08,
      level: -9,
    },
  },
  {
    id: "factory.analog.techno.stab",
    name: "Techno Stab",
    instrument: "analog",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["dark", "stab", "punchy"],
    params: {
      oscA: 2,
      oscB: 3,
      oscBDetune: 14,
      subLevel: 0.3,
      noiseLevel: 0.05,
      cutoff: 4200,
      resonance: 2.2,
      filterEnv: 0.5,
      attack: 0.003,
      decay: 0.2,
      sustain: 0.3,
      release: 0.12,
      level: -7,
    },
  },
  {
    id: "factory.analog.techno.lead",
    name: "Techno Acid Lead",
    instrument: "analog",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["acid", "resonant", "aggressive"],
    params: {
      oscA: 2,
      oscB: 2,
      oscBDetune: 8,
      subLevel: 0.1,
      noiseLevel: 0.02,
      cutoff: 3200,
      resonance: 7.5,
      filterEnv: 0.65,
      attack: 0.002,
      decay: 0.16,
      sustain: 0.4,
      release: 0.1,
      level: -8,
    },
  },
  {
    id: "factory.analog.techno.darkpluck",
    name: "Dark Pluck",
    instrument: "analog",
    genre: "techno",
    mood: ["dark", "clean"],
    tags: ["dark", "pluck", "short"],
    params: {
      oscA: 2,
      oscB: 2,
      oscBDetune: 10,
      subLevel: 0.2,
      noiseLevel: 0.03,
      cutoff: 3400,
      resonance: 2.5,
      filterEnv: 0.5,
      attack: 0.002,
      decay: 0.15,
      sustain: 0.15,
      release: 0.1,
      level: -8,
    },
  },
  {
    id: "factory.analog.techno.digikeys",
    name: "Digi Keys",
    instrument: "analog",
    genre: "techno",
    mood: ["clean", "bright"],
    tags: ["keys", "clean", "digital"],
    params: {
      oscA: 0,
      oscB: 1,
      oscBDetune: 3,
      subLevel: 0.1,
      noiseLevel: 0.02,
      cutoff: 7500,
      resonance: 1.0,
      filterEnv: 0.25,
      attack: 0.005,
      decay: 0.35,
      sustain: 0.5,
      release: 0.3,
      level: -9,
    },
  },
  {
    id: "factory.analog.trap.lead",
    name: "Trap Lead",
    instrument: "analog",
    genre: "trap",
    mood: ["bright", "clean"],
    tags: ["bright", "lead", "clean"],
    params: {
      oscA: 2,
      oscB: 3,
      oscBDetune: 10,
      subLevel: 0.1,
      noiseLevel: 0.02,
      cutoff: 5200,
      resonance: 2.0,
      filterEnv: 0.4,
      attack: 0.005,
      decay: 0.3,
      sustain: 0.4,
      release: 0.3,
      level: -12,
    },
  },
  {
    id: "factory.analog.trap.darkkeys",
    name: "Trap Dark Keys",
    instrument: "analog",
    genre: "trap",
    mood: ["dark", "warm"],
    tags: ["dark", "keys", "soft"],
    params: {
      oscA: 1,
      oscB: 0,
      oscBDetune: 5,
      subLevel: 0.2,
      noiseLevel: 0.03,
      cutoff: 2800,
      resonance: 1.0,
      filterEnv: 0.3,
      attack: 0.01,
      decay: 0.5,
      sustain: 0.5,
      release: 0.5,
      level: -10,
    },
  },
  {
    id: "factory.analog.trap.supersaw",
    name: "Supersaw Lead",
    instrument: "analog",
    genre: "trap",
    mood: ["bright", "aggressive"],
    tags: ["supersaw", "lead", "wide"],
    params: {
      oscA: 2,
      oscB: 2,
      oscBDetune: 22,
      subLevel: 0.15,
      noiseLevel: 0.03,
      cutoff: 6000,
      resonance: 1.5,
      filterEnv: 0.35,
      unison: 7,
      spread: 18,
      attack: 0.004,
      decay: 0.4,
      sustain: 0.5,
      release: 0.35,
      level: -11,
    },
  },
  {
    id: "factory.analog.house.widepad",
    name: "Wide Pad",
    instrument: "analog",
    genre: "house",
    mood: ["warm", "atmosphere"],
    tags: ["pad", "wide", "unison"],
    params: {
      oscA: 2,
      oscB: 1,
      oscBDetune: 10,
      subLevel: 0.12,
      noiseLevel: 0.05,
      cutoff: 3400,
      resonance: 0.9,
      filterEnv: 0.12,
      unison: 5,
      spread: 12,
      attack: 0.6,
      decay: 1.0,
      sustain: 0.8,
      release: 1.4,
      level: -10,
    },
  },
  {
    id: "factory.analog.acid.wobble",
    name: "Wobble Acid",
    instrument: "analog",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["acid", "wobble", "lfo"],
    params: {
      oscA: 2,
      oscB: 2,
      oscBDetune: 8,
      subLevel: 0.15,
      noiseLevel: 0.02,
      cutoff: 1200,
      resonance: 5.5,
      filterEnv: 0.4,
      unison: 1,
      spread: 0,
      lfoRate: 4.2,
      lfoDepth: 0.45,
      attack: 0.002,
      decay: 0.16,
      sustain: 0.4,
      release: 0.1,
      level: -8,
    },
  },
  {
    id: "factory.analog.ambient.pad",
    name: "Ambient Pad",
    instrument: "analog",
    genre: "ambient",
    mood: ["warm", "atmosphere"],
    tags: ["pad", "warm", "wide"],
    params: {
      oscA: 1,
      oscB: 1,
      oscBDetune: 12,
      subLevel: 0.15,
      noiseLevel: 0.06,
      cutoff: 2400,
      resonance: 0.8,
      filterEnv: 0.15,
      attack: 0.8,
      decay: 1.2,
      sustain: 0.8,
      release: 1.6,
      level: -10,
    },
  },
  {
    id: "factory.analog.ambient.vapor",
    name: "Vapor Keys",
    instrument: "analog",
    genre: "ambient",
    mood: ["atmosphere", "bright"],
    tags: ["keys", "vapor", "airy"],
    params: {
      oscA: 1,
      oscB: 0,
      oscBDetune: 9,
      subLevel: 0.1,
      noiseLevel: 0.05,
      cutoff: 3000,
      resonance: 0.7,
      filterEnv: 0.2,
      attack: 0.15,
      decay: 0.8,
      sustain: 0.6,
      release: 1.4,
      level: -11,
    },
  },
  {
    id: "factory.analog.ambient.softlead",
    name: "Soft Lead",
    instrument: "analog",
    genre: "ambient",
    mood: ["warm", "clean"],
    tags: ["lead", "soft", "warm"],
    params: {
      oscA: 1,
      oscB: 1,
      oscBDetune: 7,
      subLevel: 0.12,
      noiseLevel: 0.02,
      cutoff: 3800,
      resonance: 0.9,
      filterEnv: 0.25,
      attack: 0.06,
      decay: 0.5,
      sustain: 0.6,
      release: 0.6,
      level: -9,
    },
  },
  {
    id: "factory.analog.score.breathflute",
    name: "Breath Flute",
    instrument: "analog",
    genre: "score",
    mood: ["atmosphere", "clean"],
    tags: ["flute", "breath", "wind", "harmonic"],
    params: {
      oscA: 0,
      oscB: 1,
      oscBDetune: 5,
      subLevel: 0.05,
      noiseLevel: 0.14,
      cutoff: 4200,
      resonance: 1.1,
      filterEnv: 0.18,
      unison: 1,
      spread: 0,
      lfoRate: 4.6,
      lfoDepth: 0.14,
      attack: 0.075,
      decay: 0.4,
      sustain: 0.72,
      release: 0.5,
      level: -8,
    },
  },
  {
    id: "factory.analog.score.panflute",
    name: "Pan Flute Lead",
    instrument: "analog",
    genre: "score",
    mood: ["warm", "atmosphere"],
    tags: ["flute", "pan", "breath", "lead"],
    params: {
      oscA: 0,
      oscB: 1,
      oscBDetune: 5,
      subLevel: 0.0,
      noiseLevel: 0.1,
      cutoff: 4800,
      resonance: 1.5,
      filterEnv: 0.3,
      unison: 1,
      spread: 0,
      lfoRate: 5.2,
      lfoDepth: 0.1,
      attack: 0.02,
      decay: 0.35,
      sustain: 0.55,
      release: 0.4,
      level: -8,
    },
  },
  {
    id: "factory.analog.score.strings",
    name: "Score Strings",
    instrument: "analog",
    genre: "score",
    mood: ["warm", "atmosphere"],
    tags: ["cinematic", "warm", "moving"],
    params: {
      oscA: 2,
      oscB: 2,
      oscBDetune: 16,
      subLevel: 0.1,
      noiseLevel: 0.04,
      cutoff: 3600,
      resonance: 0.9,
      filterEnv: 0.2,
      attack: 0.5,
      decay: 0.8,
      sustain: 0.75,
      release: 1.2,
      level: -10,
    },
  },
  {
    id: "factory.analog.score.brass",
    name: "Brass Hit",
    instrument: "analog",
    genre: "score",
    mood: ["aggressive", "bright"],
    tags: ["brass", "cinematic", "hit"],
    params: {
      oscA: 2,
      oscB: 2,
      oscBDetune: 12,
      subLevel: 0.25,
      noiseLevel: 0.04,
      cutoff: 5200,
      resonance: 1.6,
      filterEnv: 0.55,
      attack: 0.01,
      decay: 0.3,
      sustain: 0.55,
      release: 0.3,
      level: -9,
    },
  },
  {
    id: "factory.analog.score.swell",
    name: "Atmos Swell",
    instrument: "analog",
    genre: "score",
    mood: ["atmosphere", "dark"],
    tags: ["swell", "cinematic", "atmosphere"],
    params: {
      oscA: 1,
      oscB: 2,
      oscBDetune: 18,
      subLevel: 0.2,
      noiseLevel: 0.08,
      cutoff: 2000,
      resonance: 1.4,
      filterEnv: 0.2,
      attack: 1.2,
      decay: 1.0,
      sustain: 0.8,
      release: 2.0,
      level: -10,
    },
  },

  /* ================= 808 Synth ================= */
  {
    id: "factory.808.trap.deep",
    name: "Deep Trap 808",
    instrument: "808",
    genre: "trap",
    mood: ["deep", "dark"],
    tags: ["sub", "long", "heavy"],
    params: { decay: 1.6, pitchDrop: 0.5, click: 0.3, drive: 0.35, tone: 0.3, gain: 0.9 },
  },
  {
    id: "factory.808.trap.punch",
    name: "Punch 808",
    instrument: "808",
    genre: "trap",
    mood: ["aggressive", "clean"],
    tags: ["punchy", "tight"],
    params: { decay: 0.6, pitchDrop: 0.55, click: 0.5, drive: 0.3, tone: 0.4, gain: 0.9 },
  },
  {
    id: "factory.808.trap.boomer",
    name: "Long Boomer",
    instrument: "808",
    genre: "trap",
    mood: ["deep", "warm"],
    tags: ["long", "boomy", "sub"],
    params: { decay: 3.0, pitchDrop: 0.45, click: 0.2, drive: 0.25, tone: 0.25, gain: 0.88 },
  },
  {
    id: "factory.808.trap.distorted",
    name: "Distorted 808",
    instrument: "808",
    genre: "trap",
    mood: ["aggressive", "dark"],
    tags: ["distorted", "aggressive"],
    params: { decay: 1.2, pitchDrop: 0.55, click: 0.45, drive: 0.8, tone: 0.5, gain: 0.82 },
  },
  {
    id: "factory.808.house.sub",
    name: "House Sub 808",
    instrument: "808",
    genre: "house",
    mood: ["clean", "warm"],
    tags: ["sub", "clean", "round"],
    params: { decay: 0.9, pitchDrop: 0.4, click: 0.35, drive: 0.2, tone: 0.35, gain: 0.85 },
  },
  {
    id: "factory.808.house.short",
    name: "Short 808",
    instrument: "808",
    genre: "house",
    mood: ["bright", "aggressive"],
    tags: ["short", "tight"],
    params: { decay: 0.35, pitchDrop: 0.5, click: 0.55, drive: 0.25, tone: 0.45, gain: 0.9 },
  },
  {
    id: "factory.808.house.punchy",
    name: "Punchy 808",
    instrument: "808",
    genre: "house",
    mood: ["aggressive", "bright"],
    tags: ["punchy", "tight"],
    params: { decay: 0.5, pitchDrop: 0.5, click: 0.6, drive: 0.35, tone: 0.45, gain: 0.9 },
  },
  {
    id: "factory.808.techno.boom",
    name: "Techno Boom",
    instrument: "808",
    genre: "techno",
    mood: ["dark", "deep"],
    tags: ["dark", "boomy"],
    params: { decay: 1.2, pitchDrop: 0.6, click: 0.25, drive: 0.45, tone: 0.25, gain: 0.85 },
  },
  {
    id: "factory.808.ambient.warm",
    name: "Warm 808",
    instrument: "808",
    genre: "ambient",
    mood: ["warm", "deep"],
    tags: ["warm", "soft", "round"],
    params: { decay: 2.0, pitchDrop: 0.3, click: 0.15, drive: 0.15, tone: 0.3, gain: 0.8 },
  },
  {
    id: "factory.808.score.impact",
    name: "Score Impact 808",
    instrument: "808",
    genre: "score",
    mood: ["deep", "aggressive"],
    tags: ["impact", "sub", "cinematic"],
    params: { decay: 0.7, pitchDrop: 0.3, click: 0.35, drive: 0.45, tone: 0.55, gain: 0.88 },
  },
  {
    id: "factory.808.trap.slide",
    name: "Slide 808",
    instrument: "808",
    genre: "trap",
    mood: ["deep", "dark"],
    tags: ["slide", "glide", "trap", "tube"],
    params: { decay: 1.4, pitchDrop: 0.3, click: 0.25, drive: 0.4, glide: 0.51, distType: 1, sub: 0.55, tone: 0.3, gain: 0.9 },
  },
  {
    id: "factory.808.trap.hardclip",
    name: "Hard Clip 808",
    instrument: "808",
    genre: "trap",
    mood: ["aggressive", "dark"],
    tags: ["hard", "distorted", "clip", "aggressive"],
    params: { decay: 0.8, pitchDrop: 0.45, click: 0.4, drive: 0.75, glide: 0.23, distType: 2, sub: 0.2, tone: 0.45, gain: 0.84 },
  },
  {
    id: "factory.808.house.subpure",
    name: "Pure Sub 808",
    instrument: "808",
    genre: "house",
    mood: ["deep", "warm"],
    tags: ["sub", "pure", "clean", "octave"],
    params: { decay: 1.1, pitchDrop: 0.35, click: 0.15, drive: 0.15, glide: 0.34, distType: 0, sub: 0.85, tone: 0.22, gain: 0.88 },
  },

  /* ================= Sampler ================= */
  {
    id: "factory.sampler.house.pluck",
    name: "House Pluck",
    instrument: "sampler",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["pluck", "bright"],
    sampleId: "factory.tonal.pluck",
    params: { root: 60, attack: 0.003, release: 0.14, cutoff: 14000, resonance: 0.8, gain: 0.9 },
  },
  {
    id: "factory.sampler.house.stab",
    name: "House Stab",
    instrument: "sampler",
    genre: "house",
    mood: ["aggressive", "bright"],
    tags: ["stab", "chord"],
    sampleId: "factory.tonal.stab",
    params: { root: 60, attack: 0.002, release: 0.12, cutoff: 13000, resonance: 0.7, gain: 0.85 },
  },
  {
    id: "factory.sampler.house.mellow",
    name: "Mellow Pluck",
    instrument: "sampler",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["pluck", "warm"],
    sampleId: "factory.tonal.pluck",
    params: { root: 60, attack: 0.03, release: 0.35, cutoff: 7000, resonance: 0.6, gain: 0.8 },
  },
  {
    id: "factory.sampler.techno.stab",
    name: "Analog Stab",
    instrument: "sampler",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["stab", "dark"],
    sampleId: "factory.tonal.stab",
    params: { root: 60, attack: 0.001, release: 0.1, cutoff: 8000, resonance: 1.4, gain: 0.9 },
  },
  {
    id: "factory.sampler.ambient.keys",
    name: "Ambient Keys",
    instrument: "sampler",
    genre: "ambient",
    mood: ["warm", "atmosphere"],
    tags: ["keys", "soft", "clean"],
    sampleId: "factory.tonal.keys",
    params: { root: 60, attack: 0.02, release: 0.5, cutoff: 9000, resonance: 0.6, gain: 0.85 },
  },
  {
    id: "factory.sampler.ambient.piano",
    name: "Piano Keys",
    instrument: "sampler",
    genre: "ambient",
    mood: ["warm", "clean"],
    tags: ["piano", "keys", "clean"],
    sampleId: "factory.tonal.keys",
    params: { root: 60, attack: 0.004, release: 0.9, cutoff: 12000, resonance: 0.5, gain: 0.85 },
  },
  {
    id: "factory.sampler.score.bell",
    name: "Score Bell",
    instrument: "sampler",
    genre: "score",
    mood: ["bright", "atmosphere"],
    tags: ["bell", "clear", "lead"],
    sampleId: "factory.tonal.bell",
    params: { root: 72, attack: 0.002, release: 0.6, cutoff: 15000, resonance: 0.7, gain: 0.8 },
  },
  {
    id: "factory.sampler.score.bellpad",
    name: "Bell Pad",
    instrument: "sampler",
    genre: "score",
    mood: ["atmosphere", "warm"],
    tags: ["bell", "pad", "long"],
    sampleId: "factory.tonal.bell",
    params: { root: 60, attack: 0.1, release: 1.4, cutoff: 6000, resonance: 0.5, gain: 0.7 },
  },

  /* ================= Texture Synth ================= */
  {
    id: "factory.texture.ambient.drift",
    name: "Ambient Drift",
    instrument: "texture",
    genre: "ambient",
    mood: ["atmosphere", "warm"],
    tags: ["atmosphere", "evolving", "wide"],
    params: { color: 0.45, motion: 0.5, space: 0.6, density: 0.6, texture: 0.35, chaos: 0.15, level: -8 },
  },
  {
    id: "factory.texture.ambient.darkdrone",
    name: "Dark Drone",
    instrument: "texture",
    genre: "ambient",
    mood: ["dark", "deep"],
    tags: ["drone", "dark", "static"],
    params: { color: 0.2, motion: 0.25, space: 0.5, density: 0.8, texture: 0.5, chaos: 0.1, level: -9 },
  },
  {
    id: "factory.texture.ambient.shimmer",
    name: "Shimmer",
    instrument: "texture",
    genre: "ambient",
    mood: ["bright", "atmosphere"],
    tags: ["shimmer", "bright", "airy"],
    params: { color: 0.7, motion: 0.45, space: 0.65, density: 0.4, texture: 0.25, chaos: 0.2, level: -10 },
  },
  {
    id: "factory.texture.ambient.lushpad",
    name: "Lush Pad",
    instrument: "texture",
    genre: "ambient",
    mood: ["warm", "clean"],
    tags: ["pad", "lush", "warm"],
    params: { color: 0.55, motion: 0.35, space: 0.55, density: 0.7, texture: 0.3, chaos: 0.1, level: -9 },
  },
  {
    id: "factory.texture.ambient.deepsapce",
    name: "Deep Space",
    instrument: "texture",
    genre: "ambient",
    mood: ["deep", "dark"],
    tags: ["space", "deep", "dark"],
    params: { color: 0.15, motion: 0.3, space: 0.75, density: 0.85, texture: 0.45, chaos: 0.15, level: -9 },
  },
  {
    id: "factory.texture.ambient.wind",
    name: "Wind",
    instrument: "texture",
    genre: "ambient",
    mood: ["atmosphere", "clean"],
    tags: ["wind", "airy", "moving"],
    params: { color: 0.5, motion: 0.7, space: 0.4, density: 0.2, texture: 0.55, chaos: 0.6, level: -11 },
  },
  {
    id: "factory.texture.ambient.rain",
    name: "Rain",
    instrument: "texture",
    genre: "ambient",
    mood: ["dark", "atmosphere"],
    tags: ["rain", "warm", "textural"],
    params: { color: 0.35, motion: 0.55, space: 0.45, density: 0.3, texture: 0.7, chaos: 0.5, level: -11 },
  },
  {
    id: "factory.texture.score.bed",
    name: "Score Bed",
    instrument: "texture",
    genre: "score",
    mood: ["atmosphere", "warm"],
    tags: ["cinematic", "bed", "moving"],
    params: { color: 0.5, motion: 0.35, space: 0.5, density: 0.65, texture: 0.4, chaos: 0.12, level: -10 },
  },
  {
    id: "factory.texture.score.dronebed",
    name: "Drone Bed",
    instrument: "texture",
    genre: "score",
    mood: ["deep", "atmosphere"],
    tags: ["drone", "cinematic", "deep"],
    params: { color: 0.25, motion: 0.25, space: 0.6, density: 0.85, texture: 0.5, chaos: 0.08, level: -10 },
  },
  {
    id: "factory.texture.techno.industrial",
    name: "Industrial Texture",
    instrument: "texture",
    genre: "techno",
    mood: ["aggressive", "dark"],
    tags: ["dark", "gritty", "moving"],
    params: { color: 0.35, motion: 0.6, space: 0.35, density: 0.5, texture: 0.65, chaos: 0.4, level: -11 },
  },
  {
    id: "factory.texture.techno.glitch",
    name: "Glitch",
    instrument: "texture",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["glitch", "bright", "chaotic"],
    params: { color: 0.6, motion: 0.75, space: 0.3, density: 0.35, texture: 0.75, chaos: 0.8, level: -12 },
  },
  {
    id: "factory.texture.techno.warmpad",
    name: "Warm Pad",
    instrument: "texture",
    genre: "techno",
    mood: ["warm", "clean"],
    tags: ["pad", "warm", "clean"],
    params: { color: 0.55, motion: 0.3, space: 0.5, density: 0.7, texture: 0.3, chaos: 0.1, level: -9 },
  },

  /* ================= Wavetable Synth ================= */
  {
    id: "factory.wavetable.house.brightlead",
    name: "Bright Lead",
    instrument: "wavetable",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["lead", "bright", "saw"],
    params: {
      table: 0,
      morph: 0.85,
      detune: 10,
      sub: 0.1,
      cutoff: 12000,
      resonance: 1.2,
      attack: 0.004,
      release: 0.2,
      level: -8,
    },
  },
  {
    id: "factory.wavetable.house.organ",
    name: "Table Organ",
    instrument: "wavetable",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["organ", "warm", "formant"],
    params: {
      table: 2,
      morph: 0.4,
      detune: 5,
      sub: 0.2,
      cutoff: 7000,
      resonance: 0.8,
      attack: 0.01,
      release: 0.15,
      level: -9,
    },
  },
  {
    id: "factory.wavetable.techno.hardstab",
    name: "Hard Stab",
    instrument: "wavetable",
    genre: "techno",
    mood: ["aggressive", "dark"],
    tags: ["stab", "digital", "harsh"],
    params: {
      table: 3,
      morph: 0.6,
      detune: 14,
      sub: 0.15,
      cutoff: 5000,
      resonance: 3,
      attack: 0.002,
      release: 0.12,
      level: -9,
    },
  },
  {
    id: "factory.wavetable.techno.fmbass",
    name: "FM Bass",
    instrument: "wavetable",
    genre: "techno",
    mood: ["dark", "aggressive"],
    tags: ["fm", "bass", "growl"],
    params: {
      table: 4,
      morph: 0.5,
      detune: 4,
      sub: 0.35,
      cutoff: 1200,
      resonance: 2.2,
      attack: 0.002,
      release: 0.1,
      level: -7,
    },
  },
  {
    id: "factory.wavetable.trap.darkkeys",
    name: "Dark Keys",
    instrument: "wavetable",
    genre: "trap",
    mood: ["dark", "deep"],
    tags: ["keys", "dark", "pwm"],
    params: {
      table: 1,
      morph: 0.55,
      detune: 8,
      sub: 0.2,
      cutoff: 3200,
      resonance: 1.4,
      attack: 0.006,
      release: 0.35,
      level: -8,
    },
  },
  {
    id: "factory.wavetable.ambient.driftpad",
    name: "Drift Pad",
    instrument: "wavetable",
    genre: "ambient",
    mood: ["atmosphere", "warm"],
    tags: ["pad", "drifting", "slow"],
    params: {
      table: 2,
      morph: 0.3,
      detune: 18,
      sub: 0.25,
      cutoff: 4500,
      resonance: 0.7,
      attack: 1.2,
      release: 2.5,
      level: -12,
    },
  },
  {
    id: "factory.wavetable.house.supersaw",
    name: "Table Supersaw",
    instrument: "wavetable",
    genre: "house",
    mood: ["bright", "aggressive"],
    tags: ["supersaw", "unison", "wide"],
    params: {
      table: 0,
      morph: 0.85,
      detune: 10,
      sub: 0.1,
      unison: 6,
      spread: 16,
      cutoff: 12000,
      resonance: 1.2,
      attack: 0.004,
      release: 0.2,
      level: -8,
    },
  },
  {
    id: "factory.wavetable.score.evobed",
    name: "Evo Wide Bed",
    instrument: "wavetable",
    genre: "score",
    mood: ["atmosphere", "warm"],
    tags: ["pad", "unison", "cinematic"],
    params: {
      table: 2,
      morph: 0.45,
      detune: 12,
      sub: 0.3,
      unison: 5,
      spread: 22,
      cutoff: 5200,
      resonance: 0.7,
      attack: 1.2,
      release: 2.6,
      level: -11,
    },
  },
  {
    id: "factory.wavetable.score.evolving",
    name: "Evolving Tone",
    instrument: "wavetable",
    genre: "score",
    mood: ["atmosphere", "dark"],
    tags: ["cinematic", "evolving", "slow"],
    params: {
      table: 0,
      morph: 0.5,
      detune: 12,
      sub: 0.3,
      cutoff: 6000,
      resonance: 0.6,
      attack: 1.5,
      release: 3,
      level: -11,
    },
  },

  /* ================= Granular Synth ================= */
  {
    id: "factory.granular.ambient.cloudpad",
    name: "Cloud Pad",
    instrument: "granular",
    genre: "ambient",
    mood: ["atmosphere", "warm"],
    tags: ["cloud", "pad", "soft"],
    params: {
      position: 0.3,
      size: 0.25,
      rate: 18,
      jitter: 0.25,
      spread: 0.8,
      pitch: 0,
      reverse: 0,
      tone: 5000,
      shape: 0.8,
      attack: 0.6,
      release: 1.5,
      gain: 0.75,
    },
  },
  {
    id: "factory.granular.ambient.timestretch",
    name: "Time Stretch",
    instrument: "granular",
    genre: "ambient",
    mood: ["deep", "atmosphere"],
    tags: ["stretch", "slow", "pitched"],
    params: {
      position: 0.2,
      size: 0.35,
      rate: 7,
      jitter: 0.03,
      spread: 0.9,
      pitch: -12,
      reverse: 0,
      tone: 4200,
      shape: 0.85,
      attack: 1,
      release: 2,
      gain: 0.8,
    },
  },
  {
    id: "factory.granular.ambient.dust",
    name: "Cathedral Dust",
    instrument: "granular",
    genre: "ambient",
    mood: ["dark", "atmosphere"],
    tags: ["dust", "sparse", "reverse"],
    params: {
      position: 0.6,
      size: 0.3,
      rate: 10,
      jitter: 0.55,
      spread: 0.95,
      pitch: -5,
      reverse: 0.85,
      tone: 3600,
      shape: 0.75,
      attack: 0.8,
      release: 1.8,
      gain: 0.7,
    },
  },
  {
    id: "factory.granular.techno.stutter",
    name: "Stutter",
    instrument: "granular",
    genre: "techno",
    mood: ["aggressive", "bright"],
    tags: ["stutter", "fast", "rhythmic"],
    params: {
      position: 0.45,
      size: 0.03,
      rate: 32,
      jitter: 0.06,
      spread: 0.35,
      pitch: 0,
      reverse: 0.2,
      tone: 9500,
      shape: 0.3,
      attack: 0.004,
      release: 0.08,
      gain: 0.8,
    },
  },
  {
    id: "factory.granular.house.vocalchop",
    name: "Vocal Chop",
    instrument: "granular",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["vocal", "chop", "playful"],
    params: {
      position: 0.5,
      size: 0.12,
      rate: 8,
      jitter: 0.04,
      spread: 0.6,
      pitch: 0,
      reverse: 0,
      tone: 8000,
      shape: 0.45,
      attack: 0.01,
      release: 0.2,
      gain: 0.85,
    },
  },
  {
    id: "factory.granular.trap.reversepad",
    name: "Reverse Pad",
    instrument: "granular",
    genre: "trap",
    mood: ["dark", "deep"],
    tags: ["reverse", "pad", "dark"],
    params: {
      position: 0.35,
      size: 0.28,
      rate: 12,
      jitter: 0.15,
      spread: 0.7,
      pitch: -3,
      reverse: 1,
      tone: 5200,
      shape: 0.7,
      attack: 0.4,
      release: 1.2,
      gain: 0.75,
    },
  },
  {
    id: "factory.granular.score.suspense",
    name: "Suspense Bed",
    instrument: "granular",
    genre: "score",
    mood: ["dark", "atmosphere"],
    tags: ["tension", "cinematic", "sparse"],
    params: {
      position: 0.15,
      size: 0.22,
      rate: 9,
      jitter: 0.4,
      spread: 0.85,
      pitch: -8,
      reverse: 0.5,
      tone: 3800,
      shape: 0.8,
      attack: 1.2,
      release: 2.2,
      gain: 0.7,
    },
  },

  /* ================= Keys (FM/Rhodes) ================= */
  {
    id: "factory.keys.house.rhodesclassic",
    name: "Classic Rhodes",
    instrument: "keys",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["rhodes", "warm", "electric"],
    params: {
      tine: 0.6,
      bell: 0.2,
      body: 0.6,
      damp: 0.4,
      tremolo: 0.12,
      width: 0.35,
      cutoff: 5000,
      resonance: 1.2,
      attack: 0.005,
      release: 0.35,
      level: -8,
    },
  },
  {
    id: "factory.keys.house.wurli",
    name: "Wurli Trem",
    instrument: "keys",
    genre: "house",
    mood: ["warm", "bright"],
    tags: ["wurlitzer", "tremolo", "vintage"],
    params: {
      tine: 0.45,
      bell: 0.1,
      body: 0.5,
      damp: 0.3,
      tremolo: 0.35,
      width: 0.45,
      cutoff: 4200,
      resonance: 1.5,
      attack: 0.003,
      release: 0.3,
      level: -7,
    },
  },
  {
    id: "factory.keys.house.wurli.lfo",
    name: "Wurli LFO",
    instrument: "keys",
    genre: "house",
    mood: ["warm", "bright"],
    tags: ["wurlitzer", "lfo", "moving"],
    params: {
      tine: 0.5,
      bell: 0.12,
      body: 0.55,
      damp: 0.3,
      tremolo: 0.2,
      width: 0.45,
      cutoff: 4200,
      resonance: 1.5,
      lfoRate: 1.8,
      lfoDepth: 0.4,
      attack: 0.003,
      release: 0.3,
      level: -7,
    },
  },
  {
    id: "factory.keys.house.fmbell",
    name: "FM Bell",
    instrument: "keys",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["bell", "fm", "clear"],
    params: {
      tine: 0.8,
      bell: 0.7,
      body: 0.4,
      damp: 0.2,
      tremolo: 0.05,
      width: 0.6,
      cutoff: 9000,
      resonance: 0.9,
      attack: 0.002,
      release: 0.6,
      level: -7,
    },
  },
  {
    id: "factory.keys.techno.dirtykeys",
    name: "Dirty Keys",
    instrument: "keys",
    genre: "techno",
    mood: ["aggressive", "dark"],
    tags: ["dirty", "fm", "gritty"],
    params: {
      tine: 0.7,
      bell: 0.4,
      body: 0.7,
      damp: 0.25,
      tremolo: 0.08,
      width: 0.35,
      cutoff: 6500,
      resonance: 2.2,
      attack: 0.004,
      release: 0.3,
      level: -7,
    },
  },
  {
    id: "factory.keys.ambient.softpad",
    name: "Soft Pad Keys",
    instrument: "keys",
    genre: "ambient",
    mood: ["warm", "atmosphere"],
    tags: ["pad", "soft", "keys"],
    params: {
      tine: 0.4,
      bell: 0.25,
      body: 0.65,
      damp: 0.5,
      tremolo: 0.18,
      width: 0.6,
      cutoff: 3200,
      resonance: 1.6,
      attack: 0.35,
      release: 0.9,
      level: -9,
    },
  },

  /* ================= Pluck Synth (Karplus-Strong) ================= */
  {
    id: "factory.pluck.house.nylon",
    name: "Nylon Pluck",
    instrument: "pluck",
    genre: "house",
    mood: ["warm", "clean"],
    tags: ["nylon", "pluck", "warm"],
    params: {
      pick: 0.45,
      damp: 0.35,
      body: 0.6,
      tone: 4200,
      decay: 0.9,
      width: 0.25,
      cutoff: 9000,
      resonance: 1.1,
      attack: 0.002,
      release: 0.3,
      level: -8,
    },
  },
  {
    id: "factory.pluck.house.brightpick",
    name: "Bright Pick",
    instrument: "pluck",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["bright", "pick", "harp"],
    params: {
      pick: 0.75,
      damp: 0.25,
      body: 0.5,
      tone: 5800,
      decay: 0.7,
      width: 0.35,
      cutoff: 11000,
      resonance: 1.0,
      attack: 0.001,
      release: 0.25,
      level: -8,
    },
  },
  {
    id: "factory.pluck.techno.muted",
    name: "Muted Pluck",
    instrument: "pluck",
    genre: "techno",
    mood: ["dark", "clean"],
    tags: ["muted", "short", "percussive"],
    params: {
      pick: 0.3,
      damp: 0.65,
      body: 0.4,
      tone: 2800,
      decay: 0.45,
      width: 0.2,
      cutoff: 7000,
      resonance: 1.4,
      attack: 0.003,
      release: 0.2,
      level: -7,
    },
  },
  {
    id: "factory.pluck.ambient.harp",
    name: "Harp",
    instrument: "pluck",
    genre: "ambient",
    mood: ["warm", "atmosphere"],
    tags: ["harp", "airy", "soft"],
    params: {
      pick: 0.5,
      damp: 0.3,
      body: 0.65,
      tone: 4600,
      decay: 1.4,
      width: 0.5,
      cutoff: 8000,
      resonance: 0.9,
      attack: 0.002,
      release: 0.5,
      level: -9,
    },
  },
  {
    id: "factory.pluck.score.kora",
    name: "Kora",
    instrument: "pluck",
    genre: "score",
    mood: ["atmosphere", "warm"],
    tags: ["kora", "exotic", "resonant"],
    params: {
      pick: 0.6,
      damp: 0.2,
      body: 0.7,
      tone: 5200,
      decay: 1.8,
      width: 0.4,
      cutoff: 7500,
      resonance: 1.3,
      attack: 0.002,
      release: 0.6,
      level: -8,
    },
  },
  {
    id: "factory.pluck.house.groove",
    name: "Groove Pluck",
    instrument: "pluck",
    genre: "house",
    mood: ["warm", "bright"],
    tags: ["groove", "melodic", "hook"],
    params: {
      pick: 0.52,
      damp: 0.38,
      body: 0.62,
      tone: 3800,
      decay: 0.85,
      width: 0.32,
      cutoff: 8500,
      resonance: 1.2,
      attack: 0.002,
      release: 0.32,
      level: -7,
    },
  },
  {
    id: "factory.pluck.ambient.flutepluck",
    name: "Flute Pluck",
    instrument: "pluck",
    genre: "ambient",
    mood: ["atmosphere", "clean"],
    tags: ["flute", "breathy", "soft", "groove"],
    params: {
      pick: 0.22,
      damp: 0.55,
      body: 0.72,
      tone: 3200,
      decay: 1.1,
      width: 0.45,
      cutoff: 6200,
      resonance: 1.8,
      attack: 0.012,
      release: 0.55,
      level: -9,
    },
  },
  {
    id: "factory.pluck.house.warmair",
    name: "Warm Air",
    instrument: "pluck",
    genre: "house",
    mood: ["warm", "deep"],
    tags: ["warm", "airy", "groove", "harmonic"],
    params: {
      pick: 0.35,
      damp: 0.42,
      body: 0.58,
      tone: 3600,
      decay: 1.0,
      width: 0.38,
      cutoff: 7800,
      resonance: 1.3,
      attack: 0.004,
      release: 0.42,
      level: -8,
    },
  },
  {
    id: "factory.pluck.score.breathstring",
    name: "Breath String",
    instrument: "pluck",
    genre: "score",
    mood: ["atmosphere", "warm"],
    tags: ["breath", "string", "cinematic", "glide"],
    params: {
      pick: 0.28,
      damp: 0.48,
      body: 0.68,
      tone: 3400,
      decay: 1.6,
      width: 0.5,
      cutoff: 6800,
      resonance: 1.5,
      attack: 0.018,
      release: 0.75,
      level: -9,
    },
  },
  {
    id: "factory.keys.ambient.movementkeys",
    name: "Moving Pad Keys",
    instrument: "keys",
    genre: "ambient",
    mood: ["atmosphere", "bright"],
    tags: ["pad", "lfo", "moving"],
    params: {
      tine: 0.5,
      bell: 0.55,
      body: 0.6,
      damp: 0.5,
      tremolo: 0.2,
      width: 0.6,
      cutoff: 4500,
      resonance: 1.6,
      lfoRate: 2.4,
      lfoDepth: 0.35,
      attack: 0.3,
      release: 1.1,
      level: -9,
    },
  },
  {
    id: "factory.keys.house.flute",
    name: "FM Flute",
    instrument: "keys",
    genre: "house",
    mood: ["clean", "bright"],
    tags: ["flute", "breathy", "harmonic", "groove"],
    params: {
      tine: 0.18,
      bell: 0.68,
      body: 0.35,
      damp: 0.62,
      tremolo: 0.08,
      width: 0.25,
      cutoff: 7200,
      resonance: 1.4,
      attack: 0.028,
      release: 0.42,
      level: -8,
    },
  },
  {
    id: "factory.keys.house.groovekeys",
    name: "Groove Keys",
    instrument: "keys",
    genre: "house",
    mood: ["warm", "bright"],
    tags: ["groove", "hook", "harmonic", "keys"],
    params: {
      tine: 0.48,
      bell: 0.22,
      body: 0.58,
      damp: 0.38,
      tremolo: 0.14,
      width: 0.4,
      cutoff: 4800,
      resonance: 1.3,
      attack: 0.006,
      release: 0.38,
      level: -7,
    },
  },
  {
    id: "factory.keys.ambient.breathy",
    name: "Breathy Pad",
    instrument: "keys",
    genre: "ambient",
    mood: ["atmosphere", "warm"],
    tags: ["breathy", "air", "pad", "flute"],
    params: {
      tine: 0.28,
      bell: 0.52,
      body: 0.62,
      damp: 0.58,
      tremolo: 0.12,
      width: 0.55,
      cutoff: 3800,
      resonance: 1.7,
      lfoRate: 1.2,
      lfoDepth: 0.22,
      attack: 0.42,
      release: 1.0,
      level: -9,
    },
  },
  {
    id: "factory.keys.score.warmgroove",
    name: "Warm Groove",
    instrument: "keys",
    genre: "score",
    mood: ["warm", "deep"],
    tags: ["groove", "warm", "cinematic", "harmonic"],
    params: {
      tine: 0.42,
      bell: 0.18,
      body: 0.68,
      damp: 0.45,
      tremolo: 0.1,
      width: 0.42,
      cutoff: 4200,
      resonance: 1.2,
      attack: 0.015,
      release: 0.65,
      level: -8,
    },
  },
];

export const DRUM_FACTORY_PRESETS: DrumSynthPreset[] = [
  {
    id: "factory.drum.hat.tight",
    name: "Tight Hat",
    type: "hatClosed",
    genre: "house",
    mood: ["bright", "clean"],
    tags: ["hat", "tight", "crisp"],
    synth: { type: "hatClosed", decay: 0.06, tone: 8200, snap: 0.4, body: 0.3 },
  },
  {
    id: "factory.drum.hat.wash",
    name: "Wash Hat",
    type: "hatOpen",
    genre: "techno",
    mood: ["dark", "atmosphere"],
    tags: ["hat", "open", "wash", "shimmer"],
    synth: { type: "hatOpen", decay: 0.45, tone: 6800, snap: 0.65, body: 0.5 },
  },
  {
    id: "factory.drum.kick.808",
    name: "808 Kick",
    type: "kick",
    genre: "trap",
    mood: ["deep", "warm"],
    tags: ["kick", "808", "sub"],
    synth: { type: "kick", decay: 0.52, tone: 4200, snap: 0.25, body: 0.7 },
  },
  {
    id: "factory.drum.kick.punch",
    name: "Punch Kick",
    type: "kick",
    genre: "house",
    mood: ["aggressive", "bright"],
    tags: ["kick", "punch", "click"],
    synth: { type: "kick", decay: 0.38, tone: 5000, snap: 0.6, body: 0.4 },
  },
  {
    id: "factory.drum.snare.crisp",
    name: "Crisp Snare",
    type: "snare",
    genre: "trap",
    mood: ["bright", "aggressive"],
    tags: ["snare", "crisp", "snap"],
    synth: { type: "snare", decay: 0.2, tone: 2100, snap: 0.7, body: 0.3 },
  },
  {
    id: "factory.drum.snare.fat",
    name: "Fat Snare",
    type: "snare",
    genre: "house",
    mood: ["warm", "deep"],
    tags: ["snare", "fat", "body"],
    synth: { type: "snare", decay: 0.28, tone: 1600, snap: 0.3, body: 0.7 },
  },
];
