/**
 * GENERATED by scripts/convert-salamander.mjs — do not edit by hand.
 * Source: Salamander Grand Piano V3 44.1kHz/16-bit close (CC-BY 3.0,
 * Alexander Holm) — see src/sample-library/licenses.ts PACK_CREDITS.
 * 120 samples: 30 keys × 4 velocity zones.
 */
import type { SampleLayer } from "../project-model/types";

export const PIANO_PACK_LAYERS: SampleLayer[] = [
  {
    "id": "layer.piano.21.z1",
    "sampleId": "factory.piano.a0.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 21,
    "maxPitch": 21,
    "root": 21
  },
  {
    "id": "layer.piano.21.z2",
    "sampleId": "factory.piano.a0.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 21,
    "maxPitch": 21,
    "root": 21
  },
  {
    "id": "layer.piano.21.z3",
    "sampleId": "factory.piano.a0.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 21,
    "maxPitch": 21,
    "root": 21
  },
  {
    "id": "layer.piano.21.z4",
    "sampleId": "factory.piano.a0.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 21,
    "maxPitch": 21,
    "root": 21
  },
  {
    "id": "layer.piano.24.z1",
    "sampleId": "factory.piano.c1.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 24,
    "maxPitch": 24,
    "root": 24
  },
  {
    "id": "layer.piano.24.z2",
    "sampleId": "factory.piano.c1.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 24,
    "maxPitch": 24,
    "root": 24
  },
  {
    "id": "layer.piano.24.z3",
    "sampleId": "factory.piano.c1.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 24,
    "maxPitch": 24,
    "root": 24
  },
  {
    "id": "layer.piano.24.z4",
    "sampleId": "factory.piano.c1.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 24,
    "maxPitch": 24,
    "root": 24
  },
  {
    "id": "layer.piano.27.z1",
    "sampleId": "factory.piano.ds1.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 27,
    "maxPitch": 27,
    "root": 27
  },
  {
    "id": "layer.piano.27.z2",
    "sampleId": "factory.piano.ds1.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 27,
    "maxPitch": 27,
    "root": 27
  },
  {
    "id": "layer.piano.27.z3",
    "sampleId": "factory.piano.ds1.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 27,
    "maxPitch": 27,
    "root": 27
  },
  {
    "id": "layer.piano.27.z4",
    "sampleId": "factory.piano.ds1.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 27,
    "maxPitch": 27,
    "root": 27
  },
  {
    "id": "layer.piano.30.z1",
    "sampleId": "factory.piano.fs1.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 30,
    "maxPitch": 30,
    "root": 30
  },
  {
    "id": "layer.piano.30.z2",
    "sampleId": "factory.piano.fs1.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 30,
    "maxPitch": 30,
    "root": 30
  },
  {
    "id": "layer.piano.30.z3",
    "sampleId": "factory.piano.fs1.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 30,
    "maxPitch": 30,
    "root": 30
  },
  {
    "id": "layer.piano.30.z4",
    "sampleId": "factory.piano.fs1.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 30,
    "maxPitch": 30,
    "root": 30
  },
  {
    "id": "layer.piano.33.z1",
    "sampleId": "factory.piano.a1.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 33,
    "maxPitch": 33,
    "root": 33
  },
  {
    "id": "layer.piano.33.z2",
    "sampleId": "factory.piano.a1.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 33,
    "maxPitch": 33,
    "root": 33
  },
  {
    "id": "layer.piano.33.z3",
    "sampleId": "factory.piano.a1.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 33,
    "maxPitch": 33,
    "root": 33
  },
  {
    "id": "layer.piano.33.z4",
    "sampleId": "factory.piano.a1.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 33,
    "maxPitch": 33,
    "root": 33
  },
  {
    "id": "layer.piano.36.z1",
    "sampleId": "factory.piano.c2.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 36,
    "maxPitch": 36,
    "root": 36
  },
  {
    "id": "layer.piano.36.z2",
    "sampleId": "factory.piano.c2.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 36,
    "maxPitch": 36,
    "root": 36
  },
  {
    "id": "layer.piano.36.z3",
    "sampleId": "factory.piano.c2.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 36,
    "maxPitch": 36,
    "root": 36
  },
  {
    "id": "layer.piano.36.z4",
    "sampleId": "factory.piano.c2.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 36,
    "maxPitch": 36,
    "root": 36
  },
  {
    "id": "layer.piano.39.z1",
    "sampleId": "factory.piano.ds2.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 39,
    "maxPitch": 39,
    "root": 39
  },
  {
    "id": "layer.piano.39.z2",
    "sampleId": "factory.piano.ds2.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 39,
    "maxPitch": 39,
    "root": 39
  },
  {
    "id": "layer.piano.39.z3",
    "sampleId": "factory.piano.ds2.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 39,
    "maxPitch": 39,
    "root": 39
  },
  {
    "id": "layer.piano.39.z4",
    "sampleId": "factory.piano.ds2.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 39,
    "maxPitch": 39,
    "root": 39
  },
  {
    "id": "layer.piano.42.z1",
    "sampleId": "factory.piano.fs2.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 42,
    "maxPitch": 42,
    "root": 42
  },
  {
    "id": "layer.piano.42.z2",
    "sampleId": "factory.piano.fs2.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 42,
    "maxPitch": 42,
    "root": 42
  },
  {
    "id": "layer.piano.42.z3",
    "sampleId": "factory.piano.fs2.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 42,
    "maxPitch": 42,
    "root": 42
  },
  {
    "id": "layer.piano.42.z4",
    "sampleId": "factory.piano.fs2.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 42,
    "maxPitch": 42,
    "root": 42
  },
  {
    "id": "layer.piano.45.z1",
    "sampleId": "factory.piano.a2.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 45,
    "maxPitch": 45,
    "root": 45
  },
  {
    "id": "layer.piano.45.z2",
    "sampleId": "factory.piano.a2.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 45,
    "maxPitch": 45,
    "root": 45
  },
  {
    "id": "layer.piano.45.z3",
    "sampleId": "factory.piano.a2.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 45,
    "maxPitch": 45,
    "root": 45
  },
  {
    "id": "layer.piano.45.z4",
    "sampleId": "factory.piano.a2.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 45,
    "maxPitch": 45,
    "root": 45
  },
  {
    "id": "layer.piano.48.z1",
    "sampleId": "factory.piano.c3.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 48,
    "maxPitch": 48,
    "root": 48
  },
  {
    "id": "layer.piano.48.z2",
    "sampleId": "factory.piano.c3.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 48,
    "maxPitch": 48,
    "root": 48
  },
  {
    "id": "layer.piano.48.z3",
    "sampleId": "factory.piano.c3.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 48,
    "maxPitch": 48,
    "root": 48
  },
  {
    "id": "layer.piano.48.z4",
    "sampleId": "factory.piano.c3.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 48,
    "maxPitch": 48,
    "root": 48
  },
  {
    "id": "layer.piano.51.z1",
    "sampleId": "factory.piano.ds3.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 51,
    "maxPitch": 51,
    "root": 51
  },
  {
    "id": "layer.piano.51.z2",
    "sampleId": "factory.piano.ds3.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 51,
    "maxPitch": 51,
    "root": 51
  },
  {
    "id": "layer.piano.51.z3",
    "sampleId": "factory.piano.ds3.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 51,
    "maxPitch": 51,
    "root": 51
  },
  {
    "id": "layer.piano.51.z4",
    "sampleId": "factory.piano.ds3.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 51,
    "maxPitch": 51,
    "root": 51
  },
  {
    "id": "layer.piano.54.z1",
    "sampleId": "factory.piano.fs3.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 54,
    "maxPitch": 54,
    "root": 54
  },
  {
    "id": "layer.piano.54.z2",
    "sampleId": "factory.piano.fs3.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 54,
    "maxPitch": 54,
    "root": 54
  },
  {
    "id": "layer.piano.54.z3",
    "sampleId": "factory.piano.fs3.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 54,
    "maxPitch": 54,
    "root": 54
  },
  {
    "id": "layer.piano.54.z4",
    "sampleId": "factory.piano.fs3.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 54,
    "maxPitch": 54,
    "root": 54
  },
  {
    "id": "layer.piano.57.z1",
    "sampleId": "factory.piano.a3.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 57,
    "maxPitch": 57,
    "root": 57
  },
  {
    "id": "layer.piano.57.z2",
    "sampleId": "factory.piano.a3.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 57,
    "maxPitch": 57,
    "root": 57
  },
  {
    "id": "layer.piano.57.z3",
    "sampleId": "factory.piano.a3.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 57,
    "maxPitch": 57,
    "root": 57
  },
  {
    "id": "layer.piano.57.z4",
    "sampleId": "factory.piano.a3.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 57,
    "maxPitch": 57,
    "root": 57
  },
  {
    "id": "layer.piano.60.z1",
    "sampleId": "factory.piano.c4.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 60,
    "maxPitch": 60,
    "root": 60
  },
  {
    "id": "layer.piano.60.z2",
    "sampleId": "factory.piano.c4.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 60,
    "maxPitch": 60,
    "root": 60
  },
  {
    "id": "layer.piano.60.z3",
    "sampleId": "factory.piano.c4.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 60,
    "maxPitch": 60,
    "root": 60
  },
  {
    "id": "layer.piano.60.z4",
    "sampleId": "factory.piano.c4.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 60,
    "maxPitch": 60,
    "root": 60
  },
  {
    "id": "layer.piano.63.z1",
    "sampleId": "factory.piano.ds4.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 63,
    "maxPitch": 63,
    "root": 63
  },
  {
    "id": "layer.piano.63.z2",
    "sampleId": "factory.piano.ds4.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 63,
    "maxPitch": 63,
    "root": 63
  },
  {
    "id": "layer.piano.63.z3",
    "sampleId": "factory.piano.ds4.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 63,
    "maxPitch": 63,
    "root": 63
  },
  {
    "id": "layer.piano.63.z4",
    "sampleId": "factory.piano.ds4.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 63,
    "maxPitch": 63,
    "root": 63
  },
  {
    "id": "layer.piano.66.z1",
    "sampleId": "factory.piano.fs4.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 66,
    "maxPitch": 66,
    "root": 66
  },
  {
    "id": "layer.piano.66.z2",
    "sampleId": "factory.piano.fs4.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 66,
    "maxPitch": 66,
    "root": 66
  },
  {
    "id": "layer.piano.66.z3",
    "sampleId": "factory.piano.fs4.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 66,
    "maxPitch": 66,
    "root": 66
  },
  {
    "id": "layer.piano.66.z4",
    "sampleId": "factory.piano.fs4.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 66,
    "maxPitch": 66,
    "root": 66
  },
  {
    "id": "layer.piano.69.z1",
    "sampleId": "factory.piano.a4.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 69,
    "maxPitch": 69,
    "root": 69
  },
  {
    "id": "layer.piano.69.z2",
    "sampleId": "factory.piano.a4.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 69,
    "maxPitch": 69,
    "root": 69
  },
  {
    "id": "layer.piano.69.z3",
    "sampleId": "factory.piano.a4.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 69,
    "maxPitch": 69,
    "root": 69
  },
  {
    "id": "layer.piano.69.z4",
    "sampleId": "factory.piano.a4.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 69,
    "maxPitch": 69,
    "root": 69
  },
  {
    "id": "layer.piano.72.z1",
    "sampleId": "factory.piano.c5.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 72,
    "maxPitch": 72,
    "root": 72
  },
  {
    "id": "layer.piano.72.z2",
    "sampleId": "factory.piano.c5.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 72,
    "maxPitch": 72,
    "root": 72
  },
  {
    "id": "layer.piano.72.z3",
    "sampleId": "factory.piano.c5.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 72,
    "maxPitch": 72,
    "root": 72
  },
  {
    "id": "layer.piano.72.z4",
    "sampleId": "factory.piano.c5.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 72,
    "maxPitch": 72,
    "root": 72
  },
  {
    "id": "layer.piano.75.z1",
    "sampleId": "factory.piano.ds5.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 75,
    "maxPitch": 75,
    "root": 75
  },
  {
    "id": "layer.piano.75.z2",
    "sampleId": "factory.piano.ds5.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 75,
    "maxPitch": 75,
    "root": 75
  },
  {
    "id": "layer.piano.75.z3",
    "sampleId": "factory.piano.ds5.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 75,
    "maxPitch": 75,
    "root": 75
  },
  {
    "id": "layer.piano.75.z4",
    "sampleId": "factory.piano.ds5.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 75,
    "maxPitch": 75,
    "root": 75
  },
  {
    "id": "layer.piano.78.z1",
    "sampleId": "factory.piano.fs5.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 78,
    "maxPitch": 78,
    "root": 78
  },
  {
    "id": "layer.piano.78.z2",
    "sampleId": "factory.piano.fs5.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 78,
    "maxPitch": 78,
    "root": 78
  },
  {
    "id": "layer.piano.78.z3",
    "sampleId": "factory.piano.fs5.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 78,
    "maxPitch": 78,
    "root": 78
  },
  {
    "id": "layer.piano.78.z4",
    "sampleId": "factory.piano.fs5.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 78,
    "maxPitch": 78,
    "root": 78
  },
  {
    "id": "layer.piano.81.z1",
    "sampleId": "factory.piano.a5.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 81,
    "maxPitch": 81,
    "root": 81
  },
  {
    "id": "layer.piano.81.z2",
    "sampleId": "factory.piano.a5.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 81,
    "maxPitch": 81,
    "root": 81
  },
  {
    "id": "layer.piano.81.z3",
    "sampleId": "factory.piano.a5.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 81,
    "maxPitch": 81,
    "root": 81
  },
  {
    "id": "layer.piano.81.z4",
    "sampleId": "factory.piano.a5.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 81,
    "maxPitch": 81,
    "root": 81
  },
  {
    "id": "layer.piano.84.z1",
    "sampleId": "factory.piano.c6.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 84,
    "maxPitch": 84,
    "root": 84
  },
  {
    "id": "layer.piano.84.z2",
    "sampleId": "factory.piano.c6.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 84,
    "maxPitch": 84,
    "root": 84
  },
  {
    "id": "layer.piano.84.z3",
    "sampleId": "factory.piano.c6.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 84,
    "maxPitch": 84,
    "root": 84
  },
  {
    "id": "layer.piano.84.z4",
    "sampleId": "factory.piano.c6.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 84,
    "maxPitch": 84,
    "root": 84
  },
  {
    "id": "layer.piano.87.z1",
    "sampleId": "factory.piano.ds6.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 87,
    "maxPitch": 87,
    "root": 87
  },
  {
    "id": "layer.piano.87.z2",
    "sampleId": "factory.piano.ds6.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 87,
    "maxPitch": 87,
    "root": 87
  },
  {
    "id": "layer.piano.87.z3",
    "sampleId": "factory.piano.ds6.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 87,
    "maxPitch": 87,
    "root": 87
  },
  {
    "id": "layer.piano.87.z4",
    "sampleId": "factory.piano.ds6.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 87,
    "maxPitch": 87,
    "root": 87
  },
  {
    "id": "layer.piano.90.z1",
    "sampleId": "factory.piano.fs6.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 90,
    "maxPitch": 90,
    "root": 90
  },
  {
    "id": "layer.piano.90.z2",
    "sampleId": "factory.piano.fs6.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 90,
    "maxPitch": 90,
    "root": 90
  },
  {
    "id": "layer.piano.90.z3",
    "sampleId": "factory.piano.fs6.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 90,
    "maxPitch": 90,
    "root": 90
  },
  {
    "id": "layer.piano.90.z4",
    "sampleId": "factory.piano.fs6.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 90,
    "maxPitch": 90,
    "root": 90
  },
  {
    "id": "layer.piano.93.z1",
    "sampleId": "factory.piano.a6.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 93,
    "maxPitch": 93,
    "root": 93
  },
  {
    "id": "layer.piano.93.z2",
    "sampleId": "factory.piano.a6.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 93,
    "maxPitch": 93,
    "root": 93
  },
  {
    "id": "layer.piano.93.z3",
    "sampleId": "factory.piano.a6.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 93,
    "maxPitch": 93,
    "root": 93
  },
  {
    "id": "layer.piano.93.z4",
    "sampleId": "factory.piano.a6.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 93,
    "maxPitch": 93,
    "root": 93
  },
  {
    "id": "layer.piano.96.z1",
    "sampleId": "factory.piano.c7.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 96,
    "maxPitch": 96,
    "root": 96
  },
  {
    "id": "layer.piano.96.z2",
    "sampleId": "factory.piano.c7.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 96,
    "maxPitch": 96,
    "root": 96
  },
  {
    "id": "layer.piano.96.z3",
    "sampleId": "factory.piano.c7.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 96,
    "maxPitch": 96,
    "root": 96
  },
  {
    "id": "layer.piano.96.z4",
    "sampleId": "factory.piano.c7.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 96,
    "maxPitch": 96,
    "root": 96
  },
  {
    "id": "layer.piano.99.z1",
    "sampleId": "factory.piano.ds7.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 99,
    "maxPitch": 99,
    "root": 99
  },
  {
    "id": "layer.piano.99.z2",
    "sampleId": "factory.piano.ds7.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 99,
    "maxPitch": 99,
    "root": 99
  },
  {
    "id": "layer.piano.99.z3",
    "sampleId": "factory.piano.ds7.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 99,
    "maxPitch": 99,
    "root": 99
  },
  {
    "id": "layer.piano.99.z4",
    "sampleId": "factory.piano.ds7.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 99,
    "maxPitch": 99,
    "root": 99
  },
  {
    "id": "layer.piano.102.z1",
    "sampleId": "factory.piano.fs7.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 102,
    "maxPitch": 102,
    "root": 102
  },
  {
    "id": "layer.piano.102.z2",
    "sampleId": "factory.piano.fs7.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 102,
    "maxPitch": 102,
    "root": 102
  },
  {
    "id": "layer.piano.102.z3",
    "sampleId": "factory.piano.fs7.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 102,
    "maxPitch": 102,
    "root": 102
  },
  {
    "id": "layer.piano.102.z4",
    "sampleId": "factory.piano.fs7.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 102,
    "maxPitch": 102,
    "root": 102
  },
  {
    "id": "layer.piano.105.z1",
    "sampleId": "factory.piano.a7.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 105,
    "maxPitch": 105,
    "root": 105
  },
  {
    "id": "layer.piano.105.z2",
    "sampleId": "factory.piano.a7.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 105,
    "maxPitch": 105,
    "root": 105
  },
  {
    "id": "layer.piano.105.z3",
    "sampleId": "factory.piano.a7.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 105,
    "maxPitch": 105,
    "root": 105
  },
  {
    "id": "layer.piano.105.z4",
    "sampleId": "factory.piano.a7.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 105,
    "maxPitch": 105,
    "root": 105
  },
  {
    "id": "layer.piano.108.z1",
    "sampleId": "factory.piano.c8.z1",
    "min": 0,
    "max": 0.25,
    "minPitch": 108,
    "maxPitch": 108,
    "root": 108
  },
  {
    "id": "layer.piano.108.z2",
    "sampleId": "factory.piano.c8.z2",
    "min": 0.25,
    "max": 0.5,
    "minPitch": 108,
    "maxPitch": 108,
    "root": 108
  },
  {
    "id": "layer.piano.108.z3",
    "sampleId": "factory.piano.c8.z3",
    "min": 0.5,
    "max": 0.75,
    "minPitch": 108,
    "maxPitch": 108,
    "root": 108
  },
  {
    "id": "layer.piano.108.z4",
    "sampleId": "factory.piano.c8.z4",
    "min": 0.75,
    "max": 1,
    "minPitch": 108,
    "maxPitch": 108,
    "root": 108
  }
];
