/**
 * GENERATED by scripts/convert-vsco2.mjs — do not edit by hand.
 * Source: VSCO 2 Community Edition (CC0) — see src/sample-library/licenses.ts PACK_CREDITS.
 */
import type { SampleLayer } from "../project-model/types";

export const VSCO_PACK_LAYERS: SampleLayer[] = [
  {
    "id": "layer.vsco.violinens.r1",
    "sampleId": "factory.vsco.violinens.r1",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 56,
    "maxPitch": 57,
    "root": 57
  },
  {
    "id": "layer.vsco.violinens.r2",
    "sampleId": "factory.vsco.violinens.r2",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 68,
    "maxPitch": 70,
    "root": 69
  },
  {
    "id": "layer.vsco.violinens.r3",
    "sampleId": "factory.vsco.violinens.r3",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 58,
    "maxPitch": 60,
    "root": 59
  },
  {
    "id": "layer.vsco.violinens.r4",
    "sampleId": "factory.vsco.violinens.r4",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 81,
    "maxPitch": 84,
    "root": 83
  },
  {
    "id": "layer.vsco.violinens.r5",
    "sampleId": "factory.vsco.violinens.r5",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 71,
    "maxPitch": 73,
    "root": 72
  },
  {
    "id": "layer.vsco.violinens.r6",
    "sampleId": "factory.vsco.violinens.r6",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 61,
    "maxPitch": 63,
    "root": 62
  },
  {
    "id": "layer.vsco.violinens.r7",
    "sampleId": "factory.vsco.violinens.r7",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 85,
    "maxPitch": 86,
    "root": 86
  },
  {
    "id": "layer.vsco.violinens.r8",
    "sampleId": "factory.vsco.violinens.r8",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 74,
    "maxPitch": 77,
    "root": 76
  },
  {
    "id": "layer.vsco.violinens.r9",
    "sampleId": "factory.vsco.violinens.r9",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 64,
    "maxPitch": 67,
    "root": 66
  },
  {
    "id": "layer.vsco.violinens.r10",
    "sampleId": "factory.vsco.violinens.r10",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 55,
    "maxPitch": 55,
    "root": 55
  },
  {
    "id": "layer.vsco.violinens.r11",
    "sampleId": "factory.vsco.violinens.r11",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 78,
    "maxPitch": 80,
    "root": 79
  },
  {
    "id": "layer.vsco.violinens.r12",
    "sampleId": "factory.vsco.violinens.r12",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 56,
    "maxPitch": 57,
    "root": 57
  },
  {
    "id": "layer.vsco.violinens.r13",
    "sampleId": "factory.vsco.violinens.r13",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 68,
    "maxPitch": 70,
    "root": 69
  },
  {
    "id": "layer.vsco.violinens.r14",
    "sampleId": "factory.vsco.violinens.r14",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 58,
    "maxPitch": 60,
    "root": 59
  },
  {
    "id": "layer.vsco.violinens.r15",
    "sampleId": "factory.vsco.violinens.r15",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 81,
    "maxPitch": 84,
    "root": 83
  },
  {
    "id": "layer.vsco.violinens.r16",
    "sampleId": "factory.vsco.violinens.r16",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 71,
    "maxPitch": 73,
    "root": 72
  },
  {
    "id": "layer.vsco.violinens.r17",
    "sampleId": "factory.vsco.violinens.r17",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 61,
    "maxPitch": 63,
    "root": 62
  },
  {
    "id": "layer.vsco.violinens.r18",
    "sampleId": "factory.vsco.violinens.r18",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 85,
    "maxPitch": 86,
    "root": 86
  },
  {
    "id": "layer.vsco.violinens.r19",
    "sampleId": "factory.vsco.violinens.r19",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 74,
    "maxPitch": 77,
    "root": 76
  },
  {
    "id": "layer.vsco.violinens.r20",
    "sampleId": "factory.vsco.violinens.r20",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 64,
    "maxPitch": 67,
    "root": 66
  },
  {
    "id": "layer.vsco.violinens.r21",
    "sampleId": "factory.vsco.violinens.r21",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 55,
    "maxPitch": 55,
    "root": 55
  },
  {
    "id": "layer.vsco.violinens.r22",
    "sampleId": "factory.vsco.violinens.r22",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 78,
    "maxPitch": 80,
    "root": 79
  },
  {
    "id": "layer.vsco.celloens.r1",
    "sampleId": "factory.vsco.celloens.r1",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 55,
    "maxPitch": 58,
    "root": 57
  },
  {
    "id": "layer.vsco.celloens.r2",
    "sampleId": "factory.vsco.celloens.r2",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 45,
    "maxPitch": 48,
    "root": 47
  },
  {
    "id": "layer.vsco.celloens.r3",
    "sampleId": "factory.vsco.celloens.r3",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 69,
    "maxPitch": 72,
    "root": 71
  },
  {
    "id": "layer.vsco.celloens.r4",
    "sampleId": "factory.vsco.celloens.r4",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 36,
    "maxPitch": 37,
    "root": 36
  },
  {
    "id": "layer.vsco.celloens.r5",
    "sampleId": "factory.vsco.celloens.r5",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 59,
    "maxPitch": 61,
    "root": 60
  },
  {
    "id": "layer.vsco.celloens.r6",
    "sampleId": "factory.vsco.celloens.r6",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 49,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.celloens.r7",
    "sampleId": "factory.vsco.celloens.r7",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 73,
    "maxPitch": 75,
    "root": 74
  },
  {
    "id": "layer.vsco.celloens.r8",
    "sampleId": "factory.vsco.celloens.r8",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 38,
    "maxPitch": 41,
    "root": 40
  },
  {
    "id": "layer.vsco.celloens.r9",
    "sampleId": "factory.vsco.celloens.r9",
    "min": 0.33070866141732286,
    "max": 0.49606299212598426,
    "minPitch": 38,
    "maxPitch": 41,
    "root": 40
  },
  {
    "id": "layer.vsco.celloens.r10",
    "sampleId": "factory.vsco.celloens.r10",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 62,
    "maxPitch": 65,
    "root": 64
  },
  {
    "id": "layer.vsco.celloens.r11",
    "sampleId": "factory.vsco.celloens.r11",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 52,
    "maxPitch": 54,
    "root": 53
  },
  {
    "id": "layer.vsco.celloens.r12",
    "sampleId": "factory.vsco.celloens.r12",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 76,
    "maxPitch": 77,
    "root": 77
  },
  {
    "id": "layer.vsco.celloens.r13",
    "sampleId": "factory.vsco.celloens.r13",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 42,
    "maxPitch": 44,
    "root": 43
  },
  {
    "id": "layer.vsco.celloens.r14",
    "sampleId": "factory.vsco.celloens.r14",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 66,
    "maxPitch": 68,
    "root": 67
  },
  {
    "id": "layer.vsco.celloens.r15",
    "sampleId": "factory.vsco.celloens.r15",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 55,
    "maxPitch": 58,
    "root": 57
  },
  {
    "id": "layer.vsco.celloens.r16",
    "sampleId": "factory.vsco.celloens.r16",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 45,
    "maxPitch": 48,
    "root": 47
  },
  {
    "id": "layer.vsco.celloens.r17",
    "sampleId": "factory.vsco.celloens.r17",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 69,
    "maxPitch": 72,
    "root": 71
  },
  {
    "id": "layer.vsco.celloens.r18",
    "sampleId": "factory.vsco.celloens.r18",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 36,
    "maxPitch": 37,
    "root": 36
  },
  {
    "id": "layer.vsco.celloens.r19",
    "sampleId": "factory.vsco.celloens.r19",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 59,
    "maxPitch": 61,
    "root": 60
  },
  {
    "id": "layer.vsco.celloens.r20",
    "sampleId": "factory.vsco.celloens.r20",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 49,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.celloens.r21",
    "sampleId": "factory.vsco.celloens.r21",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 73,
    "maxPitch": 75,
    "root": 74
  },
  {
    "id": "layer.vsco.celloens.r22",
    "sampleId": "factory.vsco.celloens.r22",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 38,
    "maxPitch": 41,
    "root": 40
  },
  {
    "id": "layer.vsco.celloens.r23",
    "sampleId": "factory.vsco.celloens.r23",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 62,
    "maxPitch": 65,
    "root": 64
  },
  {
    "id": "layer.vsco.celloens.r24",
    "sampleId": "factory.vsco.celloens.r24",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 52,
    "maxPitch": 54,
    "root": 53
  },
  {
    "id": "layer.vsco.celloens.r25",
    "sampleId": "factory.vsco.celloens.r25",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 76,
    "maxPitch": 77,
    "root": 77
  },
  {
    "id": "layer.vsco.celloens.r26",
    "sampleId": "factory.vsco.celloens.r26",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 42,
    "maxPitch": 44,
    "root": 43
  },
  {
    "id": "layer.vsco.celloens.r27",
    "sampleId": "factory.vsco.celloens.r27",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 66,
    "maxPitch": 68,
    "root": 67
  },
  {
    "id": "layer.vsco.flute.r1",
    "sampleId": "factory.vsco.flute.r1",
    "min": 0,
    "max": 1,
    "minPitch": 67,
    "maxPitch": 70,
    "root": 69
  },
  {
    "id": "layer.vsco.flute.r2",
    "sampleId": "factory.vsco.flute.r2",
    "min": 0,
    "max": 1,
    "minPitch": 79,
    "maxPitch": 82,
    "root": 81
  },
  {
    "id": "layer.vsco.flute.r3",
    "sampleId": "factory.vsco.flute.r3",
    "min": 0,
    "max": 1,
    "minPitch": 91,
    "maxPitch": 94,
    "root": 93
  },
  {
    "id": "layer.vsco.flute.r4",
    "sampleId": "factory.vsco.flute.r4",
    "min": 0,
    "max": 1,
    "minPitch": 60,
    "maxPitch": 61,
    "root": 60
  },
  {
    "id": "layer.vsco.flute.r5",
    "sampleId": "factory.vsco.flute.r5",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 71,
    "maxPitch": 73,
    "root": 72
  },
  {
    "id": "layer.vsco.flute.r6",
    "sampleId": "factory.vsco.flute.r6",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 71,
    "maxPitch": 73,
    "root": 72
  },
  {
    "id": "layer.vsco.flute.r7",
    "sampleId": "factory.vsco.flute.r7",
    "min": 0,
    "max": 1,
    "minPitch": 83,
    "maxPitch": 85,
    "root": 84
  },
  {
    "id": "layer.vsco.flute.r8",
    "sampleId": "factory.vsco.flute.r8",
    "min": 0,
    "max": 1,
    "minPitch": 95,
    "maxPitch": 96,
    "root": 96
  },
  {
    "id": "layer.vsco.flute.r9",
    "sampleId": "factory.vsco.flute.r9",
    "min": 0,
    "max": 1,
    "minPitch": 62,
    "maxPitch": 66,
    "root": 64
  },
  {
    "id": "layer.vsco.flute.r10",
    "sampleId": "factory.vsco.flute.r10",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 74,
    "maxPitch": 78,
    "root": 76
  },
  {
    "id": "layer.vsco.flute.r11",
    "sampleId": "factory.vsco.flute.r11",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 74,
    "maxPitch": 78,
    "root": 76
  },
  {
    "id": "layer.vsco.flute.r12",
    "sampleId": "factory.vsco.flute.r12",
    "min": 0,
    "max": 0.49606299212598426,
    "minPitch": 86,
    "maxPitch": 90,
    "root": 88
  },
  {
    "id": "layer.vsco.flute.r13",
    "sampleId": "factory.vsco.flute.r13",
    "min": 0.49606299212598426,
    "max": 1,
    "minPitch": 86,
    "maxPitch": 90,
    "root": 88
  },
  {
    "id": "layer.vsco.clarinet.r1",
    "sampleId": "factory.vsco.clarinet.r1",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 56,
    "maxPitch": 59,
    "root": 58
  },
  {
    "id": "layer.vsco.clarinet.r2",
    "sampleId": "factory.vsco.clarinet.r2",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 68,
    "maxPitch": 71,
    "root": 70
  },
  {
    "id": "layer.vsco.clarinet.r3",
    "sampleId": "factory.vsco.clarinet.r3",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 80,
    "maxPitch": 83,
    "root": 82
  },
  {
    "id": "layer.vsco.clarinet.r4",
    "sampleId": "factory.vsco.clarinet.r4",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 50,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.clarinet.r5",
    "sampleId": "factory.vsco.clarinet.r5",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 60,
    "maxPitch": 63,
    "root": 62
  },
  {
    "id": "layer.vsco.clarinet.r6",
    "sampleId": "factory.vsco.clarinet.r6",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 72,
    "maxPitch": 75,
    "root": 74
  },
  {
    "id": "layer.vsco.clarinet.r7",
    "sampleId": "factory.vsco.clarinet.r7",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 84,
    "maxPitch": 87,
    "root": 86
  },
  {
    "id": "layer.vsco.clarinet.r8",
    "sampleId": "factory.vsco.clarinet.r8",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 88,
    "maxPitch": 90,
    "root": 89
  },
  {
    "id": "layer.vsco.clarinet.r9",
    "sampleId": "factory.vsco.clarinet.r9",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 52,
    "maxPitch": 55,
    "root": 53
  },
  {
    "id": "layer.vsco.clarinet.r10",
    "sampleId": "factory.vsco.clarinet.r10",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 64,
    "maxPitch": 67,
    "root": 65
  },
  {
    "id": "layer.vsco.clarinet.r11",
    "sampleId": "factory.vsco.clarinet.r11",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 76,
    "maxPitch": 79,
    "root": 77
  },
  {
    "id": "layer.vsco.clarinet.r12",
    "sampleId": "factory.vsco.clarinet.r12",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 56,
    "maxPitch": 59,
    "root": 58
  },
  {
    "id": "layer.vsco.clarinet.r13",
    "sampleId": "factory.vsco.clarinet.r13",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 68,
    "maxPitch": 71,
    "root": 70
  },
  {
    "id": "layer.vsco.clarinet.r14",
    "sampleId": "factory.vsco.clarinet.r14",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 80,
    "maxPitch": 83,
    "root": 82
  },
  {
    "id": "layer.vsco.clarinet.r15",
    "sampleId": "factory.vsco.clarinet.r15",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 50,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.clarinet.r16",
    "sampleId": "factory.vsco.clarinet.r16",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 60,
    "maxPitch": 63,
    "root": 62
  },
  {
    "id": "layer.vsco.clarinet.r17",
    "sampleId": "factory.vsco.clarinet.r17",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 72,
    "maxPitch": 75,
    "root": 74
  },
  {
    "id": "layer.vsco.clarinet.r18",
    "sampleId": "factory.vsco.clarinet.r18",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 84,
    "maxPitch": 87,
    "root": 86
  },
  {
    "id": "layer.vsco.clarinet.r19",
    "sampleId": "factory.vsco.clarinet.r19",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 88,
    "maxPitch": 90,
    "root": 89
  },
  {
    "id": "layer.vsco.clarinet.r20",
    "sampleId": "factory.vsco.clarinet.r20",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 52,
    "maxPitch": 55,
    "root": 53
  },
  {
    "id": "layer.vsco.clarinet.r21",
    "sampleId": "factory.vsco.clarinet.r21",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 64,
    "maxPitch": 67,
    "root": 65
  },
  {
    "id": "layer.vsco.clarinet.r22",
    "sampleId": "factory.vsco.clarinet.r22",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 76,
    "maxPitch": 79,
    "root": 77
  },
  {
    "id": "layer.vsco.clarinet.r23",
    "sampleId": "factory.vsco.clarinet.r23",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 56,
    "maxPitch": 59,
    "root": 58
  },
  {
    "id": "layer.vsco.clarinet.r24",
    "sampleId": "factory.vsco.clarinet.r24",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 68,
    "maxPitch": 71,
    "root": 70
  },
  {
    "id": "layer.vsco.clarinet.r25",
    "sampleId": "factory.vsco.clarinet.r25",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 80,
    "maxPitch": 83,
    "root": 82
  },
  {
    "id": "layer.vsco.clarinet.r26",
    "sampleId": "factory.vsco.clarinet.r26",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 50,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.clarinet.r27",
    "sampleId": "factory.vsco.clarinet.r27",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 60,
    "maxPitch": 63,
    "root": 62
  },
  {
    "id": "layer.vsco.clarinet.r28",
    "sampleId": "factory.vsco.clarinet.r28",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 72,
    "maxPitch": 75,
    "root": 74
  },
  {
    "id": "layer.vsco.clarinet.r29",
    "sampleId": "factory.vsco.clarinet.r29",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 84,
    "maxPitch": 87,
    "root": 86
  },
  {
    "id": "layer.vsco.clarinet.r30",
    "sampleId": "factory.vsco.clarinet.r30",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 88,
    "maxPitch": 90,
    "root": 89
  },
  {
    "id": "layer.vsco.clarinet.r31",
    "sampleId": "factory.vsco.clarinet.r31",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 52,
    "maxPitch": 55,
    "root": 53
  },
  {
    "id": "layer.vsco.clarinet.r32",
    "sampleId": "factory.vsco.clarinet.r32",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 64,
    "maxPitch": 67,
    "root": 65
  },
  {
    "id": "layer.vsco.clarinet.r33",
    "sampleId": "factory.vsco.clarinet.r33",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 76,
    "maxPitch": 79,
    "root": 77
  },
  {
    "id": "layer.vsco.fhorn.r1",
    "sampleId": "factory.vsco.fhorn.r1",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 45,
    "maxPitch": 47,
    "root": 46
  },
  {
    "id": "layer.vsco.fhorn.r2",
    "sampleId": "factory.vsco.fhorn.r2",
    "min": 0,
    "max": 1,
    "minPitch": 33,
    "maxPitch": 34,
    "root": 33
  },
  {
    "id": "layer.vsco.fhorn.r3",
    "sampleId": "factory.vsco.fhorn.r3",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 55,
    "maxPitch": 58,
    "root": 57
  },
  {
    "id": "layer.vsco.fhorn.r4",
    "sampleId": "factory.vsco.fhorn.r4",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 35,
    "maxPitch": 37,
    "root": 36
  },
  {
    "id": "layer.vsco.fhorn.r5",
    "sampleId": "factory.vsco.fhorn.r5",
    "min": 0,
    "max": 0.2440944881889764,
    "minPitch": 59,
    "maxPitch": 66,
    "root": 60
  },
  {
    "id": "layer.vsco.fhorn.r6",
    "sampleId": "factory.vsco.fhorn.r6",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 38,
    "maxPitch": 40,
    "root": 39
  },
  {
    "id": "layer.vsco.fhorn.r7",
    "sampleId": "factory.vsco.fhorn.r7",
    "min": 0,
    "max": 0.2440944881889764,
    "minPitch": 48,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.fhorn.r8",
    "sampleId": "factory.vsco.fhorn.r8",
    "min": 0,
    "max": 1,
    "minPitch": 67,
    "maxPitch": 75,
    "root": 74
  },
  {
    "id": "layer.vsco.fhorn.r9",
    "sampleId": "factory.vsco.fhorn.r9",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 52,
    "maxPitch": 54,
    "root": 53
  },
  {
    "id": "layer.vsco.fhorn.r10",
    "sampleId": "factory.vsco.fhorn.r10",
    "min": 0,
    "max": 1,
    "minPitch": 76,
    "maxPitch": 77,
    "root": 77
  },
  {
    "id": "layer.vsco.fhorn.r11",
    "sampleId": "factory.vsco.fhorn.r11",
    "min": 0,
    "max": 0.33070866141732286,
    "minPitch": 41,
    "maxPitch": 44,
    "root": 43
  },
  {
    "id": "layer.vsco.fhorn.r12",
    "sampleId": "factory.vsco.fhorn.r12",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 45,
    "maxPitch": 47,
    "root": 46
  },
  {
    "id": "layer.vsco.fhorn.r13",
    "sampleId": "factory.vsco.fhorn.r13",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 55,
    "maxPitch": 58,
    "root": 57
  },
  {
    "id": "layer.vsco.fhorn.r14",
    "sampleId": "factory.vsco.fhorn.r14",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 35,
    "maxPitch": 37,
    "root": 36
  },
  {
    "id": "layer.vsco.fhorn.r15",
    "sampleId": "factory.vsco.fhorn.r15",
    "min": 0.2440944881889764,
    "max": 0.49606299212598426,
    "minPitch": 59,
    "maxPitch": 66,
    "root": 60
  },
  {
    "id": "layer.vsco.fhorn.r16",
    "sampleId": "factory.vsco.fhorn.r16",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 38,
    "maxPitch": 40,
    "root": 39
  },
  {
    "id": "layer.vsco.fhorn.r17",
    "sampleId": "factory.vsco.fhorn.r17",
    "min": 0.2440944881889764,
    "max": 0.49606299212598426,
    "minPitch": 48,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.fhorn.r18",
    "sampleId": "factory.vsco.fhorn.r18",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 52,
    "maxPitch": 54,
    "root": 53
  },
  {
    "id": "layer.vsco.fhorn.r19",
    "sampleId": "factory.vsco.fhorn.r19",
    "min": 0.33070866141732286,
    "max": 0.6614173228346457,
    "minPitch": 41,
    "maxPitch": 44,
    "root": 43
  },
  {
    "id": "layer.vsco.fhorn.r20",
    "sampleId": "factory.vsco.fhorn.r20",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 45,
    "maxPitch": 47,
    "root": 46
  },
  {
    "id": "layer.vsco.fhorn.r21",
    "sampleId": "factory.vsco.fhorn.r21",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 55,
    "maxPitch": 58,
    "root": 57
  },
  {
    "id": "layer.vsco.fhorn.r22",
    "sampleId": "factory.vsco.fhorn.r22",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 35,
    "maxPitch": 37,
    "root": 36
  },
  {
    "id": "layer.vsco.fhorn.r23",
    "sampleId": "factory.vsco.fhorn.r23",
    "min": 0.49606299212598426,
    "max": 0.7480314960629921,
    "minPitch": 59,
    "maxPitch": 66,
    "root": 60
  },
  {
    "id": "layer.vsco.fhorn.r24",
    "sampleId": "factory.vsco.fhorn.r24",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 38,
    "maxPitch": 40,
    "root": 39
  },
  {
    "id": "layer.vsco.fhorn.r25",
    "sampleId": "factory.vsco.fhorn.r25",
    "min": 0.49606299212598426,
    "max": 0.7480314960629921,
    "minPitch": 48,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.fhorn.r26",
    "sampleId": "factory.vsco.fhorn.r26",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 52,
    "maxPitch": 54,
    "root": 53
  },
  {
    "id": "layer.vsco.fhorn.r27",
    "sampleId": "factory.vsco.fhorn.r27",
    "min": 0.6614173228346457,
    "max": 1,
    "minPitch": 41,
    "maxPitch": 44,
    "root": 43
  },
  {
    "id": "layer.vsco.fhorn.r28",
    "sampleId": "factory.vsco.fhorn.r28",
    "min": 0.7480314960629921,
    "max": 1,
    "minPitch": 59,
    "maxPitch": 66,
    "root": 60
  },
  {
    "id": "layer.vsco.fhorn.r29",
    "sampleId": "factory.vsco.fhorn.r29",
    "min": 0.7480314960629921,
    "max": 1,
    "minPitch": 48,
    "maxPitch": 51,
    "root": 50
  },
  {
    "id": "layer.vsco.harp.r1",
    "sampleId": "factory.vsco.harp.r1",
    "min": 0,
    "max": 1,
    "minPitch": 30,
    "maxPitch": 32,
    "root": 31
  },
  {
    "id": "layer.vsco.harp.r2",
    "sampleId": "factory.vsco.harp.r2",
    "min": 0,
    "max": 1,
    "minPitch": 43,
    "maxPitch": 46,
    "root": 45
  },
  {
    "id": "layer.vsco.harp.r3",
    "sampleId": "factory.vsco.harp.r3",
    "min": 0,
    "max": 1,
    "minPitch": 67,
    "maxPitch": 70,
    "root": 69
  },
  {
    "id": "layer.vsco.harp.r4",
    "sampleId": "factory.vsco.harp.r4",
    "min": 0,
    "max": 1,
    "minPitch": 91,
    "maxPitch": 93,
    "root": 93
  },
  {
    "id": "layer.vsco.harp.r5",
    "sampleId": "factory.vsco.harp.r5",
    "min": 0,
    "max": 1,
    "minPitch": 33,
    "maxPitch": 36,
    "root": 35
  },
  {
    "id": "layer.vsco.harp.r6",
    "sampleId": "factory.vsco.harp.r6",
    "min": 0,
    "max": 1,
    "minPitch": 57,
    "maxPitch": 60,
    "root": 59
  },
  {
    "id": "layer.vsco.harp.r7",
    "sampleId": "factory.vsco.harp.r7",
    "min": 0,
    "max": 1,
    "minPitch": 81,
    "maxPitch": 84,
    "root": 83
  },
  {
    "id": "layer.vsco.harp.r8",
    "sampleId": "factory.vsco.harp.r8",
    "min": 0,
    "max": 1,
    "minPitch": 94,
    "maxPitch": 96,
    "root": 95
  },
  {
    "id": "layer.vsco.harp.r9",
    "sampleId": "factory.vsco.harp.r9",
    "min": 0,
    "max": 1,
    "minPitch": 47,
    "maxPitch": 49,
    "root": 48
  },
  {
    "id": "layer.vsco.harp.r10",
    "sampleId": "factory.vsco.harp.r10",
    "min": 0,
    "max": 1,
    "minPitch": 71,
    "maxPitch": 73,
    "root": 72
  },
  {
    "id": "layer.vsco.harp.r11",
    "sampleId": "factory.vsco.harp.r11",
    "min": 0,
    "max": 1,
    "minPitch": 37,
    "maxPitch": 39,
    "root": 38
  },
  {
    "id": "layer.vsco.harp.r12",
    "sampleId": "factory.vsco.harp.r12",
    "min": 0,
    "max": 1,
    "minPitch": 61,
    "maxPitch": 63,
    "root": 62
  },
  {
    "id": "layer.vsco.harp.r13",
    "sampleId": "factory.vsco.harp.r13",
    "min": 0,
    "max": 1,
    "minPitch": 85,
    "maxPitch": 87,
    "root": 86
  },
  {
    "id": "layer.vsco.harp.r14",
    "sampleId": "factory.vsco.harp.r14",
    "min": 0,
    "max": 1,
    "minPitch": 50,
    "maxPitch": 53,
    "root": 52
  },
  {
    "id": "layer.vsco.harp.r15",
    "sampleId": "factory.vsco.harp.r15",
    "min": 0,
    "max": 1,
    "minPitch": 74,
    "maxPitch": 77,
    "root": 76
  },
  {
    "id": "layer.vsco.harp.r16",
    "sampleId": "factory.vsco.harp.r16",
    "min": 0,
    "max": 1,
    "minPitch": 40,
    "maxPitch": 42,
    "root": 41
  },
  {
    "id": "layer.vsco.harp.r17",
    "sampleId": "factory.vsco.harp.r17",
    "min": 0,
    "max": 1,
    "minPitch": 64,
    "maxPitch": 66,
    "root": 65
  },
  {
    "id": "layer.vsco.harp.r18",
    "sampleId": "factory.vsco.harp.r18",
    "min": 0,
    "max": 1,
    "minPitch": 88,
    "maxPitch": 90,
    "root": 89
  },
  {
    "id": "layer.vsco.harp.r19",
    "sampleId": "factory.vsco.harp.r19",
    "min": 0,
    "max": 1,
    "minPitch": 54,
    "maxPitch": 56,
    "root": 55
  },
  {
    "id": "layer.vsco.harp.r20",
    "sampleId": "factory.vsco.harp.r20",
    "min": 0,
    "max": 1,
    "minPitch": 78,
    "maxPitch": 80,
    "root": 79
  },
  {
    "id": "layer.vsco.harp.r21",
    "sampleId": "factory.vsco.harp.r21",
    "min": 0,
    "max": 1,
    "minPitch": 97,
    "maxPitch": 99,
    "root": 98
  },
  {
    "id": "layer.vsco.harp.r22",
    "sampleId": "factory.vsco.harp.r22",
    "min": 0,
    "max": 1,
    "minPitch": 28,
    "maxPitch": 29,
    "root": 28
  },
  {
    "id": "layer.vsco.harp.r23",
    "sampleId": "factory.vsco.harp.r23",
    "min": 0,
    "max": 1,
    "minPitch": 100,
    "maxPitch": 101,
    "root": 101
  },
  {
    "id": "layer.vsco.glockenspiel.r1",
    "sampleId": "factory.vsco.glockenspiel.r1",
    "min": 0,
    "max": 1,
    "minPitch": 70,
    "maxPitch": 75,
    "root": 72
  },
  {
    "id": "layer.vsco.glockenspiel.r2",
    "sampleId": "factory.vsco.glockenspiel.r2",
    "min": 0,
    "max": 1,
    "minPitch": 82,
    "maxPitch": 87,
    "root": 84
  },
  {
    "id": "layer.vsco.glockenspiel.r3",
    "sampleId": "factory.vsco.glockenspiel.r3",
    "min": 0,
    "max": 1,
    "minPitch": 94,
    "maxPitch": 96,
    "root": 96
  },
  {
    "id": "layer.vsco.glockenspiel.r4",
    "sampleId": "factory.vsco.glockenspiel.r4",
    "min": 0,
    "max": 1,
    "minPitch": 67,
    "maxPitch": 69,
    "root": 67
  },
  {
    "id": "layer.vsco.glockenspiel.r5",
    "sampleId": "factory.vsco.glockenspiel.r5",
    "min": 0,
    "max": 1,
    "minPitch": 76,
    "maxPitch": 81,
    "root": 79
  },
  {
    "id": "layer.vsco.glockenspiel.r6",
    "sampleId": "factory.vsco.glockenspiel.r6",
    "min": 0,
    "max": 1,
    "minPitch": 88,
    "maxPitch": 93,
    "root": 91
  },
  {
    "id": "layer.vsco.marimba.r1",
    "sampleId": "factory.vsco.marimba.r1",
    "min": 0,
    "max": 1,
    "minPitch": 57,
    "maxPitch": 61,
    "root": 59
  },
  {
    "id": "layer.vsco.marimba.r2",
    "sampleId": "factory.vsco.marimba.r2",
    "min": 0,
    "max": 1,
    "minPitch": 81,
    "maxPitch": 85,
    "root": 83
  },
  {
    "id": "layer.vsco.marimba.r3",
    "sampleId": "factory.vsco.marimba.r3",
    "min": 0,
    "max": 1,
    "minPitch": 45,
    "maxPitch": 51,
    "root": 48
  },
  {
    "id": "layer.vsco.marimba.r4",
    "sampleId": "factory.vsco.marimba.r4",
    "min": 0,
    "max": 1,
    "minPitch": 69,
    "maxPitch": 75,
    "root": 72
  },
  {
    "id": "layer.vsco.marimba.r5",
    "sampleId": "factory.vsco.marimba.r5",
    "min": 0,
    "max": 1,
    "minPitch": 93,
    "maxPitch": 96,
    "root": 96
  },
  {
    "id": "layer.vsco.marimba.r6",
    "sampleId": "factory.vsco.marimba.r6",
    "min": 0,
    "max": 1,
    "minPitch": 41,
    "maxPitch": 44,
    "root": 41
  },
  {
    "id": "layer.vsco.marimba.r7",
    "sampleId": "factory.vsco.marimba.r7",
    "min": 0,
    "max": 1,
    "minPitch": 62,
    "maxPitch": 68,
    "root": 65
  },
  {
    "id": "layer.vsco.marimba.r8",
    "sampleId": "factory.vsco.marimba.r8",
    "min": 0,
    "max": 1,
    "minPitch": 86,
    "maxPitch": 92,
    "root": 89
  },
  {
    "id": "layer.vsco.marimba.r9",
    "sampleId": "factory.vsco.marimba.r9",
    "min": 0,
    "max": 1,
    "minPitch": 52,
    "maxPitch": 56,
    "root": 55
  },
  {
    "id": "layer.vsco.marimba.r10",
    "sampleId": "factory.vsco.marimba.r10",
    "min": 0,
    "max": 1,
    "minPitch": 76,
    "maxPitch": 80,
    "root": 79
  }
];
