import io

p = 'src/sample-library/factory.ts'
s = io.open(p, encoding='utf-8').read()

# ── sadPiano ──
old = "function sadPiano(): Builder {\n  return (ctx, dest) => {\n    const t0 = ctx.currentTime;\n    const lpf = ctx.createBiquadFilter();\n    lpf.type = \"lowpass\";\n    lpf.frequency.value = 2400;\n    lpf.connect(dest);\n    for (const [mult, level, decay] of [\n      [1, 0.6, 1.7],\n      [2.002, 0.25, 0.9],\n      [3.004, 0.1, 0.45],\n      [4.998, 0.05, 0.25],\n    ] as [number, number, number][]) {\n      const osc = ctx.createOscillator();\n      osc.type = \"sine\";\n      osc.frequency.value = C4 * mult;\n      osc.connect(env(ctx, t0, level, decay)).connect(lpf);\n      osc.start(t0);\n      osc.stop(t0 + decay + 0.2);\n    }\n    const hammer = noiseSource(ctx, 79, 0.012, t0);\n    const hlp = ctx.createBiquadFilter();\n    hlp.type = \"lowpass\";\n    hlp.frequency.value = 3000;\n    hammer\n      .connect(hlp)\n      .connect(env(ctx, t0, 0.08, 0.01))\n      .connect(dest);\n  };\n}"
new = "function sadPiano(): Builder {\n  return (ctx, dest) => {\n    const t0 = ctx.currentTime;\n    const lpf = ctx.createBiquadFilter();\n    lpf.type = \"lowpass\";\n    lpf.frequency.value = 1900; // darker than keys (2400) — the heartbreak shade\n    lpf.connect(dest);\n    for (const [mult, level, decay] of [\n      [1, 0.6, 2.4], // longer sympathetic ring than keys' 1.7\n      [2.002, 0.28, 1.1],\n      [3.004, 0.1, 0.5],\n      [4.998, 0.05, 0.3],\n    ] as [number, number, number][]) {\n      for (const detune of [-4, 4]) {\n        // unison detune: the slow beating a depressed piano does — keys\n        // stays a clean single voice, this one BLEEDS\n        const osc = ctx.createOscillator();\n        osc.type = \"sine\";\n        osc.frequency.value = (C4 * mult) / 2 ** (Math.abs(detune) / 1200);\n        osc.detune.value = detune;\n        osc.connect(env(ctx, t0, level / 2, decay)).connect(lpf);\n        osc.start(t0);\n        osc.stop(t0 + decay + 0.2);\n      }\n    }\n    const hammer = noiseSource(ctx, 79, 0.014, t0);\n    const hlp = ctx.createBiquadFilter();\n    hlp.type = \"lowpass\";\n    hlp.frequency.value = 3000;\n    hammer\n      .connect(hlp)\n      .connect(env(ctx, t0, 0.09, 0.012))\n      .connect(dest);\n  };\n}"
assert old in s, 'sadPiano'
s = s.replace(old, new, 1)

# ── rhodes ──
old = "    const body = ctx.createOscillator();\n    body.type = \"sine\";\n    body.frequency.value = C4;\n    const bodyG = env(ctx, t0, 0.7, 1.4);\n    body.connect(bodyG).connect(dest);\n    body.start(t0);\n    body.stop(t0 + 1.6);\n    const tine = ctx.createOscillator();\n    tine.type = \"sine\";\n    tine.frequency.value = C4 * 3.98;\n    tine.frequency.exponentialRampToValueAtTime(C4 * 3.02, t0 + 0.25);\n    const tineG = env(ctx, t0, 0.3, 0.3);\n    tine.connect(tineG).connect(dest);\n    tine.start(t0);\n    tine.stop(t0 + 0.5);\n    const bark = ctx.createOscillator();\n    bark.type = \"triangle\";\n    bark.frequency.value = C4 * 2;\n    bark.connect(env(ctx, t0, 0.12, 0.5)).connect(dest);\n    bark.start(t0);\n    bark.stop(t0 + 0.7);\n  };\n}"
new = "    // the 200A tremolo: an LFO on the whole voice — keys has none, this\n    // wobble is the electric-piano fingerprint\n    const trem = ctx.createGain();\n    trem.gain.value = 1;\n    const lfo = ctx.createOscillator();\n    lfo.type = \"sine\";\n    lfo.frequency.value = 4.8;\n    const lfoGain = ctx.createGain();\n    lfoGain.gain.value = 0.22;\n    lfo.connect(lfoGain).connect(trem.gain);\n    lfo.start(t0);\n    lfo.stop(t0 + 1.9);\n    trem.connect(dest);\n    const body = ctx.createOscillator();\n    body.type = \"sine\";\n    body.frequency.value = C4;\n    const bodyG = env(ctx, t0, 0.7, 1.6); // longer tail than keys\n    body.connect(bodyG).connect(trem);\n    body.start(t0);\n    body.stop(t0 + 1.9);\n    const tine = ctx.createOscillator();\n    tine.type = \"sine\";\n    tine.frequency.value = C4 * 4.6; // brighter attack than keys' octave\n    tine.frequency.exponentialRampToValueAtTime(C4 * 2.8, t0 + 0.3);\n    const tineG = env(ctx, t0, 0.34, 0.36);\n    tine.connect(tineG).connect(trem);\n    tine.start(t0);\n    tine.stop(t0 + 0.6);\n    const bark = ctx.createOscillator();\n    bark.type = \"triangle\";\n    bark.frequency.value = C4 * 2;\n    bark.connect(env(ctx, t0, 0.16, 0.55)).connect(trem);\n    bark.start(t0);\n    bark.stop(t0 + 0.8);\n  };\n}"
assert old in s, 'rhodes'
s = s.replace(old, new, 1)

# ── harpTone ──
old = "    // Faster, fingered decays than the keys stack + a nail transient on the\n    // attack — without it the harp measured 0.973-correlated with tonal.keys\n    // (a duplicate, not a second voice).\n    const parts: [number, number, number][] = [\n      [1, 0.5, 0.75],\n      [2.001, 0.3, 0.5],\n      [3.003, 0.18, 0.36],\n      [4.005, 0.1, 0.26],\n      [5.01, 0.06, 0.18],\n    ];"
new = "    // Inharmonic string ratios (a harp string is not a harmonic series) +\n    // the fastest staggered cascade in the bank — keys rings as one voice,\n    // the harp SPARKLES: each partial rings off at its own rate.\n    const parts: [number, number, number][] = [\n      [1, 0.5, 0.5],\n      [2.004, 0.32, 0.38],\n      [3.02, 0.2, 0.3],\n      [4.11, 0.12, 0.24],\n      [5.34, 0.08, 0.18],\n      [6.79, 0.05, 0.13],\n    ];"
assert old in s, 'harpTone parts'
s = s.replace(old, new, 1)
old = "      .connect(env(ctx, t0, 0.12, 0.01))\n      .connect(dest);\n  };\n}\n\nfunction bell(): Builder {"
new = "      .connect(env(ctx, t0, 0.16, 0.012))\n      .connect(dest);\n  };\n}\n\nfunction bell(): Builder {"
assert old in s, 'harpTone nail'
s = s.replace(old, new, 1)

# ── pluck ──
old = "    const osc = ctx.createOscillator();\n    osc.type = \"triangle\";\n    osc.frequency.value = C4;\n    const osc2 = ctx.createOscillator();\n    osc2.type = \"sine\";\n    osc2.frequency.value = C4 * 2.003;\n    const g2 = ctx.createGain();\n    g2.gain.value = 0.35;\n    osc.connect(env(ctx, t0, 0.85, 0.38)).connect(dest);\n    osc2\n      .connect(g2)\n      .connect(env(ctx, t0, 0.5, 0.18))\n      .connect(dest);\n    osc.start(t0);\n    osc.stop(t0 + 0.45);\n    osc2.start(t0);\n    osc2.stop(t0 + 0.25);\n  };\n}"
new = "    // gated woody pluck: the body through a soft LPF with a FAST decay —\n    // keys rings, the pluck THUMBS. The brightness stays in a short sine\n    // on top so the attack still reads.\n    const lpf = ctx.createBiquadFilter();\n    lpf.type = \"lowpass\";\n    lpf.frequency.value = 1500;\n    lpf.connect(dest);\n    const osc = ctx.createOscillator();\n    osc.type = \"triangle\";\n    osc.frequency.value = C4;\n    osc.connect(env(ctx, t0, 0.85, 0.26)).connect(lpf);\n    osc.start(t0);\n    osc.stop(t0 + 0.32);\n    const osc2 = ctx.createOscillator();\n    osc2.type = \"sine\";\n    osc2.frequency.value = C4 * 2.003;\n    const g2 = ctx.createGain();\n    g2.gain.value = 0.4;\n    osc2\n      .connect(g2)\n      .connect(env(ctx, t0, 0.5, 0.12))\n      .connect(dest);\n    osc2.start(t0);\n    osc2.stop(t0 + 0.18);\n  };\n}"
assert old in s, 'pluck'
s = s.replace(old, new, 1)

io.open(p, 'w', encoding='utf-8', newline='\n').write(s)
print('4 tonal builders differentiated')
