import { parseIntentText } from "../src/intent/text-parser";

const probes: Array<[string, string]> = [
  ["dubstep", "dubstep beat"],
  ["brostep", "brostep drop"],
  ["riddim", "riddim bass"],
  ["melodic dubstep", "melodic dubstep"],
  ["trip hop", "trip hop downtempo"],
  ["downtempo", "downtempo chill"],
  ["reggae", "reggae riddim"],
  ["dub", "dub soundsystem"],
  ["soundsystem", "soundsystem dub"],
  ["grime", "grime instrumental"],
  ["trance", "uplifting trance"],
  ["psytrance", "psytrance full on"],
  ["gabber", "gabber 180"],
  ["hardcore techno", "hardcore techno"],
  ["uptempo", "uptempo hardcore"],
  ["synthwave", "synthwave outrun"],
  ["darksynth", "darksynth"],
  ["shoegaze", "shoegaze wall of sound"],
  ["dream pop", "dream pop"],
  ["nu jazz", "nu jazz broken"],
  ["broken beat", "broken beat"],
  ["funk", "funk groove"],
  ["boogie", "boogie funk"],
  ["balearic", "balearic sunset house"],
  ["jungle", "jungle breaks"],
  ["breakcore", "breakcore 180"],
  ["city pop", "city pop tokyo"],
  ["k-pop", "k-pop idol"],
  ["corridos", "corridos tumbados"],
  ["lo-fi", "lo-fi chill"],
  ["lofi", "lofi beats"],
  ["drum and bass", "drum and bass"],
  ["dancehall", "dancehall riddim"],
  ["afrobeats", "afrobeats"],
  ["amapiano", "amapiano log drum"],
  ["gqom", "gqom"],
  ["kuduro", "kuduro"],
  ["baile funk", "baile funk"],
  ["reggaeton", "reggaeton"],
  ["dembow", "dembow"],
  ["phonk", "phonk drift"],
  ["jersey club", "jersey club"],
  ["hyperpop", "hyperpop"],
  ["hardstyle", "hardstyle"],
  ["ebm", "ebm body music"],
  ["trap soul", "trap soul"],
  ["bedroom pop", "bedroom pop"],
  ["gfunk", "g-funk"],
  ["headnod", "head nod boom bap"],
  ["miami bass", "miami bass"],
  ["snap", "snap music"],
  ["bounce", "nola bounce"],
  ["country rap", "country rap tune"],
  ["drill", "uk drill"],
  ["dark ambient", "dark ambient drone"],
  ["drone", "drone ambient"],
  ["new age", "new age meditation"],
  ["post rock", "post rock"],
  ["speed garage", "speed garage"],
  ["bassline", "bassline house"],
  ["afroswing", "afroswing"],
  ["sophisti pop", "sophisti pop"],
  ["vaporwave", "vaporwave"],
  ["chillhop", "chillhop"],
];

for (const [label, text] of probes) {
  const p = parseIntentText(text);
  const g = p.input.genre ?? "-";
  const s = p.input.style ?? "-";
  console.log(`${label.padEnd(18)} -> genre=${String(g).padEnd(10)} style=${s}`);
}
