/**
 * SAMPLE LICENSE REGISTRY — the redistribution-rights table for everything
 * the app ships or loads as a factory asset.
 *
 * WHY A REGISTRY: the app REDISTRIBUTES raw sample WAVs inside its own
 * binary (unlike a music tool, where "free for your songs" is enough).
 * That is stricter: the license must allow redistribution in a commercial
 * product, and CC-BY adds a credits obligation we fulfil in
 * `public/licenses/credits.md` (generated from this table by
 * `tests/sample-license-gate.test.ts`).
 *
 * NOT allowed by this registry (documented rejections):
 *   - CC-BY-NC — non-commercial excludes a paid/shipped product
 *   - CC-BY-ND — "no derivatives" forbids the sampling itself
 *   - CC-BY-SA — share-alike conflicts with the proprietary app license
 *   - "free for your music" site licenses (LABS, PianoBook, Spitfire…) —
 *     they grant end-user music use, NOT raw-sample redistribution in a
 *     tool. They require a per-pack vendor review before entering here.
 */

export type SampleLicense = "cc0" | "cc-by-3.0" | "cc-by-4.0" | "kyx-original";

export interface LicenseInfo {
  /** SPDX-style short id shown in the credits file. */
  id: SampleLicense;
  name: string;
  /** Full attribution line written into credits.md. */
  attribution: string;
  /** Whether redistribution inside the shipped app is licensed. */
  redistributable: boolean;
}

export const LICENSES: Record<SampleLicense, LicenseInfo> = {
  "kyx-original": {
    id: "kyx-original",
    name: "KYX original",
    attribution: "© KYX — first-party content.",
    redistributable: true,
  },
  cc0: {
    id: "cc0",
    name: "CC0 1.0 Universal",
    attribution: "CC0 1.0 Universal — no attribution required (credited as good practice).",
    redistributable: true,
  },
  "cc-by-3.0": {
    id: "cc-by-3.0",
    name: "Creative Commons Attribution 3.0 Unported",
    attribution: "Creative Commons Attribution 3.0 Unported — see https://creativecommons.org/licenses/by/3.0/.",
    redistributable: true,
  },
  "cc-by-4.0": {
    id: "cc-by-4.0",
    name: "Creative Commons Attribution 4.0 International",
    attribution: "Creative Commons Attribution 4.0 International — see https://creativecommons.org/licenses/by/4.0/.",
    redistributable: true,
  },
};

/** Packs approved for redistribution. Each entry names every obligation the
 * gate test enforces (license + credits line). Grows one entry per pack. */
export interface PackCredits {
  pack: string;
  license: SampleLicense;
  /** Attribution line(s) — written into credits.md verbatim. */
  credits: string[];
  sourceUrl: string;
}

export const PACK_CREDITS: PackCredits[] = [
  {
    pack: "VSCO 2 Community Edition (orchestral subset)",
    license: "cc0",
    credits: [
      "Orchestral instruments (strings, winds, mallets, harp) — Versilian Studios VSCO 2 Community Edition.",
      "CC0 1.0 Universal — dedicated to the public domain (see LICENSE in the pack).",
    ],
    sourceUrl: "https://archive.org/details/vsco-2-ce-sfz",
  },
  {
    pack: "Salamander Grand Piano V3 (44.1kHz 16-bit close)",
    license: "cc-by-3.0",
    credits: [
      "Yamaha C5 grand piano, 88 keys × 16 velocity layers, close mic.",
      "Recorded by Alexander Holm (Salamander Grand Piano project).",
    ],
    sourceUrl: "https://archive.org/details/SalamanderGrandPianoV3",
  },
];

/** The credits.md body generated from this table (the gate test pins its
 * content against a fresh render so the file can never go stale). */
export function renderCredits(): string {
  const lines: string[] = [
    "# Sample credits",
    "",
    "Licenses of the sample material shipped with KYX. Regenerated by",
    "`tests/sample-license-gate.test.ts` — edit PACK_CREDITS in",
    "`src/sample-library/licenses.ts`, not this file.",
    "",
  ];
  for (const pack of PACK_CREDITS) {
    const info = LICENSES[pack.license];
    lines.push(`## ${pack.pack} — ${info.name}`);
    lines.push("");
    lines.push(`Source: ${pack.sourceUrl}`);
    for (const credit of pack.credits) lines.push(`- ${credit}`);
    lines.push(`- ${info.attribution}`);
    lines.push("");
  }
  return lines.join("\n");
}
