import type { EffectType } from "../project-model/types";

export interface EffectPreset {
  id: string;
  name: string;
  type: EffectType;
  params: Record<string, number>;
  /** Step pattern for step-sequenced effects. */
  steps?: number[];
  /** Beat Mangler envelopes are distinct project fields from gate patterns. */
  volumeSteps?: number[];
  pitchSteps?: number[];
  /** Per-preset output compensation in dB; generated measurements fill gaps. */
  outputTrimDb?: number;
}

const preset = (id: string, name: string, type: EffectType, params: Record<string, number>): EffectPreset => ({
  id,
  name,
  type,
  params,
});
const stepPreset = (
  id: string,
  name: string,
  type: EffectType,
  params: Record<string, number>,
  steps: number[],
): EffectPreset => ({ id, name, type, params, steps });
const manglerPreset = (
  id: string,
  name: string,
  params: Record<string, number>,
  volumeSteps: number[],
  pitchSteps?: number[],
): EffectPreset => ({ id, name, type: "beatMangler", params, volumeSteps, pitchSteps });

export const CORE_EFFECT_PRESETS: EffectPreset[] = [
  preset("eq-clean", "Clean", "eq", { lowShelfGain: 0, lowMidGain: 0, highMidGain: 0, highShelfGain: 0 }),
  preset("eq-air", "Air Lift", "eq", { highShelfFreq: 6500, highShelfGain: 2.5, lowMidGain: -1 }),
  preset("eq-warm", "Warm", "eq", { lowShelfGain: 2, lowShelfFreq: 130, highShelfGain: -1.5, highShelfFreq: 8000 }),
  preset("eq-vocal", "Presence", "eq", { lowShelfGain: -2, lowMidGain: -1, highMidFreq: 2800, highMidGain: 2 }),
  preset("transient-punch", "Punch", "transient", { attack: 0.55, sustain: -0.15, sensitivity: 0.65 }),
  preset("transient-tight", "Tight", "transient", { attack: 0.2, sustain: -0.55, sensitivity: 0.7 }),
  preset("transient-body", "Body", "transient", { attack: -0.2, sustain: 0.45, sensitivity: 0.45 }),
  preset("clipper-soft", "Soft Clip", "clipper", { drive: 0.16, ceiling: -1, softness: 0.42, output: -1 }),
  preset("clipper-kick", "Kick Ceiling", "clipper", { drive: 0.24, ceiling: -1, softness: 0.24, output: -2 }),
  preset("limiter-safety", "Safety", "limiter", {
    ceiling: -1,
    threshold: -1.5,
    release: 0.12,
    lookaheadMs: 5,
    link: 1,
    mix: 1,
  }),
  preset("limiter-punch", "Punch", "limiter", {
    ceiling: -1,
    threshold: -6,
    release: 0.06,
    lookaheadMs: 3,
    link: 1,
    mix: 1,
  }),
  preset("limiter-slam", "Slam", "limiter", {
    ceiling: -1,
    threshold: -14,
    release: 0.18,
    lookaheadMs: 5,
    link: 1,
    mix: 1,
  }),
  stepPreset(
    "stepgate-trance",
    "Trance 1/16",
    "stepGate",
    { division: 4, depth: 1, smooth: 0.08, mix: 1 },
    [1, 0.35, 0.75, 0.25, 0.9, 0.3, 0.7, 0.2, 1, 0.35, 0.75, 0.25, 0.9, 0.3, 0.65, 0.18],
  ),
  stepPreset(
    "stepgate-stutter",
    "Stutter",
    "stepGate",
    { division: 4, depth: 1, smooth: 0.02, mix: 1 },
    [1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0],
  ),
  stepPreset(
    "stepgate-swell",
    "Slow Swell",
    "stepGate",
    { division: 1, depth: 0.85, smooth: 0.75, mix: 1 },
    [0, 0.2, 0.5, 0.8, 1, 1, 0.8, 0.4],
  ),
  stepPreset(
    "stepgate-pad",
    "Gated Pad",
    "stepGate",
    { division: 3, depth: 1, smooth: 0.25, mix: 1 },
    [1, 0.6, 0.2, 0.6, 1, 0.4, 0.7, 0.3],
  ),
  preset("comp-glue", "Glue", "compressor", {
    threshold: -20,
    ratio: 2,
    attack: 0.03,
    release: 0.25,
    knee: 12,
    detector: 0,
    scHpf: 20,
    makeup: 3,
    mix: 1,
  }),
  preset("comp-punch", "Punch", "compressor", {
    threshold: -16,
    ratio: 4,
    attack: 0.005,
    release: 0.12,
    knee: 6,
    detector: 1,
    scHpf: 20,
    makeup: 4,
    mix: 1,
  }),
  preset("comp-smash", "Smash", "compressor", {
    threshold: -24,
    ratio: 12,
    attack: 0.003,
    release: 0.08,
    knee: 0,
    detector: 1,
    scHpf: 60,
    makeup: 7,
    mix: 0.7,
  }),
  preset("comp-bass-level", "Bass Level", "compressor", {
    threshold: -22,
    ratio: 3,
    attack: 0.02,
    release: 0.3,
    knee: 9,
    detector: 0,
    scHpf: 120,
    makeup: 2,
    mix: 1,
  }),
  preset("svf-lp-warm", "LP Warm", "svFilter", { cutoff: 1200, resonance: 0.15, mode: 0, drive: 0.25, mix: 1 }),
  preset("svf-lp-acid", "LP Acid", "svFilter", { cutoff: 400, resonance: 0.85, mode: 0, drive: 0.5, mix: 1 }),
  preset("svf-hp-clean", "HP Clean", "svFilter", { cutoff: 300, resonance: 0.1, mode: 1, drive: 0, mix: 1 }),
  preset("svf-bp-hollow", "BP Hollow", "svFilter", { cutoff: 800, resonance: 0.6, mode: 2, drive: 0.15, mix: 1 }),
  preset("svf-notch-fix", "Notch Fix", "svFilter", { cutoff: 1200, resonance: 0.4, mode: 3, drive: 0, mix: 1 }),
  preset("flanger-classic", "Classic", "flanger", {
    rate: 0.3,
    depth: 4,
    base: 5,
    feedback: 0.55,
    spread: 0.8,
    mix: 0.5,
  }),
  preset("flanger-subtle", "Subtle", "flanger", {
    rate: 0.2,
    depth: 1.5,
    base: 8,
    feedback: 0.25,
    spread: 0.9,
    mix: 0.3,
  }),
  preset("flanger-jet", "Jet", "flanger", { rate: 0.8, depth: 7, base: 1.5, feedback: 0.85, spread: 0.4, mix: 0.65 }),
  preset("tremolo-classic", "Classic", "tremolo", { rate: 5, depth: 0.7, shape: 0, mode: 0, mix: 1 }),
  preset("tremolo-hard", "Hard Gate", "tremolo", { rate: 8, depth: 0.95, shape: 0.9, mode: 0, mix: 1 }),
  preset("tremolo-pan", "Auto Pan", "tremolo", { rate: 2, depth: 0.85, shape: 0, mode: 1, mix: 1 }),
  preset("autowah-classic", "Classic Wah", "autowah", {
    minFreq: 300,
    maxFreq: 2500,
    resonance: 0.7,
    attack: 0.01,
    release: 0.15,
    sensitivity: 1.5,
    mode: 0,
    mix: 1,
  }),
  preset("autowah-bass", "Bass Wah", "autowah", {
    minFreq: 100,
    maxFreq: 800,
    resonance: 0.8,
    attack: 0.02,
    release: 0.3,
    sensitivity: 2,
    mode: 1,
    mix: 1,
  }),
  preset("autowah-funky", "Funky", "autowah", {
    minFreq: 400,
    maxFreq: 4000,
    resonance: 0.9,
    attack: 0.005,
    release: 0.08,
    sensitivity: 2.5,
    mode: 0,
    mix: 0.85,
  }),
  stepPreset(
    "stutter-1-16",
    "1/16 Loop",
    "stutter",
    { division: 4, mix: 0.8, feedback: 0 },
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  ),
  stepPreset(
    "stutter-gate",
    "Gate Loop",
    "stutter",
    { division: 4, mix: 0.9, feedback: 0.2 },
    [1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
  ),
  stepPreset(
    "stutter-chop",
    "Chop",
    "stutter",
    { division: 3, mix: 0.85, feedback: 0.35 },
    [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0],
  ),
  preset("comb-tight", "Tight", "comb", { delayMs: 4, feedback: 0.35, damp: 8000, mix: 0.45 }),
  preset("comb-reso", "Resonant", "comb", { delayMs: 14, feedback: 0.72, damp: 5000, mix: 0.55 }),
  preset("comb-metallic", "Metallic", "comb", { delayMs: 28, feedback: -0.68, damp: 4000, mix: 0.6 }),
  preset("vowel-ae", "A→E", "vowel", { vowel: 0.5, resonance: 0.6, mix: 1 }),
  preset("vowel-io", "I→O", "vowel", { vowel: 2.5, resonance: 0.7, mix: 1 }),
  preset("vowel-u", "U Hollow", "vowel", { vowel: 4, resonance: 0.5, mix: 0.85 }),
  preset("duck-clean", "Clean", "duckDelay", {
    time: 375,
    feedback: 0.35,
    tone: 4000,
    duckAmount: 0.6,
    duckThresh: -24,
    mix: 0.3,
  }),
  preset("duck-pump", "Heavy Duck", "duckDelay", {
    time: 450,
    feedback: 0.45,
    tone: 3200,
    duckAmount: 0.85,
    duckThresh: -28,
    duckAttack: 0.002,
    duckRelease: 0.22,
    mix: 0.35,
  }),
  preset("duck-slap", "Slap", "duckDelay", {
    time: 140,
    feedback: 0.25,
    tone: 5500,
    duckAmount: 0.5,
    duckThresh: -20,
    mix: 0.4,
  }),
  preset("tape-warm", "Warm Tape", "tapeSat", { drive: 0.35, hysteresis: 0.25, tone: 6500, mix: 1, output: 0 }),
  preset("tape-hot", "Hot Tape", "tapeSat", { drive: 0.65, hysteresis: 0.55, tone: 5000, mix: 1, output: -1 }),
  preset("tape-crunch", "Tape Crunch", "tapeSat", { drive: 0.8, hysteresis: 0.45, tone: 8000, mix: 0.85, output: 0 }),
  preset("tape-808-harmonics", "808 Harmonics", "tapeSat", {
    drive: 0.48,
    hysteresis: 0.16,
    tone: 7600,
    mix: 0.72,
    output: -2,
  }),
  preset("mseq-vocal", "Vocal Clarity", "msEq", {
    midLowGain: -1,
    midHighGain: 1.5,
    sideLowGain: -0.5,
    sideHighGain: 2,
  }),
  preset("mseq-wide", "Wide Air", "msEq", { sideHighGain: 2.5, sideHighFreq: 8000, midLowGain: 0.5, sideLowGain: -1 }),
  preset("mseq-tight", "Tight Mono", "msEq", {
    midLowGain: 1.2,
    midHighGain: -0.5,
    sideLowGain: -2,
    sideHighGain: 0.5,
  }),
  preset("haas-wide", "Wide Haas", "haasWidener", { delayMs: 14, width: 0.8, feedback: 0.15 }),
  preset("haas-subtle", "Subtle Haas", "haasWidener", { delayMs: 8, width: 0.5, feedback: 0 }),
  preset("haas-spread", "Spread", "haasWidener", { delayMs: 22, width: 0.9, feedback: 0.25 }),
  preset("multiband-smile", "Smile", "multiband", { lowGain: 1.5, midGain: -1, highGain: 1 }),
  preset("multiband-focus", "Mid Focus", "multiband", { lowGain: -1, midGain: 2, highGain: -0.5 }),
  preset("multiband-heavy", "Heavy Low", "multiband", { lowGain: 2.5, midGain: -0.5, highGain: -1 }),
  preset("drum-glue", "Glue", "drumBuss", { drive: 0.18, transient: 0.12, compressor: 0.32, boomAmount: 0.08 }),
  preset("drum-crush", "Crush", "drumBuss", { drive: 0.55, transient: 0.4, compressor: 0.7, mix: 0.7 }),
  preset("drum-punch", "Punch", "drumBuss", { drive: 0.2, transient: 0.55, compressor: 0.22, boomAmount: 0.1 }),
  preset("bass-solid", "Solid", "bassBuss", {
    drive: 0.12,
    subEnhance: 0.2,
    compression: 0.35,
    monoBassFrequency: 100,
  }),
  preset("bass-grit", "Grit", "bassBuss", { drive: 0.45, subEnhance: 0.12, compression: 0.4, mix: 0.85 }),
  preset("bass-sub", "Sub Focus", "bassBuss", {
    drive: 0.08,
    subEnhance: 0.55,
    subFrequency: 58,
    monoBassFrequency: 120,
  }),
  preset("utility-mono", "Mono Bass", "utility", { width: 1, monoBassFrequency: 120 }),
  preset("utility-wide", "Wide", "utility", { width: 1.35, pan: 0 }),
  preset("utility-gain", "Gain Trim", "utility", { gain: -6, width: 1 }),
  preset("gate-tight", "Tight", "gate", { threshold: -32, attack: 0.001, hold: 0.015, release: 0.07, range: -48 }),
  preset("gate-soft", "Soft", "gate", { threshold: -48, attack: 0.008, hold: 0.04, release: 0.18, range: -24 }),
  preset("gate-hard", "Hard", "gate", { threshold: -24, attack: 0.0005, hold: 0.01, release: 0.04, range: -80 }),
  preset("sidechain-pump", "Pump", "sidechain", { threshold: -28, ratio: 8, attack: 0.002, release: 0.18, amount: 1 }),
  preset("sidechain-gentle", "Gentle", "sidechain", {
    threshold: -18,
    ratio: 3,
    attack: 0.01,
    release: 0.3,
    amount: 0.65,
  }),
  preset("sidechain-deep", "Deep", "sidechain", { threshold: -36, ratio: 12, attack: 0.001, release: 0.28, amount: 1 }),
  preset("sidechain-mb", "Multiband Pump", "sidechain", {
    threshold: -22,
    ratio: 8,
    attack: 0.003,
    release: 0.18,
    amount: 0.9,
    splitFreq: 150,
  }),
  preset("chorus-subtle", "Subtle", "chorus", { rate: 0.35, depth: 0.25, mix: 0.18 }),
  preset("chorus-wide", "Wide", "chorus", { rate: 0.6, depth: 0.7, mix: 0.45 }),
  preset("chorus-doubler", "Doubler", "chorus", { rate: 1.2, depth: 0.45, mix: 0.55 }),
  preset("chorus-tight", "Tight", "chorus", { rate: 0.5, depth: 0.35, spread: 0, mix: 0.35 }),
  preset("delay-slap", "Slapback", "delay", { time: 120, sync: 0, pingPong: 0, feedback: 0.15, tone: 6000, mix: 0.2 }),
  preset("delay-pingpong", "Ping-Pong 1/8", "delay", {
    time: 375,
    sync: 2,
    pingPong: 1,
    feedback: 0.45,
    tone: 5000,
    mix: 0.3,
  }),
  preset("delay-dub", "Dub 1/4", "delay", {
    time: 500,
    sync: 1,
    pingPong: 0,
    feedback: 0.65,
    tone: 2500,
    mix: 0.35,
  }),
  // Multi-Tap — rhythmic fill delays (call-and-response, ping-pong hats)
  preset("multitap-16th-run", "16th Run", "multiTapDelay", {
    taps: 4,
    t1Div: 6,
    t2Div: 6,
    t3Div: 6,
    t4Div: 6,
    spread: 0.8,
    feedback: 0.2,
    tone: 5200,
    mix: 0.28,
  }),
  preset("multitap-dotted-stairs", "Dotted Stairs", "multiTapDelay", {
    taps: 3,
    t1Div: 0,
    t2Div: 2,
    t3Div: 4,
    t4Div: 6,
    spread: 0.7,
    feedback: 0.35,
    tone: 4200,
    mix: 0.3,
  }),
  preset("multitap-pingpong-hats", "Ping-Pong Hats", "multiTapDelay", {
    taps: 2,
    t1Div: 4,
    t2Div: 6,
    t3Div: 4,
    t4Div: 6,
    spread: 1,
    feedback: 0.12,
    tone: 7500,
    mix: 0.22,
  }),
  preset("multitap-dub-cascade", "Dub Cascade", "multiTapDelay", {
    taps: 4,
    t1Div: 2,
    t2Div: 4,
    t3Div: 6,
    t4Div: 7,
    spread: 0.6,
    feedback: 0.55,
    tone: 2400,
    mix: 0.35,
  }),
  // KYX Kaskáda — character delay presets
  preset("kaskada-tape-echo", "Tape Echo", "kaskada", {
    time: 375,
    sync: 0,
    pingPong: 0,
    feedback: 0.45,
    toneLp: 3500,
    toneHp: 150,
    drive: 0.35,
    modRate: 0.8,
    modDepth: 0.3,
    spread: 0.6,
    freeze: 0,
    character: 1,
    mix: 0.25,
    level: -6,
  }),
  preset("kaskada-pp-wide", "Ping-Pong Wide", "kaskada", {
    time: 500,
    sync: 0,
    pingPong: 1,
    feedback: 0.55,
    toneLp: 6000,
    toneHp: 200,
    drive: 0,
    modRate: 0.3,
    modDepth: 0.1,
    spread: 0.9,
    freeze: 0,
    character: 0,
    mix: 0.3,
    level: -6,
  }),
  preset("kaskada-hat-sync", "Sync Hat Echo", "kaskada", {
    time: 250,
    sync: 2,
    pingPong: 1,
    feedback: 0.22,
    toneLp: 7200,
    toneHp: 500,
    drive: 0.05,
    modRate: 0.6,
    modDepth: 0.08,
    spread: 0.9,
    freeze: 0,
    character: 0,
    mix: 0.2,
    level: -6,
  }),
  preset("kaskada-slap-back", "Slap Back", "kaskada", {
    time: 120,
    sync: 0,
    pingPong: 0,
    feedback: 0.15,
    toneLp: 8000,
    toneHp: 200,
    drive: 0,
    modRate: 0.5,
    modDepth: 0,
    spread: 0.3,
    freeze: 0,
    character: 0,
    mix: 0.18,
    level: -6,
  }),
  preset("kaskada-dub-space", "Dub Space", "kaskada", {
    time: 650,
    sync: 0,
    pingPong: 1,
    feedback: 0.75,
    toneLp: 2500,
    toneHp: 100,
    drive: 0.6,
    modRate: 0.4,
    modDepth: 0.2,
    spread: 0.7,
    freeze: 0,
    character: 2,
    mix: 0.4,
    level: -8,
  }),
  preset("kaskada-ambient-wash", "Ambient Wash", "kaskada", {
    time: 850,
    sync: 0,
    pingPong: 0,
    feedback: 0.8,
    toneLp: 3000,
    toneHp: 80,
    drive: 0.2,
    modRate: 0.3,
    modDepth: 0.45,
    spread: 1,
    freeze: 0,
    character: 1,
    mix: 0.55,
    level: -10,
  }),
  preset("kaskada-tight-double", "Tight Double", "kaskada", {
    time: 80,
    sync: 0,
    pingPong: 0,
    feedback: 0,
    toneLp: 10000,
    toneHp: 100,
    drive: 0,
    modRate: 0.5,
    modDepth: 0,
    spread: 0.3,
    freeze: 0,
    character: 0,
    mix: 0.3,
    level: -6,
  }),

  /* ────────────── FX Expansion (beatmaking pass) ────────────── */

  preset("ringmod-steel", "Steel Perc", "ringMod", { frequency: 830, feedback: 0, mix: 1 }),
  preset("ringmod-robot", "Robot Ring", "ringMod", { frequency: 95, feedback: 0.4, mix: 1 }),
  preset("ringmod-arc", "Arc Ring", "ringMod", { frequency: 1400, feedback: 0.7, mix: 0.8 }),

  stepPreset(
    "tapestop-8th",
    "Stop 1/2 Bar",
    "tapeStop",
    { engaged: 1, time: 0.6, curve: 0, spin: 0, mix: 1 },
    [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  ),
  preset("tapestop-slow", "Slow Stop", "tapeStop", { engaged: 1, time: 4, curve: 0, spin: 0, mix: 1 }),
  preset("tapest-op-rev", "Rev Spin", "tapeStop", { engaged: 1, time: 2, curve: 1, spin: 1, mix: 1 }),

  preset("freqshift-sub", "Sub Drift", "freqShifter", { shift: -38, mix: 1 }),
  preset("freqshift-metal", "Metal Air", "freqShifter", { shift: 620, mix: 0.7 }),
  // Frequency Shifter suite — the new modules are what make these audible.
  preset("freqshift-wide", "Wide Drift", "freqShifter", {
    shift: 180,
    fine: 0,
    side: 0,
    lfoRate: 0.15,
    lfoDepth: 0,
    feedback: 0,
    delayTime: 30,
    drive: 0,
    tone: 16000,
    spread: 1,
    mix: 0.65,
  }),
  preset("freqshift-barberpole", "Barberpole", "freqShifter", {
    shift: 90,
    fine: 0,
    side: 0,
    lfoRate: 0.4,
    lfoDepth: 220,
    feedback: 0,
    delayTime: 30,
    drive: 0,
    tone: 12000,
    spread: 0.3,
    mix: 0.8,
  }),
  preset("freqshift-kosmische", "Kosmische Seq", "freqShifter", {
    shift: 310,
    fine: 0,
    side: 0,
    lfoRate: 0.08,
    lfoDepth: 40,
    feedback: 0.72,
    delayTime: 48,
    drive: 0.25,
    tone: 8000,
    spread: 0.5,
    mix: 0.55,
  }),
  preset("freqshift-subdrop", "Sub Drop", "freqShifter", {
    shift: 0,
    fine: 0,
    side: 1,
    lfoRate: 0.1,
    lfoDepth: 0,
    feedback: 0.35,
    delayTime: 60,
    drive: 0.3,
    tone: 3000,
    spread: 0,
    mix: 0.7,
  }),
  preset("freqshift-ringboth", "Ring Both", "freqShifter", {
    shift: 440,
    fine: 6,
    side: 2,
    lfoRate: 0.25,
    lfoDepth: 60,
    feedback: 0.2,
    delayTime: 22,
    drive: 0.4,
    tone: 10000,
    spread: 0.4,
    mix: 0.75,
  }),

  preset("pitchshift-down", "Chop −3", "pitchShift", { semitones: -3, fine: 0, grainMs: 45, width: 0.6, mix: 1 }),
  preset("pitchshift-up", "Chop +4", "pitchShift", { semitones: 4, fine: 0, grainMs: 38, width: 0.4, mix: 1 }),
  preset("pitchshift-wide", "Wide Detune", "pitchShift", { semitones: 0, fine: 12, grainMs: 70, width: 1, mix: 0.5 }),

  // Vinyl Suite — the presets lean on the individual module controls so they
  // are audibly distinct (AGE alone scales everything uniformly).
  preset("vinyl-78", "78 RPM Shellac", "vinyl", {
    amount: 1,
    crackle: 0.9,
    crackleTone: 1800,
    crackleDecay: 0.25,
    hiss: 0.75,
    hissTone: 4500,
    rumble: 0.5,
    rumbleTone: 70,
    wowRate: 1.1,
    wow: 0.85,
    flutterRate: 14,
    flutter: 0.5,
    drive: 0.35,
    year: 1,
    toneLp: 6500,
    toneHp: 150,
    width: 0,
    mix: 1,
  }),
  preset("vinyl-dusty-lofi", "Dusty Lo-Fi", "vinyl", {
    amount: 0.55,
    crackle: 0.5,
    crackleTone: 2400,
    crackleDecay: 0.45,
    hiss: 0.4,
    hissTone: 5200,
    rumble: 0.15,
    rumbleTone: 55,
    wowRate: 0.6,
    wow: 0.45,
    flutterRate: 9,
    flutter: 0.25,
    drive: 0.2,
    year: 0.7,
    toneLp: 11000,
    toneHp: 40,
    width: 0.5,
    mix: 1,
  }),
  preset("vinyl-club-clean", "Club Clean", "vinyl", {
    amount: 0.12,
    crackle: 0.08,
    crackleTone: 3500,
    crackleDecay: 0.6,
    hiss: 0.12,
    hissTone: 8000,
    rumble: 0,
    rumbleTone: 50,
    wowRate: 0.5,
    wow: 0.1,
    flutterRate: 12,
    flutter: 0.05,
    drive: 0,
    year: 0.2,
    toneLp: 16000,
    toneHp: 20,
    width: 1,
    mix: 1,
  }),
  preset("vinyl-tape-wobble", "Tape Wobble", "vinyl", {
    // Wow/flutter forward, artefacts near zero — a pitch-drift machine.
    amount: 0.2,
    crackle: 0.05,
    crackleTone: 2500,
    crackleDecay: 0.5,
    hiss: 0.25,
    hissTone: 7000,
    rumble: 0,
    rumbleTone: 60,
    wowRate: 1.4,
    wow: 1,
    flutterRate: 7,
    flutter: 0.7,
    drive: 0.15,
    year: 0.35,
    toneLp: 13000,
    toneHp: 30,
    width: 1,
    mix: 1,
  }),
  preset("vinyl-phonk-crush", "Phonk Crush", "vinyl", {
    // Drive + narrow band — the dark, saturated phonk/memphis tone.
    amount: 0.7,
    crackle: 0.6,
    crackleTone: 1500,
    crackleDecay: 0.35,
    hiss: 0.55,
    hissTone: 3800,
    rumble: 0.65,
    rumbleTone: 45,
    wowRate: 0.4,
    wow: 0.3,
    flutterRate: 10,
    flutter: 0.2,
    drive: 0.75,
    year: 0.85,
    toneLp: 5200,
    toneHp: 90,
    width: 0.3,
    mix: 1,
  }),
  preset("vinyl-radio-1930", "Radio 1930", "vinyl", {
    // Extreme year contour + narrow width: a broadcast-band restoration.
    amount: 0.85,
    crackle: 0.65,
    crackleTone: 3000,
    crackleDecay: 0.7,
    hiss: 0.8,
    hissTone: 9000,
    rumble: 0.3,
    rumbleTone: 100,
    wowRate: 0.9,
    wow: 0.5,
    flutterRate: 18,
    flutter: 0.4,
    drive: 0.4,
    year: 1,
    toneLp: 3200,
    toneHp: 280,
    width: 0,
    mix: 1,
  }),

  preset("multitap-quarter", "Quarters", "multiTapDelay", {
    taps: 3,
    t1Div: 2,
    t2Div: 4,
    t3Div: 6,
    t4Div: 0,
    spread: 0.8,
    feedback: 0.25,
    tone: 5000,
    mix: 0.35,
  }),
  preset("multitap-wide", "Wide Eighths", "multiTapDelay", {
    taps: 4,
    t1Div: 4,
    t2Div: 4,
    t3Div: 4,
    t4Div: 2,
    spread: 1,
    feedback: 0.35,
    tone: 4000,
    mix: 0.3,
  }),
  // Vocoder — carrier (this track) sculpted by the routed modulator track.
  preset("vocoder-robot", "Robot", "vocoder", {
    bands: 16,
    loFreq: 120,
    hiFreq: 7000,
    q: 5,
    attack: 0.003,
    release: 0.05,
    shift: 0,
    sibilance: 0.3,
    stereo: 0.4,
    level: 0,
    mix: 1,
  }),
  preset("vocoder-choir", "Choir Pad", "vocoder", {
    // Wide, slow, low-sharpness: a lush evolving choir from any carrier.
    bands: 12,
    loFreq: 150,
    hiFreq: 5500,
    q: 2.2,
    attack: 0.03,
    release: 0.35,
    shift: 0,
    sibilance: 0.15,
    stereo: 1,
    level: -2,
    mix: 0.85,
  }),
  preset("vocoder-deep-robot", "Deep Robot", "vocoder", {
    // Formant shifted down: monster/deep-voice character.
    bands: 16,
    loFreq: 80,
    hiFreq: 4500,
    q: 6,
    attack: 0.005,
    release: 0.08,
    shift: -12,
    sibilance: 0.45,
    stereo: 0.3,
    level: 1,
    mix: 1,
  }),
  preset("vocoder-whisper", "Whisper", "vocoder", {
    // Sibilance-dominant: breathy, voice-forward texture.
    bands: 16,
    loFreq: 200,
    hiFreq: 9000,
    q: 8,
    attack: 0.001,
    release: 0.03,
    shift: 0,
    sibilance: 0.9,
    stereo: 0.7,
    level: -3,
    mix: 0.75,
  }),
  preset("vocoder-talkbox", "Talkbox", "vocoder", {
    // Tight bands + fast envelopes: classic funk talkbox articulation.
    bands: 16,
    loFreq: 180,
    hiFreq: 5000,
    q: 12,
    attack: 0.002,
    release: 0.04,
    shift: 5,
    sibilance: 0.6,
    stereo: 0.2,
    level: 0,
    mix: 1,
  }),
  // Reverse Swell — live reverse-envelope risers (no reversed sample needed).
  preset("reverseswell-drop-riser", "Drop Riser", "reverseSwell", {
    engaged: 0,
    time: 2,
    reach: 2,
    curve: 0.6,
    tone: 12000,
    level: 0,
    mix: 1,
  }),
  preset("reverseswell-tape-dive", "Tape Dive", "reverseSwell", {
    // reach >> time: the reverse read crawls (slow dive into the drop).
    engaged: 0,
    time: 4,
    reach: 8,
    curve: 0.35,
    tone: 7000,
    level: 0,
    mix: 1,
  }),
  preset("reverseswell-chirp", "Rising Chirp", "reverseSwell", {
    // reach < time: the reverse read runs fast (octave-ish riser chirp).
    engaged: 0,
    time: 1.5,
    reach: 0.5,
    curve: 0.85,
    tone: 16000,
    level: -2,
    mix: 0.9,
  }),
  preset("reverseswell-sub-swell", "Sub Swell", "reverseSwell", {
    engaged: 0,
    time: 3,
    reach: 3,
    curve: 0.5,
    tone: 2000,
    level: 1,
    mix: 1,
  }),
  // Granular Freeze — send-bus texture holds (no reversed sample needed).
  preset("granularfreeze-pad-hold", "Pad Hold", "granularFreeze", {
    freeze: 0,
    window: 3,
    position: 0.5,
    drift: 0.3,
    grainMs: 120,
    scatter: 0.25,
    pitch: 0,
    tone: 9000,
    level: 0,
    mix: 1,
  }),
  preset("granularfreeze-shimmer", "Shimmer Cloud", "granularFreeze", {
    // +12 st cloud with wide scatter — an octave-up shimmer pad.
    freeze: 0,
    window: 2,
    position: 0.5,
    drift: 0.45,
    grainMs: 70,
    scatter: 0.6,
    pitch: 12,
    tone: 14000,
    level: -2,
    mix: 0.85,
  }),
  preset("granularfreeze-deep-drone", "Deep Drone", "granularFreeze", {
    // −12 st, long grains, low tone: a sub-drone freeze under the drop.
    freeze: 0,
    window: 4,
    position: 0.35,
    drift: 0.15,
    grainMs: 320,
    scatter: 0.12,
    pitch: -12,
    tone: 3200,
    level: 0,
    mix: 1,
  }),
  preset("granularfreeze-glitch-cloud", "Glitch Cloud", "granularFreeze", {
    // Tiny grains + full scatter: stuttering micro-texture.
    freeze: 0,
    window: 1.5,
    position: 0.6,
    drift: 0.7,
    grainMs: 25,
    scatter: 1,
    pitch: 5,
    tone: 12000,
    level: -3,
    mix: 0.9,
  }),
  preset("granularfreeze-tape-hold", "Tape Hold", "granularFreeze", {
    // Dark, slow, no scatter — the "locked tape loop" character.
    freeze: 0,
    window: 6,
    position: 0.5,
    drift: 0.08,
    grainMs: 200,
    scatter: 0,
    pitch: 0,
    tone: 5000,
    level: 0,
    mix: 1,
  }),

  // Telephone pack — SVF narrow-band + distortion character (no new DSP):
  // the lo-fi phone/handset chain beatmakers reach for on hooks and fills.
  preset("svf-telephone-band", "Telephone Band", "svFilter", {
    cutoff: 1700,
    resonance: 0.55,
    mode: 2, // HP
    drive: 0.2,
    mix: 1,
  }),
  preset("svf-telephone-band2", "Handset Lo", "svFilter", {
    cutoff: 600,
    resonance: 0.3,
    mode: 1, // BP
    drive: 0.35,
    mix: 1,
  }),
  preset("svf-radio-mid", "Radio Mid", "svFilter", {
    cutoff: 2400,
    resonance: 0.7,
    mode: 1, // BP
    drive: 0.15,
    mix: 1,
  }),
  preset("dist-telephone", "Telephone Drive", "distortion", {
    drive: 0.62,
    tone: 3200,
    mix: 1,
    output: -2,
  }),
  preset("dist-intercom", "Intercom", "distortion", {
    drive: 0.8,
    tone: 2000,
    mix: 0.9,
    output: -4,
  }),

  manglerPreset(
    "beatmangler-halftime",
    "Halftime",
    { playMode: 0, repeatFill: 0, trigger: 1, interval: 0, offset: 0, chance: 1, gate: 2, mix: 0.8 },
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  ),
  manglerPreset(
    "beatmangler-skip",
    "Skip 16ths",
    { playMode: 0, repeatFill: 0, trigger: 1, interval: 4, offset: 0, chance: 0.75, gate: 4, mix: 0.75 },
    [1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0],
  ),
];

export function presetsForEffect(type: EffectType): EffectPreset[] {
  return CORE_EFFECT_PRESETS.filter((item) => item.type === type);
}
