/**
 * Generated by scripts/measure-fx-preset-loudness.mjs.
 * Factory FX output compensation, measured per effect type from a fixed
 * percussive reference loop. Empty maps are the safe 0 dB fallback until the
 * measurement script is run after adding or changing factory presets.
 */
export const FACTORY_FX_PRESET_GAIN_DB: Record<string, number> = {};
export const FACTORY_FX_CHAIN_GAIN_DB: Record<string, number> = {};
